docs/en/install-upgrade/highlights.asciidoc
- docs: update apm include (#1387)
=> [7.9] docs: update apm include (#1387)

docs/en/install-upgrade/highlights.asciidoc
- docs: update apm include (#1387)
=> [7.x] docs: update apm include (#1387)

docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
This PR adds a new item to the DFA limitations list about jobs that are restarting after an Elasticsearch upgrade.
[DFA restart limitation](https://stack-docs_1384.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html#dfa-restart)
=> [DOCS] Adds limitation item about restarting DFA job after upgrade

docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Adds limitation item about restarting DFA job after upgrade (#1384)
=> [7.x] [DOCS] Adds limitation item about restarting DFA job after upgrade (#1384)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Related to https://github.com/elastic/kibana/pull/76023
This PR adds the new machine learning jobs for the Elastic Security app to the list in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html
* https://stack-docs_1363.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html
* https://stack-docs_1363.docs-preview.app.elstc.co/guide/en/security/master/prebuilt-ml-jobs.html
=> [DOCS] Add metadata and discovery analysis jobs for security integration

docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR adds documentation to Metrics integration ML modules added in https://github.com/elastic/kibana/pull/76460
[Metrics jobs](https://stack-docs_1366.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-metrics-ui.html)
=> [DOCS] Adds Metrics AD configurations to OOTB jobs

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
This PR changes the links on the metrics and logs related OOTB job pages to point to the Observability guide instead of the Kibana docs. It also removes the link from the uptime OOTB job page.
[Logs jobs](https://stack-docs_1402.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-logs-ui.html)
[Uptime jobs](https://stack-docs_1402.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-uptime.html)
Backport these changes to 7.x, and 7.10 after https://github.com/elastic/kibana/pull/79978 is merged. Then add the uptime link to the uptime OOTB job page in a separate PR.
=> [DOCS] Changes links in OOTB job descriptions

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
This PR removes the links that point to the Kibana guide from the Metrics, Logs, and Uptime related OOTB job definition pages. https://github.com/elastic/kibana/pull/79978 will move Metrics, Logs, and Uptime related content from the Kibana guide to the Observability guide. As the links handled in this PR point to the Kibana guide, they make the docs CI check fail in the above-mentioned PR. Removal of these links will solve the issue.
Applies to 7.x and 7.10.
[Metrics OOTB jobs]()
[Logs OOTB jobs]()
[Uptime OOTB jobs]()
**Add the appropriate links, after https://github.com/elastic/kibana/pull/79978 is merged.**
=> [7.x][DOCS] Remove links from OOTB jobs

docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
This PR expands the regression evaluation conceptual docs with `MSLE` and `Huber`. It also adds links that point to the loss function section in the regression conceptual.
[Regression evaluation](https://stack-docs_1398.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfanalytics-evaluate.html#ml-dfanalytics-regression-evaluation)
=> [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs

docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
- [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)
=> [7.x] [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)

docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
- [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)
=> [7.10] [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)

docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
- [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)
=> [7.9] [DOCS] Adds MSLE and Huber evaluation metrics to conceptual docs (#1398)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
- [DOCS] Changes links in OOTB job descriptions (#1402)
=> [7.x] [DOCS] Changes links in OOTB job descriptions (#1402)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
- [DOCS] Changes links in OOTB job descriptions (#1402)
=> [7.10] [DOCS] Changes links in OOTB job descriptions (#1402)

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/63479
This PR updates the "coming" tags and enables the Elasticsearch breaking changes content.
=> [DOCS] Update coming tags in Installation and Upgrade Guide

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
This PR adds a link that points to the `Monitor uptime data` page in the Observability guide to the Uptime pre-defined anomaly detection job description.
[Uptime OOTB job](https://stack-docs_1414.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-uptime.html)
=> [DOCS] Adds link to Uptime OOTB job description

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
- [DOCS] Adds link to Uptime OOTB job description. (#1414)
=> [7.x] [DOCS] Adds link to Uptime OOTB job description. (#1414)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
- [DOCS] Adds link to Uptime OOTB job description. (#1414)
=> [7.10] [DOCS] Adds link to Uptime OOTB job description. (#1414)

docs/en/getting-started/get-started-stack.asciidoc
This PR updates the links at the end of the `Getting started with the Elastic Stack` page to point to the relevant pages in the Observability guide.
https://github.com/elastic/docs/pull/1985
[GS with the Stack – What's next?](https://stack-docs_1422.docs-preview.app.elstc.co/guide/en/elastic-stack-get-started/master/get-started-elastic-stack.html#whats_next)
=> [DOCS] Changes links in stack getting started to point to the Observability guide

docs/en/getting-started/get-started-stack.asciidoc
- [DOCS] Changes links in stack getting started to point to the Observability guide (#1422)
=> [7.x] [DOCS] Changes links in stack getting started to point to the Observability guide (#1422)

docs/en/getting-started/get-started-stack.asciidoc
- [DOCS] Changes links in stack getting started to point to the Observability guide (#1422)
=> [7.10] [DOCS] Changes links in stack getting started to point to the Observability guide (#1422)

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/redirects.asciidoc
Replaces the APM highlights with Observability.
https://stack-docs_1435.docs-preview.app.elstc.co/guide/en/elastic-stack/master/observability-highlights.html
For https://github.com/elastic/observability-docs/issues/222.
For https://github.com/elastic/apm-server/pull/4385.
=> docs: change APM to Observability highlights

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/redirects.asciidoc
- docs: change APM to Observability (#1435)
=> [7.x] docs: change APM to Observability (#1435)

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/redirects.asciidoc
- docs: change APM to Observability (#1435)
=> [7.10] docs: change APM to Observability (#1435)

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/redirects.asciidoc
Replaces the Beats highlights with a link to the Observability What's new topic.
Related PR: https://github.com/elastic/beats/pull/22475
=> Redirect Beats highlights to the observability "what's new" topic

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/redirects.asciidoc
- Redirect Beats highlights to the observability what's new topic (#1440)
=> [7.x] Redirect Beats highlights to the observability what's new topic (#1440)

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/redirects.asciidoc
- Redirect Beats highlights to the observability what's new topic (#1440)
=> [7.10] Redirect Beats highlights to the observability what's new topic (#1440)

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR removes the "coming" tags from the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/7.10/index.html)
=> Remove coming tags

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
This PR adds a new item to the Anomaly Detection at scale piece about setting the `scroll_size` of a datafeed.
[AD at scale - Set the `scroll_size` of a datafeed](https://stack-docs_1445.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-detection-scale.html#set-scroll-size)
=> [DOCS] Adds scroll_size related recommendation to AD at scale

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
This PR puts the sentence that states the consideration only applies to datafeeds that don't use aggregations to the beginning of the paragraph, so the statement is clearer.
[Set the `scroll_size` of the datafeed](https://stack-docs_1456.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-detection-scale.html#set-scroll-size)
=> [DOCS] Fine-tunes scroll_size related recommendation in AD at scale

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)
=> [7.x] [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)
=> [7.10] [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)
=> [7.9] [DOCS] Fine-tunes scroll_size related recommendation in AD at scale. (#1456)

docs/en/stack/ml/setup.asciidoc
This PR updates the machine learning security privilege setup information (https://www.elastic.co/guide/en/machine-learning/master/setup.html#setup-privileges) to mention the use of the Stack Management app and clarify that the use of the built-in roles is for scenarios where you're not using Kibana.
https://stack-docs_1453.docs-preview.app.elstc.co/guide/en/machine-learning/master/setup.html#setup-privileges
=> [DOCS] Clarify machine learning setup

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc, docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
This PR:
* arranges the anomaly detection related limitations into four groups (and adds a short explanation about them to the intro):
* Platform
* Configuration
* Operation
* UI
* comments out `Jobs close on the datafeed end date` as the described behavior is not a limitation. (This information will be published in the AD feature documentation in a separate PR, then removed from this piece.)
* removes the following limitations:
* Jobs must be stopped before updates (changed in 6.3)
* Date nanoseconds data types are not supported (changed in 7.7)
* amends the following limitations:
* Security integration
* Anomaly Explorer and Single Metric Viewer omissions and limitations
* Jobs created in Kibana use model plot config and pre-aggregated data.
(This PR **does not** remove `Machine …
=> [DOCS] Reviews anomaly detection limitations

docs/en/glossary/glossary.asciidoc
Per elastic/elasticsearch#42720, we're refactoring rollups to phase out rollup jobs and special rollup indices.
The functionality may be around for a while, but I'd like to remove these items from the glossary. They're pulled from ES `master` where I'm removing the source defs. Once the refactor is finished, rollup jobs/indices are not something new users are likely to run into or something we want to promote.
If wanted, I can hold off on merging until closer to launch.
Relates to elastic/elasticsearch#65519
=> [DOCS] Remove legacy rollup glossary items

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
This PR adds a subsection about how to move trained models between clusters to the `Trained models` section.
[Trained models – Moving a trained model between clusters](https://stack-docs_1439.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-trained-models.html#move-between-clusters)
=> [DOCS] Adds Moving trained models between clusters to docs

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
- [DOCS] Adds Moving trained models between clusters to docs (#1439)
=> [7.x] [DOCS] Adds Moving trained models between clusters to docs (#1439)

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
This PR fixes the level of the `Moving a model to the Elastic Stack` section.
[Moving a model to the Elastic Stack]()
=> [DOCS] Fixes section level in Trained models docs

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
- [DOCS] Fixes section level in Trained models docs. (#1482)
=> [7.x] [DOCS] Fixes section level in Trained models docs. (#1482)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR:
* adds the recognizer query link to the descriptions of the supplied configurations,
* puts a link that points to the Creating AD jobs tutorial page to the OOTB ML jobs listing page,
* adds a note about the recognizer queries to the listing page,
* expands the docs with info about where you can create Logs and Metrics related jobs.
[OOTB ML jobs](https://stack-docs_1477.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs.html)
=> [DOCS] Expands supplied configurations docs

docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
- [DOCS] Fixes API quick reference for trained models (#1486)
=> [7.x] [DOCS] Fixes API quick reference for trained models (#1486)

docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
- [DOCS] Fixes API quick reference for trained models (#1486)
=> [7.10] [DOCS] Fixes API quick reference for trained models (#1486)

docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
As stated in the title.
[Language identification](https://stack-docs_1489.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-lang-ident.html)
=> [DOCS] Fixes a typo in language identification docs

docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
=> [7.x] [DOCS] Fixes a typo in language identification docs. (#1489)

docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
=> [7.10] [DOCS] Fixes a typo in language identification docs. (#1489)

docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
=> [7.9] [DOCS] Fixes a typo in language identification docs. (#1489)

docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
=> [7.8] [DOCS] Fixes a typo in language identification docs. (#1489)

docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
=> [7.7] [DOCS] Fixes a typo in language identification docs. (#1489)

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
- [DOCS] Fixes comment block on trained models page. (#1495)
=> [7.x] [DOCS] Fixes comment block on trained models page. (#1495)

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- [DOCS] Adds runtime field limitation to AD limitations (#1372)
=> [7.x] [DOCS] Adds runtime field limitation to AD limitations (#1372)

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
This version is a suggestion to make the instructions more concise and
to make use of only two tools (curl, jq) from the command line. This
makes prerequisites fewer, and following along easier. There are some
minor grammatical changes to the section on importing models trained
outside the Stack which hopefully also makes the terminology a bit more
in line with common parlance.
Notes:
- Apologies in advance for my terrible knowledge of AsciiDoc. Please have
a good review of my formatting!
- This has also been tested only on
v7.11-SNAPSHOT and makes use of the `exclude_generated` flag only
available in `7.x` and `master` branches, making this documentation
not applicable to the `7.10` branch.
- I've used the full commands which include `localhost` and a specific
username/password. I don't …
=> [DOCS] Updates guide to exporting/importing models

docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1470
=> [7.x][DOCS] Add machine learning overview to tutorial (#1470)

docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1470
=> [7.11][DOCS] Add machine learning overview to tutorial (#1470)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
This PR fixes the URL for the manifest files in pages such as https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-apache.html
It uses the "branch" attribute from shared files such as https://github.com/elastic/docs/blob/master/shared/versions/stack/master.asciidoc.
=> [DOCS] Fixes branch in path to module

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Changes:
- Removes the `/reference/` dir from the ES highlights include
- Updates the `coming` tags for the 7.12.0 release
- Updates several includes links for 7.12.0
=> [DOCS] Fix highlights include. Fix coming tags

docs/en/install-upgrade/breaking.asciidoc
Ready the APM Breaking changes.
Will fail until https://github.com/elastic/apm-server/pull/4600 is merged and backported.
=> [7.11] docs: Ready APM breaking changes

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
This PR updates the anomaly detection and data frame analytics limitations with details about space-aware machine learning objects.
* https://stack-docs_1503.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html#dfa-space-limitations
* https://stack-docs_1503.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-limitations.html#ml-space-limitations
=> [DOCS] Add space limitations for ML objects

docs/en/install-upgrade/upgrading-stack.asciidoc
As per the new licensing change for Elasticsearch and Kibana (explained in great detail [in this blog post](https://www.elastic.co/blog/licensing-change)) this pull request removes outdated information about basic and trial licenses from the Installation and Upgrade Guide.
https://stack-docs_1527.docs-preview.app.elstc.co/guide/en/elastic-stack/master/upgrading-elastic-stack.html
=> [DOCS] Remove unnecessary license details

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
This update will point directly to the eland API which has an example and full list of supported models. This is the right place to document limitations as this is where it's implemented.
=> Updates instructions on how to import models

docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Relates to elastic/elasticsearch#66885
=> Add known issue for zero memory on Debian 8

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
PR [#68051](https://github.com/elastic/elasticsearch/pull/68051) in the Elasticsearch repo is making changes to the networking docs, which impacts the HTTP settings. Specifically, `modules-http` is changing to `modules-network`, with the HTTP settings nested underneath. 
I checked out that PR locally and built the docs, and the resulting URL for the new HTTP section results in `.../guide/modules-network.html#http-settings`. This ML link must be updated for the ES build to pass.
=> [DOCS] Update ML link for ES #68051

docs/en/install-upgrade/highlights.asciidoc
This PR makes the Kibana release highlights visible in the Installation and Upgrade Guide.
Related to https://github.com/elastic/kibana/pull/90238
=> [DOCS] Add Kibana highlights to Install & Upgrade Guide

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Related to https://github.com/elastic/kibana/pull/85065
This PR adds documentation for the new modules in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html, based on the details in https://github.com/elastic/kibana/tree/master/x-pack/plugins/ml/server/models/data_recognizer/modules/security_linux and https://github.com/elastic/kibana/tree/master/x-pack/plugins/ml/server/models/data_recognizer/modules/security_windows and the existing job descriptions.
* https://stack-docs_1504.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html#security-linux-jobs
* https://stack-docs_1504.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html#security-windows-jobs
=> [DOCS] Adds security_linux and security_windows modules

docs/en/getting-started/docker/docker-compose.yml
The current example exposes the `9201` and `9202` ports. However, this isn't necessary.
Closes #1511
=> [DOCS] Remove unneeded ports from `docker-compose.yml` example

docs/en/getting-started/docker/docker-compose.yml
- [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)
=> [7.x] [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)

docs/en/getting-started/docker/docker-compose.yml
- [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)
=> [7.11] [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)

docs/en/getting-started/docker/docker-compose.yml
- [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)
=> [7.10] [DOCS] Remove unneeded ports from `docker-compose.yml` example (#1559)

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
This PR adds a link that points to the `Classification class assignment objective` Jupyter notebook to the `class_score` section of the classification conceptual docs.
[Classification – `class_score`](https://stack-docs_1563.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-classification.html#dfa-classification-class-score)
=> [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
- [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)
=> [7.x] [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
- [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)
=> [7.11] [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
- [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)
=> [7.10] [DOCS] Adds link of Jupyter notebook about class assignment objective to classification docs (#1563)

docs/en/install-upgrade/highlights.asciidoc
* Removes coming tags from Release Highlights
* Removes stray `]` in "Highlights" intro. (I'll fix this in master, too)
=> Remove coming tags for 7.11

docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
This PR adds links of recently published blog posts to the DFA examples page.
[DFA examples](https://stack-docs_1574.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfanalytics-examples.html)
=> [DOCS] Adds blog post links to DFA examples page

docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
- [DOCS] Adds blog post links to DFA examples page. (#1574)
=> [7.x] [DOCS] Adds blog post links to DFA examples page. (#1574)

docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
- [DOCS] Adds blog post links to DFA examples page. (#1574)
=> [7.11] [DOCS] Adds blog post links to DFA examples page. (#1574)

docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/69084
This PR aligns "ngram" terminology in the machine learning documentation with the "n-gram" recommendations in the [Elastic writing style guide](https://brand.elastic.co/302f66895/p/194a3b-writing-style-guide).
=> [DOCS] Fixes n-gram terminology

docs/en/glossary/glossary.asciidoc
This PR adds "custom rules" to the glossary and links to the following page: https://www.elastic.co/guide/en/machine-learning/current/ml-rules.html
=> [DOCS] Adds custom rules to glossary

docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc, docs/en/stack/ml/anomaly-detection/index.asciidoc
This PR adds the piece about anomaly detection alert type to the Examples section of the Anomaly detection chapter.
[Configuring anomaly detection alerts ](https://stack-docs_1573.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-configuring-alerts.html)
=> [DOCS] Adds anomaly detection alert config docs to ML book

docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc, docs/en/stack/ml/anomaly-detection/index.asciidoc
- [DOCS] Adds anomaly detection alert config docs to ML book (#1573)
=> [7.x] [DOCS] Adds anomaly detection alert config docs to ML book (#1573)

docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/68922
This PR adds a link to the new create trained model aliases API
=> [DOCS] Link to trained model aliases API

docs/en/stack/ml/df-analytics/ml-inference.asciidoc
This PR expands the conceptual documentation of the inference feature by adding a note about trained model aliases.
[Inference](https://stack-docs_1593.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-inference.html)
=> [DOCS] Expands inference conceptual with a note about aliases

docs/en/stack/ml/df-analytics/ml-inference.asciidoc
- [DOCS] Expands inference conceptual with a note about aliases. (#1593)
=> [7.x] [DOCS] Expands inference conceptual with a note about aliases. (#1593)

docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
This PR must be merged after https://github.com/elastic/elasticsearch/pull/69453
It adds a link in the Machine Learning Guide to the new preview data frame analytics API.
=> [DOCS] Link to preview data frame analytics API

docs/en/glossary/glossary.asciidoc
This PR adds the short definition of the `trained model` term to the glossary.
[Glossary: T](https://stack-docs_1596.docs-preview.app.elstc.co/guide/en/elastic-stack-glossary/master/terms.html#t-glos)
=> [DOCS] Adds trained model to glossary

docs/en/stack/ml/setup.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/69766 and https://github.com/elastic/elasticsearch/pull/68964
This PR updates the setup page in the Machine Learning Guide to indicate that some machine learning settings are affected by operator privileges.
=> [DOCS] Adds operator privileges to ML setup

docs/en/glossary/glossary.asciidoc
This PR adds three new terms to the glossary that are related to the feature `inference`:
* inference,
* inference aggregation,
* inference pipeline.
=> [DOCS] Adds inference related terms to glossary

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Backports https://github.com/elastic/stack-docs/pull/962
=> [7.x][DOCS] Clarifies machine learning rollup limitation (#962)

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Backports https://github.com/elastic/stack-docs/pull/962
=> [7.12][DOCS] Clarifies machine learning rollup limitation

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Backports https://github.com/elastic/stack-docs/pull/962
=> [7.11][DOCS] Clarifies machine learning rollup limitation

docs/en/glossary/glossary.asciidoc
Related to https://github.com/elastic/kibana/pull/94447
This PR removes the terms "alert" and "Alerts and Actions" from the glossary.
=> [DOCS] Removes obsolete terms from glossary

docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
This PR:
* arranges the DFA related limitations into four groups (and adds a short explanation about them to the intro):
* Platform
* Configuration
* Operation
* UI
* changes inference trained model terminology to trained model terminology where applies.
This PR is part of an effort that aims to make the AD, DFA, and Transforms limitations sections similar to each other in structure. Related PR: https://github.com/elastic/stack-docs/pull/1471
[DFA limitations](https://stack-docs_1607.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html)
=> [DOCS] Reorganizes DFA limitations

docs/en/glossary/glossary.asciidoc
Types were deprecated in 6.x and will not be supported in 8.x.
This removes the `type` definition from the Stack glossary.
Relates to https://github.com/elastic/elasticsearch/pull/70516
=> Remove ES `type` definition

docs/en/install-upgrade/breaking.asciidoc
Activates the include for Beats BCs.  Doc build will fail until  https://github.com/elastic/beats/pull/24646 is merged and backported.
@lcawl In situations where there are no breaking changes, I don't think we should send users down the rabbit hole, so I've removed the para that begins "This list summarizes the most important breaking changes..." WDYT? Good idea? Bad idea?
This approach only works if there really are *no* changes (even in the changelog). I think that's the case for Beats in 7.12 (I'll know for sure when 24646 is reviewed.)
=> Activate include for beats breaking changes

docs/en/glossary/glossary.asciidoc
Add some new and missing terms from the Elasticsearch glossary to the Stack glossary.
Relates to https://github.com/elastic/elasticsearch/pull/70516
=> [DOCS] Add missing ES terms to glossary

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR must be merged after https://github.com/elastic/kibana/pull/94771 , https://github.com/elastic/kibana/pull/95124, https://github.com/elastic/kibana/pull/94761, https://github.com/elastic/elasticsearch/pull/70533, https://github.com/elastic/elasticsearch/pull/70700
It adds some highlights and breaking changes to the Installation and Upgrade Guide.
https://stack-docs_1620.docs-preview.app.elstc.co/guide/en/elastic-stack/7.12/elastic-stack-highlights.html
https://stack-docs_1620.docs-preview.app.elstc.co/guide/en/elastic-stack/7.12/elastic-stack-breaking-changes.html
=> [DOCS] Add 7.12 highlights to Installation Upgrade Guide

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR removes "coming" tags now that 7.12.0 documentation is available.
=> [DOCS] Removes coming tags from highlights and breaking changes

docs/en/glossary/glossary.asciidoc
We've decided to adopt a new approach to the rollup refactor. This reverts commit a1f8f9cdaf9fe1b0c4a80b220658a3874875bc45 and restores some glossary definition for the current rollup functionality.
=> [DOCS] Restore rollup glossary items (#1473)

docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
This PR adds a mention of custom rules are called job rules in Kibana to the `Custom rules` section.
[Custom rules](https://stack-docs_1634.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-rules.html)
Do not merge this PR before https://github.com/elastic/kibana/pull/96999
=> [DOCS] Clarifies that custom rules are called job rules in Kibana

docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc
- [DOCS] Clarifies that custom rules are called job rules in Kibana. (#1634)
=> [7.x] [DOCS] Clarifies that custom rules are called job rules in Kibana. (#1634)

docs/en/glossary/glossary.asciidoc
This PR expands the glossary entry about custom rules by mentioning that they are referred to as job rules in Kibana.
[Glossary - C](https://stack-docs_1636.docs-preview.app.elstc.co/guide/en/elastic-stack-glossary/master/terms.html#c-glos)
=> [DOCS] Edits custom rules entry in Glossary

docs/en/stack/ml/get-started/ml-getting-started.asciidoc
This PR embeds the education video about single metric anomaly detection jobs in the machine learning getting started page. It uses the same method as pages like https://www.elastic.co/guide/en/observability/current/user-experience.html 
https://stack-docs_1638.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-getting-started.html#get-started-prereqs
=> [ML] Adds link to anomaly detection video

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Related to https://github.com/elastic/security-docs/pull/637
This PR removes the "beta" indicators from within https://www.elastic.co/guide/en/security/master/prebuilt-ml-jobs.html
=> [DOCS] Removes beta qualifiers from prebuilt ML jobs

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- [DOCS] Removes beta qualifiers from prebuilt ML jobs (#1641)
=> [7.x] [DOCS] Removes beta qualifiers from prebuilt ML jobs (#1641)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- [DOCS] Removes beta qualifiers from prebuilt ML jobs (#1641)
=> [7.13] [DOCS] Removes beta qualifiers from prebuilt ML jobs (#1641)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- [DOCS] Removes beta qualifiers from prebuilt ML jobs (#1641)
=> [7.12] [DOCS] Removes beta qualifiers from prebuilt ML jobs (#1641)

docs/en/getting-started/get-started-stack.asciidoc
The example shows very old lucene versions.
This should be backported to 7.13 and later.
=> Update example output to show recent versions

docs/en/getting-started/get-started-stack.asciidoc
- Update get-started-stack.asciidoc (#1650)
=> [7.13] Update get-started-stack.asciidoc (#1650)

docs/en/getting-started/get-started-stack.asciidoc
- Update get-started-stack.asciidoc (#1650)
=> [7.x] Update get-started-stack.asciidoc (#1650)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc, docs/en/stack/ml/setup.asciidoc
This PR adds an ES- and a Kibana-related subsection to the security info on the ML setup page. It also adds the warning about built-in roles in Kibana to the beginning of the section for better visibility.
Related to https://github.com/elastic/ml-team/issues/525
[ML setup](https://stack-docs_1649.docs-preview.app.elstc.co/guide/en/machine-learning/master/setup.html)
=> [DOCS] Separates ES and Kibana security info on ML setup page

docs/en/stack/ml/setup.asciidoc
- [DOCS] Separates ES and Kibana security info on ML setup page (#1649)
=> [7.x] [DOCS] Separates ES and Kibana security info on ML setup page (#1649)

docs/en/stack/ml/setup.asciidoc
- [DOCS] Separates ES and Kibana security info on ML setup page (#1649)
=> [7.13] [DOCS] Separates ES and Kibana security info on ML setup page (#1649)

docs/en/stack/ml/setup.asciidoc
- [DOCS] Separates ES and Kibana security info on ML setup page (#1649)
=> [7.12] [DOCS] Separates ES and Kibana security info on ML setup page (#1649)

docs/en/glossary/glossary.asciidoc
https://github.com/elastic/elasticsearch/pull/72946 marks the freeze API as deprecated. This removes a couple of glossary terms related to frozen indices.
Relates to https://github.com/elastic/elasticsearch/pull/72990 and https://github.com/elastic/elasticsearch/issues/70192.
=> Remove frozen index glossary terms

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
This PR adds some details about how to avoid jobs being tucked in "opening" state forever by using autoscaling (ESS) or setting up ML settings properly (on-prem).
[Anomaly detection at scale – Node sizing](https://stack-docs_1659.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-detection-scale.html#node-sizing)
=> [DOCS] Adds autoscaling info to Anomaly detection at scale

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)
=> [7.x] [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)
=> [7.13] [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)
=> [7.12] [DOCS] Adds autoscaling info to Anomaly detection at scale (#1659)

docs/en/glossary/glossary.asciidoc
Adds the `alias` glossary term. Removes the `index alias` term.
Depends on https://github.com/elastic/elasticsearch/pull/73065
=> [DOCS] Add `alias` glossary term

docs/en/glossary/glossary.asciidoc
Removes an unneeded anchor from the `alias` glossary entry.
Relates to https://github.com/elastic/elasticsearch/pull/73169.
=> [DOCS] Remove index alias anchor for `alias` glossary entry

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
* Adds APM 7.13 content
* Adds Observability 7.13 content
* Updates coming tags to 7.13.0
For https://github.com/elastic/observability-docs/issues/468.
Related to https://github.com/elastic/apm-server/pull/5281.
=> [7.13] Add 7.13 Observability and APM content

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
* Adds a placeholder for 7.14 APM content
* Updates coming tags to 7.14
Blocked by https://github.com/elastic/apm-server/pull/5281.
=> [7.14] Add APM placeholder for 7.14

docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc, docs/en/stack/ml/anomaly-detection/ml-recover-failed-jobs.asciidoc, docs/en/stack/ml/anomaly-detection/ml-restart-failed-jobs.asciidoc
This PR adds a new page to the anomaly detection documentation that explains how to recover from a failed job.
[Recover from a failed anomaly detection job](https://stack-docs_1667.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-recover-failed-jobs.html)
=> Adds page about recovering from a failed job to anomaly detection docs

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR must be merged *after* https://github.com/elastic/kibana/pull/100081 and https://github.com/elastic/kibana/pull/99978
It uncomments some tagged regions and fixes the "coming" tags in the Install and Upgrade Guide
=> [DOCS] Add highlights to Install Upgrade Guide

docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc, docs/en/stack/ml/anomaly-detection/ml-restart-failed-jobs.asciidoc
- Adds page about recovering from a failed job to anomaly detection docs (#1667)
=> [7.12] Adds page about recovering from a failed job to anomaly detection docs (#1667)

docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc, docs/en/stack/ml/anomaly-detection/ml-restart-failed-jobs.asciidoc
- Adds page about recovering from a failed job to anomaly detection docs (#1667)
=> [7.x] Adds page about recovering from a failed job to anomaly detection docs (#1667)

docs/en/glossary/glossary.asciidoc, docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR adds an item to the anomaly detection limitation section that explains what happens if the analyzed field contains an array.
[Arrays in analyzed fields are turned into comma-separated strings](https://stack-docs_1651.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-limitations.html#ml-arrays-limitations)
=> [DOCS] Adds item about fields containing arrays to anomaly detection limitations

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- [DOCS] Adds item about fields containing arrays to anomaly detection limitations (#1651)
=> [7.x] [DOCS] Adds item about fields containing arrays to anomaly detection limitations (#1651)

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- [DOCS] Adds item about fields containing arrays to anomaly detection limitations (#1651)
=> [7.12] [DOCS] Adds item about fields containing arrays to anomaly detection limitations (#1651)

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- [DOCS] Adds item about fields containing arrays to anomaly detection limitations (#1651)
=> [7.13] [DOCS] Adds item about fields containing arrays to anomaly detection limitations (#1651)

docs/en/getting-started/get-started-docker.asciidoc
If you use security in production, we recommend setting up TLS, even for the basic license.
Closes https://github.com/elastic/elasticsearch/issues/73800
https://stack-docs_1693.docs-preview.app.elstc.co/guide/en/elastic-stack-get-started/master/get-started-docker.html#get-started-docker-tls
=> [DOCS] Remove Gold license reference for TLS security

docs/en/getting-started/get-started-docker.asciidoc
- [DOCS] Remove Gold license reference for TLS security (#1693)
=> [7.x] [DOCS] Remove Gold license reference for TLS security (#1693)

docs/en/getting-started/get-started-docker.asciidoc
- [DOCS] Remove Gold license reference for TLS security (#1693)
=> [7.13] [DOCS] Remove Gold license reference for TLS security (#1693)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1681
=> [7.13][DOCS] Update list of Apache and Nginx ML modules (#1681)

docs/en/stack/page_header.html
Related to https://github.com/elastic/stack-docs/issues/1698
This PR adds a warning at the top of pages in the Stack Overview, which indicates that this is legacy documentation.
=> [DOCS] Add legacy header for Stack Overview

docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc, docs/en/stack/ml/get-started/ml-getting-started.asciidoc
This PR adds some metadata to the machine learning overview pages and the getting started tutorial, using the method described in https://docs.asciidoctor.org/asciidoc/latest/document/metadata/
It must be merged *after* https://github.com/elastic/docs/pull/2136
When you "view source" for these pages in a browser, it includes the metadata as follows:
````
<meta name="description" content="An introduction to machine learning data frame analytics, which ...">
<meta name="keywords" content="ML, Elasticsearch, data frame analytics, overview">
````
=> [DOCS] Adds ML document metadata

docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Adds a new limitation item to the DFA limitations section about nested fields.
[DFA limitations – Nested fields are not supported](https://stack-docs_1714.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html#dfa-nested-fields-limitations)
=> [DOCS] Adds nested fields related item to DFA limitations

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR adds a tip in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs.html for dealing with model memory limits.
* https://stack-docs_1271.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-detection-scale.html#set-model-memory-limit
* https://stack-docs_1271.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs.html
=> [DOCS] Add model memory tip for ML modules

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1271
=> [7.x][DOCS] Add model memory tip for ML modules (#1271)

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1271
=> [7.13][DOCS] Add model memory tip for ML modules (#1271)

docs/en/glossary/glossary.asciidoc
I'll unpublish and remove the glossary from the ES repo after this PR is merged.
https://stack-docs_1722.docs-preview.app.elstc.co/guide/en/elastic-stack-glossary/master/terms.html
=> [DOCS] Move ES glossary to stack docs

docs/en/stack/ml/anomaly-detection/job-tips.asciidoc, docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
Update to use attributes so https://github.com/elastic/elasticsearch/pull/74529 can be merged.
=> [DOCS] Update xrefs to time units section in ES guide

docs/en/stack/ml/get-started/ml-getting-started.asciidoc, docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc, docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc, docs/en/stack/ml/get-started/ml-gs-next.asciidoc, docs/en/stack/ml/get-started/ml-gs-results.asciidoc, docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/setup.asciidoc
This PR simplifies the structure of the "setup and security" and "getting started with machine learning" sections fo the Machine Learning Guide by removing the use of docbook "parts", without losing the desired levels in the table of contents.
=> [DOCS] Adds chapter, removes part from ML guide

docs/en/glossary/glossary.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1732 and https://github.com/elastic/stack-docs/issues/1725
This PR comments out a link that points to outlier detection-related docs. Due to the ML book reorg, this link would break the docs build after merging https://github.com/elastic/stack-docs/pull/1732. The PR also changes the URL to point to the proper place. After the changes in [1732](https://github.com/elastic/stack-docs/pull/1732) are applied, it's enough to delete the `//` to make the link work.
=> [DOCS] Comments out link to outlier detection in glossary

docs/en/glossary/glossary.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1736 and https://github.com/elastic/stack-docs/issues/1725
This PR comments out links that point to classification and regression-related docs. Due to the ML book reorg, these links would break the docs build after merging https://github.com/elastic/stack-docs/pull/1736.
=> [DOCS] Removes classification and regression links from Glossary

docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc, docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
This PR fixes links to https://www.elastic.co/guide/en/kibana/master/add-sample-data.html, which are now redirected to the [Quickstart](https://www.elastic.co/guide/en/kibana/master/get-started.html)
=> [DOCS] Fixes links to Kibana sample data documentation

docs/en/stack/ml/anomaly-detection/job-tips.asciidoc, docs/en/stack/ml/redirects.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1747
This PR addresses the following broken links:
> 18:39:00 INFO:build_docs:  Kibana [master]: src/core/public/doc_links/doc_links_service.ts contains broken links to:
18:39:00 INFO:build_docs:   - en/machine-learning/master/create-jobs.html#bucket-span
18:39:00 INFO:build_docs:   - en/machine-learning/master/create-jobs.html#cardinality
18:39:00 INFO:build_docs:   - en/machine-learning/master/create-jobs.html#detectors
18:39:00 INFO:build_docs:   - en/machine-learning/master/create-jobs.html#job-tips
18:39:00 INFO:build_docs:   - en/machine-learning/master/create-jobs.html#model-memory-limits
=> [DOCS] Add redirects for broken links

docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
- [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)
=> [7.x] [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)

docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
Backports the following commits to 7.14:
- [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)
=> [7.14] [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)

docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
- [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)
=> [7.13] [DOCS] Clarifies behavior of datafeeds with or without an end time (#1754)

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Changes the wording of the note about connection timeouts in `Trained models` docs.
[Trained models](https://stack-docs_1762.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-trained-models.html)
=> [DOCS] Fine-tunes note in trained models docs

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
- [DOCS] Fine-tunes note in trained models docs. (#1762)
=> [7.x] [DOCS] Fine-tunes note in trained models docs. (#1762)

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Backports the following commits to 7.14:
- [DOCS] Fine-tunes note in trained models docs. (#1762)
=> [7.14] [DOCS] Fine-tunes note in trained models docs. (#1762)

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
- [DOCS] Fine-tunes note in trained models docs. (#1762)
=> [7.13] [DOCS] Fine-tunes note in trained models docs. (#1762)

docs/en/install-upgrade/highlights.asciidoc
Related to https://github.com/elastic/kibana/pull/106484
This PR uncomments the 7.14 highlights in the Installation and Upgrade Guide.
=> [DOCS] Uncomment 7.14 highlights

docs/en/install-upgrade/breaking.asciidoc
This PR adds missing sections to the Installation and Upgrade Guide from the Elasticsearch breaking changes (https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html)
=> [DOCS] Add missing breaking change sections

docs/en/glossary/glossary.asciidoc
Related to https://github.com/elastic/kibana/pull/106339
This PR adds the "labs" term to the glossary.
=> [DOCS] Adds labs to glossary

docs/en/glossary/glossary.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1722
=> [DOCS] Move Kibana glossary to stack docs

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Changes:
* Removes 7.14 coming tags. These aren't needed as 7.14 docs are marked as preliminary until release.
* Uncomments the include for 7.14 ES breaking changes.
=> [DOCS] Add ES breaking changes. Remove 7.14 coming tags.

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR removes coming tags from breaking changes and release highlights in the 7.x Installation and Upgrade Guide. I plan to do the same for our 8.x branch.
As @chriscressman recently pointed out, our 7.x and 8.x docs already have a "preliminary docs" advisory until they're released:
These coming tags duplicate that message. Removing them creates an unneeded chore at release.
=> [DOCS] Remove coming tags from breaking changes + release highlights

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR uncomments the 7.14 breaking changes in the Installation and Upgrade Guide.
It must be merged after https://github.com/elastic/kibana/pull/107058
=> [DOCS] Uncomment 7.14 breaking changes

docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
This PR adds a note to the classification/regression sections about a workaround if the DFA model is too large to fit into JVM. Also expands the DFA memory limitation item with this information.
Related issue: https://github.com/elastic/elasticsearch/issues/76093
* [Classification](https://stack-docs_1778.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-classification.html#dfa-classification-supervised)
* [Regression](https://stack-docs_1778.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-regression.html#dfa-regression-supervised)
* [Limitation](https://stack-docs_1778.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html#dfa-dataframe-size-limitations)
=> [DOCS] Adds a note about a workaround if DFA model is too large to fit into JVM

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/dfa-regression.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
This PR backports the changes of the following commit to the 7.x branch:
[DOCS] Adds a note about a workaround if DFA model is too large to fit into JVM #1778
=> [7.x][DOCS] Adds a note about a workaround if DFA model is too large to fit into JVM

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/dfa-regression.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
This PR backports the changes of the following commit to the 7.14 branch:
[DOCS] Adds a note about a workaround if DFA model is too large to fit into JVM #1778
=> [7.14][DOCS] Adds a note about a workaround if DFA model is too large to fit into JVM

docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc, docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc, docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
Related to #74265 and #74257
This PR updates machine learning documentation to make use of the datafeed_config option in the create anomaly detection jobs API and clarifies some details related to stopping datafeeds when jobs close.
* https://stack-docs_1793.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-ad-finding-anomalies.html#closing-ml-jobs
* https://stack-docs_1793.docs-preview.app.elstc.co/guide/en/machine-learning/master/mapping-anomalies.html
* https://stack-docs_1793.docs-preview.app.elstc.co/guide/en/machine-learning/master/geographic-anomalies.html
=> [DOCS] Update datafeed details in ML docs

docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc, docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc, docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc, docs/en/stack/ml/redirects.asciidoc
This PR adds deleted pages for anomaly detection content that has moved in the main branch, so that switching versions from 7.x pages doesn't generate an error.
=> [DOCS] Add deleted pages for reorganized content

docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
This PR refreshes the list of data frame analytics APIs in https://www.elastic.co/guide/en/machine-learning/master/ml-dfanalytics-apis.html to match https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-df-analytics-apis.html
It also sorts the list alphabetically.
=> [DOCS] Refreshes list of data frame analytics APIs

docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Adds documentation for how to avoid elastic/elasticsearch#75377
and how to remediate it if you don't avoid it.
https://stack-docs_1802.docs-preview.app.elstc.co/guide/en/machine-learning/7.x/ml-troubleshooting.html
=> Adding troubleshooting docs for spurious ML job closure issue

docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1802
=> [7.15][DOCS]Adding troubleshooting docs for spurious ML job closure issue (#1802)

docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1802
=> [7.14][DOCS] Adding troubleshooting docs for spurious ML job closure issue (#1802)

docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Relates to https://github.com/elastic/elasticsearch/pull/76987
This PR adds a link to https://www.elastic.co/guide/en/elasticsearch/reference/master/put-trained-model-definition-part.html from the Machine Learning Guide
=> [DOCS] Add link to new trained model API

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
This PR updates the details in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html for jobs that use a rare function, by_field_name, and partition_field_name, such that it aligns with the description in the anomaly detection job wizard.
=> [DOCS] Clarifies rare security job details

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR makes it clearer that data that exists in rolled-up indices cannot be analyzed by anomaly detection jobs.
Related to https://github.com/elastic/ml-team/issues/495#issuecomment-906322444
[Rollup indices are not supported in Kibana](https://stack-docs_1821.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-limitations.html#ml-rollup-limitations)
=> [DOCS] Makes limitation item about rolled up indices clearer

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- [DOCS] Makes limitation item about rolled up indices clearer (#1821)
=> [7.x] [DOCS] Makes limitation item about rolled up indices clearer (#1821)

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Backports the following commits to 7.15:
- [DOCS] Makes limitation item about rolled up indices clearer (#1821)
=> [7.15] [DOCS] Makes limitation item about rolled up indices clearer (#1821)

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Backports the following commits to 7.14:
- [DOCS] Makes limitation item about rolled up indices clearer (#1821)
=> [7.14] [DOCS] Makes limitation item about rolled up indices clearer (#1821)

docs/en/install-upgrade/highlights.asciidoc
This PR makes the 7.15 Elasticsearch release highlights visible in the Installation and Upgrade Guide.
=> [DOCS] Uncomments 7.15 release highlights

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/redirects.asciidoc
=> [DOCS] Fixes tiny typo

docs/en/install-upgrade/breaking.asciidoc
This PR adds the Beats 7.15.0 breaking changes to the Installation and Upgrade Guide.
It must be merged only after https://github.com/elastic/beats/pull/28079 is merged.
=> [DOCS] Add beats breaking changes

docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
This PR slightly modifies the transform config in outlier detection docs and the regression DFA config in regression docs.
* [Outlier detection](https://stack-docs_1840.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-finding-outliers.html#weblogs-outliers)
* [Regression](https://stack-docs_1840.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-regression.html#flightdata-regression-model)
=> Amends transforms and regression API config in docs

docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
This PR slightly modifies the regression DFA config in regression docs.
Related to https://github.com/elastic/stack-docs/pull/1840
* [Regression](https://stack-docs_1841.docs-preview.app.elstc.co/guide/en/machine-learning/7.x/flightdata-regression.html#flightdata-regression-model)
=> Amends regression API config in docs

docs/en/install-upgrade/upgrading-stack.asciidoc
This PR redirects a link in the Installation & Upgrade Guide that points to the old Java HLRC. After the PR is merged, the link points to the new client.
Related to https://github.com/elastic/docs/pull/2229
**DO NOT merge before https://github.com/elastic/docs/pull/2236**
[Upgrading the Elastic Stack](https://stack-docs_1844.docs-preview.app.elstc.co/guide/en/elastic-stack/master/upgrading-elastic-stack.html)
=> Redirects link in Installation & Upgrade

docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc, docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc, docs/en/stack/ml/get-started/ml-getting-started.asciidoc, docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc, docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc, docs/en/stack/ml/get-started/ml-gs-next.asciidoc, docs/en/stack/ml/get-started/ml-gs-results.asciidoc, docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/machine-learning-intro.asciidoc, docs/en/stack/ml/redirects.asciidoc
Moves the "getting started" tutorial under "Anomaly Detection", since it does not cover data frame analytics.  
Moves the introduction from the first page of the tutorial into a new page (aligned with similar "What is...?" pages for [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-intro.html), [Kibana](https://www.elastic.co/guide/en/kibana/current/introduction.html), [Observability](https://www.elastic.co/guide/en/observability/current/observability-introduction.html), etc).
* https://stack-docs_1839.docs-preview.app.elstc.co/guide/en/machine-learning/master/machine-learning-intro.html
* https://stack-docs_1839.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-getting-started.html
=> [DOCS] Add intro; move tutorial

docs/en/getting-started/get-started-docker.asciidoc, docs/en/glossary/glossary.asciidoc, docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/installing-stack.asciidoc, docs/en/install-upgrade/overview.asciidoc, docs/en/install-upgrade/upgrading-stack.asciidoc
- docs: link to new APM book (#1850)
=> [8.0] docs: link to new APM book (#1850)

docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
This PR adds a link to the setup page to places in the docs that mention ML node and/or `xpack.ml.enabled` config details, so the setup page can be the source of truth of this info.
* https://stack-docs_1872.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-ad-finding-anomalies.html#ml-ad-setup
* https://stack-docs_1872.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-classification.html#dfa-classification-environment
* https://stack-docs_1872.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-finding-outliers.html#dfa-outlier-detection-environment
* https://stack-docs_1872.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-regression.html
=> Adds setup page links to sections about ML node setup

docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1872
=> [7.16][DOCS] Adds setup page links to sections about ML node setup (#1872)

docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1872
=> [8.0][DOCS] Adds setup page links to sections about ML node setup (#1872)

docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1872
=> [7.15][DOCS] Adds setup page links to sections about ML node setup (#1872)

docs/en/glossary/glossary.asciidoc
Closes https://github.com/elastic/elasticsearch/issues/80050
Relates to https://github.com/elastic/elasticsearch/issues/79675, https://github.com/elastic/elasticsearch/pull/79081
=> [DOCS] Add 'feature state' definition to glossary

docs/en/getting-started/get-started-stack.asciidoc
Updates the getting started page for the Stack to reflect changes for security ON by default. Also removes old links, updates other links, and fixes some minor issues throughout the page.
Preview link: https://stack-docs_1883.docs-preview.app.elstc.co/guide/en/elastic-stack-get-started/master/get-started-elastic-stack.html
=> [DOCS] Updating Stack getting started for security ON

docs/en/glossary/glossary.asciidoc
This PR defines the term data views in the glossary.
=> [DOCS] Adds data views to glossary

docs/en/glossary/glossary.asciidoc
Tweaks the `index pattern` definition to make it clear that it now applies to the Elasticsearch context, not Kibana.
Relates to https://github.com/elastic/stack-docs/pull/1886.
=> [DOCS] Update index pattern definition

docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
This PR fixes a link to a deleted page in https://www.elastic.co/guide/en/machine-learning/master/ml-dfa-classification.html#ml-inference-class
=> [DOCS] Fix link to ingest pipelines

docs/en/getting-started/get-started-stack.asciidoc
Backports the following commits to 7.16:
- Remove links and references to journalbeat (#1893)
=> [7.16] Remove links and references to journalbeat (#1893)

docs/en/install-upgrade/highlights.asciidoc
This PR removes the comments so that the what's new content can be pulled from the Kibana repo.
=> [DOCS] Adds highlights for Kibana

docs/en/stack/ml/df-analytics/index.asciidoc, docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc, docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc, docs/en/stack/ml/nlp/ml-nlp.asciidoc, docs/en/stack/ml/redirects.asciidoc
This PR adds stubs for the NLP content in the Machine Learning Guide. It must be merged *after* https://github.com/elastic/docs/pull/2306 and https://github.com/elastic/elasticsearch/pull/81347
https://stack-docs_1903.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp.html
=> [DOCS] Adds NLP folders to ML Guide

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
This PR adds the "Extract information" page to the NLP docs.
The page contains the conceptual docs of the following NLP tasks:
* named entity recognition (NER)
* fill-mask
[Extract information](https://stack-docs_1908.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-extract-info.html)
=> Adds Extract information page to NLP docs

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
- Adds Extract information page to NLP docs (#1908)
=> [8.0] Adds Extract information page to NLP docs (#1908)

docs/en/install-upgrade/upgrading-stack.asciidoc
Backports the following commits to 7.16:
- Redirects link in Installation & Upgrade. (#1844)
=> [7.16] Redirects link in Installation & Upgrade. (#1844)

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp.asciidoc
Adds initial instructions for importing and deploying NLP trained models.
https://stack-docs_1905.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-deploy-models.html
=> [DOCS] Draft NLP model deployment

docs/en/install-upgrade/breaking.asciidoc
Activates the include for beats breaking changes in 7.16.
MERGE AFTER https://github.com/elastic/beats/pull/29300.
=> Updates the Beats breaking changes link

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-categorize-text.asciidoc, docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc, docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc, docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
This PR adds the "Classify text" page to the NLP docs.
The page contains the conceptual docs of the following NLP tasks:
* language identification
* text classification
* zero-shot text classification
[Classify text](https://stack-docs_1911.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-categorize-text.html)
EDIT: The section title has been changed from `Categorize text` to `Classify text`.
=> Drafts Classify text page for NLP docs

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc, docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc, docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
- Drafts Classify text page for NLP docs (#1911)
=> [8.0] Drafts Classify text page for NLP docs (#1911)

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc, docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
This PR adds the "Search and compare" page to the NLP docs.
The page contains the conceptual docs for the Text embedding task.
[Search and compare](https://stack-docs_1914.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-search-compare.html)
=> Drafts Search and compare section for NLP docs

docs/en/getting-started/get-started-docker.asciidoc
Introduces a new section for enrolling new nodes on Docker. These changes were included in the Elasticsearch Docker documentation in https://github.com/elastic/elasticsearch/pull/81787.
=> [DOCS] Add section for enrolling new nodes on Docker

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
This PR adds examples to the trained model deployment page. In particular, a sample Eland script and a sample NER inference test. 
This PR must be merged after https://github.com/elastic/docs/pull/2327
=> [DOCS] Adds trained model deployment examples

docs/en/install-upgrade/installing-stack.asciidoc
Azure was missing from the list of Elastic Cloud providers, switched existing test to use the shared attributes, and removed closing line as it is covered in the first line of the section.
=> Use ess-leadin-short shared attr

docs/en/install-upgrade/breaking.asciidoc
Adds some missing headings to the 8.0 Elasticsearch breaking changes.
=> [DOCS] Add 8.0 ES breaking changes for plugins and SQL JDBC

docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
Adds new documentation referencing the new `zxx` special case. 
Relates to: https://github.com/elastic/elasticsearch/pull/82746
https://stack-docs_1944.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-classify-text.html#ml-nlp-lang-ident
=> Update ml-nlp-lang-ident with zxx special case

docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
The anomaly detection content in the Machine Learning guide is currently in a docbook "part", which means there are some limitations to what can go in the "partintro" on the first page. It gained us extra layers in the navigation, however those are no longer required.  Therefore, this PR reverts to a chapter format instead of a part format.
=> Revert anomaly detection part to chapter

docs/en/install-upgrade/breaking.asciidoc
This PR addresses the following broken link in https://github.com/elastic/kibana/pull/123404
> 12:26:47 INFO:build_docs:Bad cross-document links:
12:26:47 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elastic-stack/7.17/kibana-breaking-changes.html contains broken links to:
12:26:47 INFO:build_docs:   - en/kibana/7.17/release-notes-7.16.0.html
It also updates other out-dated references to 7.16 breaking changes.
=> [DOCS] Updates breaking changes in Install Upgrade Guidie

docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1951
=> [8.0][DOCS] Removes APM NodeJS and RUM Javascript modules (#1951)

docs/en/install-upgrade/breaking.asciidoc
This PR must be merged after https://github.com/elastic/kibana/pull/123404, since adds a link in the Installation and Upgrade Guide to the Kibana release notes that are published in that PR.
=> [DOCS] Fix link to Kibana 7.17 release notes

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
This PR updates the https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-apache.html page in the machine learning guide to use tables instead of description lists and links to the appropriate configuration files.
=> [DOCS] Restructure Apache job list as table with links

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1963
https://stack-docs_1965.docs-preview.app.elstc.co/guide/en/machine-learning/8.0/ootb-ml-jobs-apache.html
=> [8.0][DOCS] Restructure Apache job list as table with links (#1963)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1963
=> [8.1][DOCS] Restructure Apache job list as table with links (#1963)

docs/en/install-upgrade/breaking.asciidoc
Removing this while we get the 8.2 migration guide in place in https://github.com/elastic/elasticsearch/pull/83341
=> [DOCS] Comment out ES migration guide

docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
The link from the [Archived settings](https://www.elastic.co/guide/en/elastic-stack/master/upgrading-elasticsearch.html#archived-settings) section of the Stack Upgrade Guide points to the [Elasticsearch Upgrade Guide](https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-upgrade.html). This link should instead point to the child page for [Archived settings](https://www.elastic.co/guide/en/elasticsearch/reference/master/archived-settings.html).
Preview link: https://stack-docs_1986.docs-preview.app.elstc.co/guide/en/elastic-stack/master/upgrading-elasticsearch.html#archived-settings
=> [DOCS] Fix link in Stack Upgrade Guide

docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
=> [8.1] [DOCS] Fix link in Stack Upgrade Guide (#1986)

docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
=> [8.0] [DOCS] Fix link in Stack Upgrade Guide (#1986)

docs/en/glossary/glossary.asciidoc, docs/en/install-upgrade/upgrading-stack-cloud.asciidoc, docs/en/install-upgrade/upgrading-stack.asciidoc
The 8.0 upgrade assistant is only available in 7.17. This updates our docs to link to the 7.17 version of the related Kibana docs page.
=> [DOCS] Link to the 7.17 upgrade assistant docs

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
This PR reorganizes the content in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-auditbeat.html such that it consists of tables instead of description lists and links to the job and datafeed details.
=> [DOCS] Restructure Auditbeat jobs in tables

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
This PR updates the content in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-logs-ui.html to use tables instead of description lists, to link to the appropriate configuration files, and to link to the corresponding pages in the Observability Guide.
=> [DOCS] Restructures log jobs in table

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
This PR updates the content in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-metricbeat.html to use tables instead of description lists and to link to the appropriate configuration files.
=> [DOCS] Restructures Metricbeat jobs in table

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
This PR updates the content in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-metrics-ui.html to use tables instead of description lists and to link to the appropriate configuration files.
=> [DOCS] Restructures Metrics jobs in table

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
This PR updates the content in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-nginx.html to use tables instead of description lists and to link to the appropriate configuration files.
=> [DOCS] Restructures Nginx jobs in table

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2002
=> [8.1][DOCS] Restructures Metricbeat jobs in table (#2002)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
This PR updates the content in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-uptime.html to use tables instead of description lists and to link to the appropriate configuration files.
=> [DOCS] Restructures Uptime jobs in table

docs/en/install-upgrade/breaking.asciidoc
DO NOT MERGE until elastic/logstash#13723 has been merged.
NOTE: Docs CI will fail until then.
=> Activate Logstash breaking changes include 8.0

docs/en/getting-started/get-started-stack.asciidoc
Backports the following commits to 8.1:
- Remove Homebrew instructions from getting started docs (#2021)
=> [8.1] Remove Homebrew instructions from getting started docs (#2021)

docs/en/getting-started/get-started-stack.asciidoc
- Remove Homebrew instructions from getting started docs (#2021)
=> [8.0] Remove Homebrew instructions from getting started docs (#2021)

docs/en/install-upgrade/upgrading-stack.asciidoc
Re-adds an anchor removed by https://github.com/elastic/stack-docs/pull/1970. This will create a broken link when 8.0 is released.
I'll open a separate PR to remove the anchor once I fix any outstanding references.
=> [DOCS] Re-add anchor for stack upgrade order

docs/en/install-upgrade/upgrading-stack.asciidoc
Updates the upgrade guide to clarify BWC for CCS. Based on [the CCS docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations), you can only search back one minor version.  This means a local 8.1 cluster can only search remote 8.0+ clusters.
Relates to https://github.com/elastic/kibana/pull/125138 and https://github.com/elastic/stack-docs/pull/1970
=> [DOCS] Fix CCS cluster compatibility

docs/en/install-upgrade/upgrading-stack.asciidoc
This is an automatic backport to `8.1` of:
- #2028
=> [8.1] Fix CCS cluster compatibility (#2028)

docs/en/install-upgrade/upgrading-stack.asciidoc
This is an automatic backport to `8.0` of:
- #2028
=> [8.0] Fix CCS cluster compatibility (#2028)

docs/en/install-upgrade/upgrading-kibana.asciidoc
Comments out link to {kibana-ref}/_upgrading_multiple_kibana_instances.html#logging-config-changes[configuring logging] to avert broken links.
=> [DOCS] Omit link to logging config changes

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Restructures the content about pre-built machine learning security jobs in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html to use tables instead of description lists and link to the configuration files.
=> [DOCS] Restructures reference for preconfigured security jobs

docs/en/install-upgrade/upgrading-stack.asciidoc
#2024 re-added an anchor to fix some broken links for the 8.0 release. Now that we've updated links using the anchor, we can remove it.
Depends on https://github.com/elastic/cloud-on-k8s/pull/5350
=> [DOCS] Remove anchor from upgrade docs

docs/en/install-upgrade/upgrading-stack.asciidoc
This will backport the following commits from `8.0` to `8.1`:
- [[DOCS] Remove anchor from upgrade docs (#2027)](https://github.com/elastic/stack-docs/pull/2027)
=> [8.1] [DOCS] Remove anchor from upgrade docs (#2027)

docs/en/install-upgrade/upgrading-stack.asciidoc
This will backport the following commits from `8.0` to `main`:
- [[DOCS] Remove anchor from upgrade docs (#2027)](https://github.com/elastic/stack-docs/pull/2027)
=> [main] [DOCS] Remove anchor from upgrade docs (#2027)

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc, docs/en/stack/ml/nlp/ml-nlp-resources.asciidoc
This PR augments the machine learning documentation with a list of NLP model architectures and third party models.
* https://stack-docs_1989.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-model-ref.html
* Link in https://stack-docs_1989.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-deploy-models.html#ml-nlp-select-model
* Link in https://stack-docs_1989.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-overview.html
=> [DOCS] Add list of supported NLP model architectures

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc, docs/en/stack/ml/nlp/ml-nlp-resources.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1989
=> [8.1][DOCS] Add list of supported NLP model architectures (#1989)

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc, docs/en/stack/ml/nlp/ml-nlp-resources.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1989
The MPNet support is 8.1+, however, per https://github.com/elastic/elasticsearch/pull/82234
=> [8.0][DOCS] Add list of supported NLP model architectures (#1989)

docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
Relates to https://github.com/elastic/elasticsearch/pull/84005, which encounters the following build errors:
> 16:06:38 INFO:build_docs:Bad cross-document links:
16:06:38 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/machine-learning/master/ml-api-quickref.html contains broken links to:
16:06:38 INFO:build_docs:   - en/elasticsearch/reference/master/ml-apis.html#ml-api-anomaly-job-endpoint
16:06:38 INFO:build_docs:   - en/elasticsearch/reference/master/ml-apis.html#ml-api-calendar-endpoint
16:06:38 INFO:build_docs:   - en/elasticsearch/reference/master/ml-apis.html#ml-api-datafeed-endpoint
16:06:38 INFO:build_docs:   - en/elasticsearch/reference/master/ml-apis.html#ml-api-filter-endpoint
16:06:38 INFO:build_docs:   - en/elasticsearch/reference/master/ml-apis.html#ml-api-result-endpo …
=> [DOCS] Fix links to ML APIs - part 1

docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2051
=> [8.1][DOCS] Fix links to ML APIs - part 1 (#2051)

docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2051
=> [8.0][DOCS] Fix links to ML APIs - part 1 (#2051)

docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc, docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
Relates to https://github.com/elastic/elasticsearch/pull/84005 and https://github.com/elastic/stack-docs/pull/2050
=> [DOCS] Fix links to ML APIs

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/index.asciidoc
- [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide (#2039)
=> [8.0] [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide (#2039)

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/index.asciidoc
Backports the following commits to 8.1:
- [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide (#2039)
=> [8.1] [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide (#2039)

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/upgrading-elasticsearch.asciidoc, docs/en/install-upgrade/upgrading-kibana.asciidoc, docs/en/install-upgrade/upgrading-stack-cloud.asciidoc, docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc, docs/en/install-upgrade/upgrading-stack.asciidoc
This will backport the following commits from `main` to `8.0`:
- [[DOCS] Update upgrade steps for minor/patch releases (#2057)](https://github.com/elastic/stack-docs/pull/2057)
=> [8.0] [DOCS] Update upgrade steps for minor/patch releases (#2057)

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/upgrading-elasticsearch.asciidoc, docs/en/install-upgrade/upgrading-kibana.asciidoc, docs/en/install-upgrade/upgrading-stack-cloud.asciidoc, docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc, docs/en/install-upgrade/upgrading-stack.asciidoc
This will backport the following commits from `main` to `8.1`:
- [[DOCS] Update upgrade steps for minor/patch releases (#2057)](https://github.com/elastic/stack-docs/pull/2057)
=> [8.1] [DOCS] Update upgrade steps for minor/patch releases (#2057)

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/redirects.asciidoc
Elasticsearch for Hadoop rarely releases breaking changes outside of major releases.
This commit removes the breaking changes page for ES Hadoop from the Elastic Upgrade Guide in 8.1+. It also adds a redirect page that points users back to the ES Hadoop docs.
Redirect page: https://stack-docs_2056.docs-preview.app.elstc.co/guide/en/elastic-stack/master/elasticsearch-hadoop-breaking-changes.html
=> [DOCS] Remove ES Hadoop breaking changes in 8.1+

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/index.asciidoc
Resolves https://github.com/elastic/security-docs/issues/1571.
Previews:
* [Highlights landing page](https://stack-docs_2046.docs-preview.app.elstc.co/guide/en/elastic-stack/master/elastic-stack-highlights.html)
* [Elastic Security highlights](https://stack-docs_2046.docs-preview.app.elstc.co/guide/en/elastic-stack/master/security-highlights.html)
Note: Version # in the previews will be 8.2.0 because that's the current version in main/master; we'll backport to 8.0.0 and 8.1.0.
To complete this PR, these other changes were necessary:
* https://github.com/elastic/security-docs/pull/1575
* https://github.com/elastic/security-docs/pull/1578
=> [DOCS] Add Elastic Security highlights to Installation and Upgrade Guide

docs/en/install-upgrade/highlights.asciidoc
- [DOCS] Add Elastic Security highlights to Installation and Upgrade Guide (#2046)
=> [8.0] [DOCS] Add Elastic Security highlights to Installation and Upgrade Guide (#2046)

docs/en/install-upgrade/highlights.asciidoc
Backports the following commits to 8.1:
- [DOCS] Add Elastic Security highlights to Installation and Upgrade Guide (#2046)
=> [8.1] [DOCS] Add Elastic Security highlights to Installation and Upgrade Guide (#2046)

.mergify.yml, README.md
The security and observability repos use Mergify to automate backports. This PR copies the method used in observability-docs (https://github.com/elastic/observability-docs/blob/main/.mergify.yml), since it uses new, backport-specific labels (backport-x.y), rather than changing/overloading the behaviour of existing labels.
Before we merge this PR, we must create backport labels that meet the conditions, as seen in https://github.com/elastic/observability-docs/labels?q=backport
=> Add mergify configuration file for stack-docs

docs/en/getting-started/get-started-stack.asciidoc
Nothing dramatic - just two typos.
=> fix: minor typos on get-started-stack.asciidoc

docs/en/getting-started/get-started-stack.asciidoc
This PR updates the cURL command to check if ES is running in the getting started guide.
[ES is up and running](https://stack-docs_2085.docs-preview.app.elstc.co/guide/en/elastic-stack-get-started/master/get-started-elastic-stack.html#_make_sure_that_elasticsearch_is_up_and_running)
=> [DOCS] Fixes curl command to check if ES is running

docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
This PR removes the limitation item about space-unaware trained models from DFA limitations. From 8.2, trained models are space-aware, so the limitation does not apply anymore. It also comments out the Kibana limitations section as there is no other limitation under this section. It slightly modifies the intro paragraph, too.
Related to https://github.com/elastic/ml-team/issues/495#issuecomment-1096592588.
[Limitations](https://stack-docs_2101.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html)
=> Removes outdated DFA limitation

docs/en/getting-started/get-started-docker.asciidoc
Update the path where auto generated certificates are stored in the docker instructions
=> [DOCS] Update certificate path in Docker installation

docs/en/getting-started/get-started-docker.asciidoc, docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR applies the following changes on the anomaly detection limitations page:
* adds a limitation about deprecation messages for datafeeds that use Painless with deprecated syntax,
* removes a limitation regarding POST data API usage.
[Deprecation warnings for Painless scripts](https://stack-docs_2125.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-limitations.html#ml-limitations-painless-script)
=> Adds Painless-related deprecation warnings limitation and removes POST data API limitation

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR adds the proper Eland install command to the NLP model import instructions.
[Import trained model and vocabulary](https://stack-docs_2130.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-deploy-models.html)
=> [DOCS] Adds Eland install instructions to NLP model import

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Related to https://github.com/elastic/eland/pull/461 and https://github.com/elastic/eland/pull/462
This PR adds an `Authentication methods` section to the NLP import guide that lists the available methods with examples.
[Authentication methods](https://stack-docs_2132.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-deploy-models.html#authentication)
=> [DOCS] Adds authentication methods to NLP import guide

docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc, docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR makes documentation changes related to https://github.com/elastic/elasticsearch/pull/86361
In particular, it updates the ML Guide to use the new URL for the infer API and it updates the API example output in the "Deploy trained models" page.
- https://stack-docs_2123.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-apis.html
- https://stack-docs_2123.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-deploy-models.html#ml-nlp-test-inference
=> [DOCS] Deprecate deployment infer API

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc, docs/en/stack/ml/redirects.asciidoc
Relates to https://github.com/elastic/kibana/pull/131166
This PR updates the job reference information in https://www.elastic.co/guide/en/security/master/prebuilt-ml-jobs.html and https://www.elastic.co/guide/en/security/master/prebuilt-ml-jobs.html
In particular, it refreshes the list of anomaly detection jobs in the "Security:Linux" and "Security:Windows" sections and removes the discontinued "Security:Auditbeat", "Security:Auditbeat authentication", "Security:Winlogbeat", and "Security:Winlogbeat authentication" sections. It also removes the discontinued "Auditbeat host processes" section from [Auditbeat anomaly detection configurations](https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-auditbeat.html)
This PR must be merged after …
=> [DOCS] Updates list of security and auditbeat anomaly detection configurations

docs/en/getting-started/get-started-docker.asciidoc
This will clarify that users should use the `elastic` user to log into Kibana after the installation.
cc @lockewritesdocs
=> Clarify login flow

docs/en/install-upgrade/breaking.asciidoc
This PR must be merged after https://github.com/elastic/elasticsearch/pull/87294
It updates the breaking changes page in the Installation and Upgrade Guide to use the appropriate files for Elasticsearch and omits links to 8.3 release information that doesn't exist yet.
=> [DOCS] Clean up 8.3 breaking change links

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
This PR improves readability on the NLP model reference page by adding link text to URLs. It also orders the list items into alphabetical order.
[NLP model reference](https://stack-docs_2154.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-model-ref.html)
=> Improves readability on NLP model reference page

docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc, docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc, docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc, docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
This PR fixes grammatical errors/places where shared attributes are not used in NLP documentation. These fixes are based on the [linting tool](https://github.com/elastic/docs-lint) results.
=> Fixes grammar based on linting tool results in NLP docs

docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc, docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc, docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
In the NLP conceptual documentation, the examples used pseudo-JSON snippets for the sake of simplicity. This PR changes the examples to use the actual JSON objects and structure to provide more accurate example snippets even if the structure is a bit more complex.
* [Classify text](https://stack-docs_2172.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-classify-text.html)
* [Extract info](https://stack-docs_2172.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-extract-info.html)
* [Search and compare](https://stack-docs_2172.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-search-compare.html)
=> [DOCS] Changes NLP examples to use proper JSON structure and objects

docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
This PR adds the links of the NLP example blog posts to a section called `Further reading` at the end of the NLP inference page.
[NLP inference - Further reading]()
=> [DOCS] Adds links to the inference example that point to the NLP blog posts

docs/en/stack/ml/anomaly-detection/ml-ad-resources.asciidoc
This PR updates https://www.elastic.co/guide/en/machine-learning/master/ml-ad-resources.html to add links to its nested pages.
=> [DOCS] Add missing links in anomaly detection resources

docs/en/glossary/glossary.asciidoc
This PR updates the [Glossary](https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html) definition for `time series data` and adds a new definition for `time series data stream`. Also, a tiny update to `data stream` to add a link.
Rel: https://github.com/elastic/elasticsearch/pull/87897
=> [DOCS] Add/Update time series data and related terms

docs/en/stack/ml/nlp/ml-nlp.asciidoc
This PR adds an admonition to the NLP landing page about the fact that the feature is in technical preview.
[NLP landing](https://stack-docs_2198.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp.html)
=> [DOCS] Adds technical preview admonition to NLP landing page

docs/en/stack/ml/setup.asciidoc
ML anomaly detection jobs cause certain field values from the
source indices to be copied into the results indices when an
anomaly is detected.
This PR calls out the security implications of that. If an ML
anomaly detection job is being run against sensitive data then
it is important to carefully consider who has access to ML
anomaly detection results.
=> [DOCS] Add notes about security for ML anomaly detection job results

docs/en/install-upgrade/breaking.asciidoc
This content has a dependency on https://github.com/elastic/beats/pull/32768.
MERGE AFTER https://github.com/elastic/beats/pull/32768 is merged _and_ successfully backported to 8.4.
=> Update link for Beats breaking changes include

docs/en/install-upgrade/breaking.asciidoc
Fixes #2216 
Preview:
Notes
The breaking changes page in the Install & Upgrade Guide is built using [includes of tagged regions](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/), so I added tags to the relevant region in the Release Notes page in the Security Docs repo (see change in in https://github.com/elastic/security-docs/pull/1828).
This PR's doc build will fail until the 8.4 release notes page is available on the public docsite. This means that, in order for this PR to successfully build, BOTH of the following requirements need to be met:
The 8.4 Security release notes PR merged into main and backported to the 8.4 branch.
The 8.4 Security release notes page will need to be built/published on the 8.4 branch and available on the [public …
=> [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide for 8.4

docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc, docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/88994 and https://github.com/elastic/elasticsearch/pull/88439.
This PR adds conceptual docs about the text similarity task to the NLP conceptual documentation.
[Text similarity](https://stack-docs_2223.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-search-compare.html#ml-nlp-text-similarity)
=> Adds text similarity task to the NLP docs

docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
In 8.5, the maximum number of classes for classification analysis is increased from 30 to 100. This PR adjusts the documentation to represent this change.
[Classification](https://stack-docs_2222.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-classification.html)
=> Updates classification conceptual docs

docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
This PR:
* improves the readability of the documentation on influencers by using a bulleted list of requirements
* put the requirements for the API users under a collapsible section
* suggests using the Advanced job wizard,
* adds further details about the topic.
[Influencers](https://stack-docs_2221.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-ad-run-jobs.html#ml-ad-influencers)
=> [DOCS] Improves influencer documentation

.mergify.yml
This PR update the mergify configuration file to use the backport-8.5 label and the 8.5 branch.
=> Add 8.5 to mergify

docs/en/glossary/glossary.asciidoc
Relates to https://github.com/elastic/docs/issues/2518
=> [DOCS] Fix hard-coded link in glossary

docs/en/install-upgrade/breaking.asciidoc
Fixes https://github.com/elastic/stack-docs/issues/2242.
Preview:
* [Elastic Installation and Upgrade Guide | Breaking changes]
* [Elastic Security breaking changes]
* Version # in the previews will be 8.6.0 because that's the current version in main/master; we'll backport to 8.5.0.
* The breaking changes page in the Install & Upgrade Guide is built using [includes of tagged regions](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/), so I added tags to the relevant region in the Release Notes page in the Security Docs repo (see change in in https://github.com/elastic/security-docs/pull/2519).
* This PR's doc build will fail until the `8.5` release notes page is available on the public docsite. This means that, in order for this PR to successfully build, …
=> [DOCS] Add Elastic Security breaking changes to Installation and Upgrade Guide for 8.5

docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
This PR sets the model memory limit to 50 MB in the regression API example to avoid running out of memory when users try the API example out.
[Creating a regression model]() --available soon
=> [DOCS] Modifies regression API example

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Relates to https://github.com/elastic/elasticsearch/pull/90728
This PR adds a link to the new [update trained model deployment API](https://www.elastic.co/guide/en/elasticsearch/reference/master/update-trained-model-deployment.html) in the [Deploy NLP trained model steps](https://www.elastic.co/guide/en/machine-learning/master/ml-nlp-deploy-models.html#ml-nlp-deploy-model).
When https://github.com/elastic/kibana/issues/144550 is complete and this action can be performed within Kibana, that should be mentioned here as well.
NOTE: The API mentions "assignment_state" whereas in this PR I'm using "allocation status", since that's what I see in the docs for the get trained model stats output. If it's not correct, we need to update for consistency.
=> [DOCS] Add update API link to deployment NLP steps

docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
This PR adds a link of the semantic search endpoint to the quick reference list of the trained model APIs.
[API quick reference](https://stack-docs_2270.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-apis.html)
=> [DOCS] Adds semantic search endpoint to the list of trained model APIs

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
This PR updates the "Autoscaling..." section of the anomaly detection at scale piece by adding the CPU-based scaling criterion to the text.
[Anomaly detection at scale – 1. Consider autoscaling...](https://stack-docs_2275.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-detection-scale.html#node-sizing)
=> [DOCS] Updates AD at scale piece with autoscaling detail

docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/92086.
This PR removes a reference to the semantic search API docs from the NLP API page.
=> [8.6][DOCS] Removes reference to semantic search docs

docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
In line 19 of the [shut down node](https://github.com/elastic/elasticsearch/blame/master/docs/reference/upgrade/shut-down-node.asciidoc#L19) doc, it suggests `kill $(cat pid)` to stop a daemon process. Removed as not everyone is running Elasticsearch using a daemon. 
Fixes #88558
=> [DOCS] Stop a single node

docs/en/glossary/terms/allocator-affinity.asciidoc, docs/en/glossary/terms/allocator-tag.asciidoc, docs/en/glossary/terms/console.asciidoc, docs/en/glossary/terms/data-center.asciidoc, docs/en/glossary/terms/deployment-template.asciidoc, docs/en/glossary/terms/deployment.asciidoc, docs/en/glossary/terms/ece.asciidoc, docs/en/glossary/terms/eck.asciidoc, docs/en/glossary/terms/elastic-stack.asciidoc, docs/en/glossary/terms/elasticsearch-service.asciidoc, docs/en/glossary/terms/hardware-profile.asciidoc, docs/en/glossary/terms/host-runner.asciidoc, docs/en/glossary/terms/instance-configuration.asciidoc, docs/en/glossary/terms/instance-type.asciidoc, docs/en/glossary/terms/instance.asciidoc, docs/en/glossary/terms/kibana.asciidoc, docs/en/glossary/terms/no-op.asciidoc, docs/en/glossary/terms/solution.asciidoc, docs/en/glossary/terms/vcpu.asciidoc
This adds terms from the Cloud glossaries that were missing from our newly assembled and very nice [shared glossary](https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html). 
Rel: https://github.com/elastic/platform-docs-team/issues/49
=> Add Cloud entries to shared glossary

docs/en/install-upgrade/breaking.asciidoc
This PR fixes the re-use of Elasticsearch breaking changes in https://www.elastic.co/guide/en/elastic-stack/8.6/elasticsearch-breaking-changes.html and removes a "coming" tag.
=> [DOCS] Fix 8.6 breaking changes

docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc, docs/en/stack/ml/get-started/ml-gs-results.asciidoc
This PR: 
* adds an admonition to the tutorial that informs the users that their results might differ from the results seen in the screenshots
* adds an extra step to the instructions to make sure that the anomaly in the analysis is visible in the SMV.
[Create sample jobs...](https://stack-docs_2301.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-getting-started.html#sample-data-jobs) -- admonition block
[Single metric job results](https://stack-docs_2301.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-getting-started.html#ml-gs-results-smv) -- new step in the instructions
=> [DOCS] Amends the instructions in the anomaly detection tutorial

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Related issue: https://github.com/elastic/ml-team/issues/894
This PR highlights recommended models for every task type on the supported models' page. 
[Compatible third party NLP models](https://stack-docs_2310.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-model-ref.html)
=> Marks recommended models in the third party models list

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Related issue: https://github.com/elastic/machine-learning-qa/issues/1449
This PR adds a new item to the list of anomaly detection limitations. Frozen tier data is not supported for anomaly detection.
[AD limitations]()
=> Adds limitation item about anomaly detection jobs and frozen tier data

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
This PR changes links on the Apache and Nginx pages that point to the GH repo where the spec files are stored. Until 8.1, it was the Kibana repo (version controlled). From 8.2, it's the Integrations repo (not version controlled). For this reason, the links from 8.2 to 8.6 are broken. This PR fixes this problem. 7.17 is also affected as it's an active (updated) branch.
=> Fixes GH links on Apache and Nginx OOTB job pages

docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc, docs/en/stack/ml/anomaly-detection/anomaly-how-tos.asciidoc, docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/ml-ad-run-jobs.asciidoc, docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc, docs/en/stack/ml/get-started/ml-gs-results.asciidoc, docs/en/stack/ml/redirects.asciidoc
Related to https://github.com/elastic/ml-team/issues/867.
This PR removes the pages about categorization and population jobs under the How-to section of the book. A higher-level description of these jobs is available on the page about the different types of anomaly detection jobs. This PR is part of the anomaly detection documentation reorganization effort.
=> Removes pages from the how-to section

docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
Related to: https://github.com/elastic/elasticsearch/pull/93500
Removes a reference to the semantic search endpoint from the NLP API page.
=> Removes reference to semantic search endpoint from docs

docs/en/stack/ml/anomaly-detection/ml-ad-job-types.asciidoc
This PR adds the new, geo job type to the page that lists the different anomaly detection job types.
[Geo data](https://stack-docs_2328.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-anomaly-detection-job-types.html#geo-jobs)
=> [DOCS] Adds description of the geo anomaly job to the job types page

docs/en/stack/ml/anomaly-detection/job-tips.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc, docs/en/stack/ml/get-started/ml-getting-started.asciidoc, docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc, docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
This PR adds a TIP about the available field stats in the anomaly detection and the data frame analytics wizards.
The PR also removes a link that is not relevant anymore and fixes some line breaks.
=> [DOCS] Adds info about available field statistics in AD and DFA wizards

docs/en/stack/ml/index-custom-title-page.html
This PR fixes a typo in one of the link text strings on the ML landing page.
=> [DOCS] Fixes typo in link text

docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
This PR updates the NLP text embedding example to use the semantic search capabilities released with 8.7. 
I've also updated a few instances of "vector search" with "semantic search", as that will make it easier for folks to find this example.
=> Update NLP example to use semantic search

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
As of 8.4.0, Elasticsearch supports any IOB tagged NER entities.
=> Update ML docs for NER support

docs/en/install-upgrade/breaking.asciidoc
Fixes #2351 
* The breaking changes page in the Install & Upgrade Guide is built using [includes of tagged regions](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/), refer for example to https://github.com/elastic/security-docs/pull/2519.
* This PR's doc build will fail until the `8.7` release notes page is available on the public docsite. This means that, in order for this PR to successfully build, **_BOTH_** of the following requirements need to be met:
- The `8.7` Security release notes PR merged into main and backported to the `8.7` branch.
- The `8.7` Security release notes page will need to be built/published on the `8.7` branch and available on the [public docsite](https://www.elastic.co/guide/en/security/current/index.html).
=> Update security breaking changes link from 8.6 to 8.7

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR adds an empty section to the `Deploy trained models` page that will explain how to deploy trained models in an air-gaped environment. It also adds a section ID, so the section will have its own anchor (`#ml-nlp-deploy-model-air-gaped`) on the page.
Content will be added soon.
=> [DOCS] Adds section title and anchor for model deployment in air-gaped env

docs/en/stack/ml/nlp/ml-nlp.asciidoc
This PR removes a `beta` tag from the NLP landing page.
=> Removes beta tag from NLP landing page

docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
This PR fixes a link on the trained model page of the DFA docs that points to the latest Eland documentation.
=> Fixes a broken link that points to the latest Eland docs

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
The last letter of the model name is capitalized (Elastic Learned Sparse EncodeR). This PR applies the correct grammar on the model name.
=> [DOCS] Changes the title of the ELSER page

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
The ELSER page intro was about how ELSER works and what technology it is based on. While it is important information, the first paragraph of the page must describe what the model can do for the users. For this reason, this PR changes the perspective of the first paragraph and describes how ELSER can help users. The technical background will be explained in a more detailed way in a blog post anyway and the intro will contain a link to that post, so anyone can learn more about it.
* [ELSER](https://stack-docs_2393.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html)
=> [DOCS] Adjusts intro para for ELSER

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Adding link from NLP ELSER deployment page to Enterprise Search ELSER deployment instructions.
=> Link from NLP ELSER doc to Ent Search ELSER deployment section

docs/en/stack/ml/nlp/index.asciidoc, docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc, docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc, docs/en/stack/ml/nlp/ml-nlp.asciidoc
This PR:
* creates a limitation section under the NLP chapter,
* adds a limitation item about ELSER v1 and maximum token number,
* adds a link to the ELSER page to the NLP landing page.
[NLP limitations](https://stack-docs_2396.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-limitations.html)
=> [DOCS] Adds limitation item about ELSER v1

docs/en/stack/ml/anomaly-detection/ml-ad-explain.asciidoc, docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc, docs/en/stack/ml/anomaly-detection/ml-ad-job-types.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc, docs/en/stack/ml/df-analytics/ml-how-dfa-works.asciidoc, docs/en/stack/ml/get-started/ml-getting-started.asciidoc, docs/en/stack/ml/machine-learning-intro.asciidoc, docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc, docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc, docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc, docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc, docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc, docs/en/stack/ml/nlp/ml-nlp.asciidoc
This PR updates source files that contain `:description:` attributes to use `:frontmatter-description:` instead. It also adds the other frontmatter necessary for migration to the new docs system.
=> [DOCS] Add frontmatter for migration

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR adds the instructions for installing models by using Docker to the model deployment page.
[Deploy NLP model](https://stack-docs_2418.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-import-model.html)
=> [DOCS] Adds Docker install option to model deployment

docs/en/install-upgrade/breaking.asciidoc
Fixes #2416 
* The breaking changes page in the Install & Upgrade Guide is built using [includes of tagged regions](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/), refer for example to https://github.com/elastic/security-docs/pull/2519.
* This PR's doc build will fail until the `8.8` release notes page is available on the public docsite. This means that, in order for this PR to successfully build, both of the following requirements need to be met:
- The `8.8` Security release notes PR merged into main and backported to the `8.8` branch.
- The `8.8` Security release notes page will need to be built/published on the `8.8` branch and available on the [public docsite](https://www.elastic.co/guide/en/security/current/index.html).
=> Update security breaking changes link from 8.7 to 8.8

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR adds the following pieces of content to the ELSER conceptual docs:
* Hardware benchmarks section,
* information on the used data sets,
* table of the data sets,
* table of the benchmarking results.
[Hardware benchmarks](https://stack-docs_2421.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html#elser-hw-benchamrks)
=> [DOCS] Adds hardware benchmarks to ELSER docs

docs/en/stack/ml/index-custom-title-page.html
This PR adds a new item under the NLP section of the ML landing page that leads to the ELSER conceptual documentation.
[ML landing page](https://stack-docs_2423.docs-preview.app.elstc.co/guide/en/machine-learning/master/index.html)
=> [DOCS] Amends ML landing page to include ELSER

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR changes the section title `Inference request queues` to `Request queues and search priority`.
[Request queue and search priority](https://stack-docs_2425.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-deploy-model.html#infer-request-queues)
=> [DOCS] Makes section title more descriptive on NLP model deployment page

docs/en/install-upgrade/breaking.asciidoc
Fixes https://github.com/elastic/stack-docs/issues/2427.
* The breaking changes page in the Install & Upgrade Guide is built using [includes of tagged regions](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/), refer for example to https://github.com/elastic/security-docs/pull/2519.
* This PR's doc build will fail until the `8.8.1` release notes page is available on the public docsite. This means that, in order for this PR to successfully build, both of the following requirements need to be met:
- The `8.8.1` Security release notes PR merged into main and backported to the `8.8` branch.
- The `8.8.1` Security release notes page will need to be built/published on the `8.8` branch and available on the [public …
=> [DOCS] Update security breaking changes link from 8.8.0 to 8.8.1

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR adds more conceptual information to the ELSER introduction about how the model works.
[ELSER](https://stack-docs_2433.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html)
=> [DOCS] Adds more conceptual info to ELSER

docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc, docs/en/stack/ml/nlp/ml-nlp-ner-example.asciidoc, docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
This PR adds the `size` parameter to the reindex API calls in the NLP examples.
=> Adds size parameter to the reindex commands in the NLP examples

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR adds a note to the ELSER conceptual docs that contains a recommendation for the minimum size of the ML node.
=> [DOCS] Adds note about the recommended node size for ELSER

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc, docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
This PR:
* adjusts the note on the minimum ML node size on the ELSER page to include reference to ESS and autoscaling,
* adds the same note to the third-party models page.
* [ELSER requirements](https://stack-docs_2447.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html#elser-req)
* [Third-party models](https://stack-docs_2447.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-model-ref.html#ml-nlp-model-ref)
=> [DOCS] Adjusts note on minimum node size for ELSER and third-party models

docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
The other JSON snippets have the correct code for pasting into the kibana console, so this section should as well.
=> [DOCS] Added missing quotations for "docs" post request

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Related to https://github.com/elastic/stack-docs/pull/2451.
This PR deletes two models from the question-answering model section as both models are sentence similarity models.
=> [DOCS] Removes sentence similarity models from QA list

docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
This PR amends the vector search end-to-end example to contain a reference about `embedding_size`.
[Add the text embedding model to an inference ingest pipeline]()
=> [DOCS] Amends text with embedding_size info

docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
This PR temporarily changes the deep link to `knn-search.html#semantic-search` in the ES book into `knn-search.html`. The `semantic-search` ID is moved as part of https://github.com/elastic/elasticsearch/pull/97715 and that PR is failing a cross-book link CI check because of this cross-book link.
I'll restore the deep link after  https://github.com/elastic/elasticsearch/pull/97715 has been merged.
=> Temporarily remove deep link to knn semantic search

docs/en/install-upgrade/air-gapped-install.asciidoc
Follow up to https://github.com/elastic/stack-docs/pull/2458. Adds air-gapped install instructions for Elasticsearch and Machine Learning.
=> Add air-gapped install instructions for Elasticsearch and Machine Learning

docs/en/install-upgrade/breaking.asciidoc
Uncomments the links to the Kibana 8.9 breaking changes.
Relates to https://github.com/elastic/kibana/pull/162444
=> Link to Kibana 8.9 breaking changes

docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
Restores the deep link to the semantic search section in the kNN docs, that was temporarily removed in https://github.com/elastic/stack-docs/pull/2474
=> Restore deep link to knn semantic search

docs/en/install-upgrade/breaking.asciidoc
This will backport the following commits from `8.8` to `8.7`:
- [[Install/Upgrade] Fix Beats 8.8 breaking changes (#2502)](https://github.com/elastic/stack-docs/pull/2502)
=> [8.7] [Install/Upgrade] Fix Beats 8.8 breaking changes (#2502)

docs/en/install-upgrade/breaking.asciidoc
This will backport the following commits from `8.8` to `8.6`:
- [[Install/Upgrade] Fix Beats 8.8 breaking changes (#2502)](https://github.com/elastic/stack-docs/pull/2502)
=> [8.6] [Install/Upgrade] Fix Beats 8.8 breaking changes (#2502)

docs/en/install-upgrade/air-gapped-install.asciidoc
Adds a link to the [Install ECE offline](https://www.elastic.co/guide/en/cloud-enterprise/3.6/ece-install-offline.html) instructions to the air-gapped install page.
Closes: https://github.com/elastic/stack-docs/issues/2509
=> Add ECE to air-gapped install page

docs/en/install-upgrade/air-gapped-install.asciidoc
This will backport the following commits from `main` to `8.9`:
- [Add ECE to air-gapped install page (#2510)](https://github.com/elastic/stack-docs/pull/2510)
=> [8.9] Add ECE to air-gapped install page (#2510)

docs/en/install-upgrade/breaking.asciidoc
The current link points to a specific version of the release notes rather than the release notes landing page. Point to the landing page instead.
This makes it easier to bump the Elastic docs version, since it removes a dependency on a specific Enterprise Search page existing first.
It's also consistent with the other release notes links on this page.
Rel: https://github.com/elastic/stack-docs/pull/2495
=> Fix link to Enterprise Search release notes

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
This PR changes the node size requirements on the third-party model page, so it doesn't refer to ELSER.
[Model reference page](https://stack-docs_2517.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-model-ref.html)
=> [DOCS] Fixes NLP size requirement on model reference page

docs/en/install-upgrade/air-gapped-install.asciidoc
In air-gapped environments Fleet Server, Elastic Agent, and the stack need to be upgraded in a set order. This adds a link in the [Elastic agent section](https://www.elastic.co/guide/en/elastic-stack/current/air-gapped-install.html#air-gapped-elastic-agent) of the air-gapped install docs to the [specific air-gapped requirements](https://www.elastic.co/guide/en/fleet/current/air-gapped.html) in the Fleet & Agent Guide.
=> Agent upgrade order

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR changes the reference to the `rank_feature` field type to `rank_features` as that's the correct field type that needs to be used for ELSER. Other references to the field type – for example in the end-to-end example – are correct.
Closes https://github.com/elastic/platform-docs-team/issues/176
=> [DOCS] Fixes field type in ELSER conceptual

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This will backport the following commits from `main` to `8.10`:
- [[DOCS] Fixes field type in ELSER conceptual. (#2527)](https://github.com/elastic/stack-docs/pull/2527)
=> [8.10] [DOCS] Fixes field type in ELSER conceptual. (#2527)

docs/en/install-upgrade/installing-stack.asciidoc
This will backport the following commits from `main` to `8.10`:
- [[DOCS] Add default ports for Elastic Stack components (#2531)](https://github.com/elastic/stack-docs/pull/2531)
=> [8.10] [DOCS] Add default ports for Elastic Stack components (#2531)

docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
Changes `{ref}//start-trained-model-deployment.html` to `{ref}/start-trained-model-deployment.html`
=> [DOCS] Removes // from start trained model deployment link

docs/en/siem/overview.asciidoc
Changes `{filebeat-ref}//filebeat-module-cisco.html` to `{filebeat-ref}/filebeat-module-cisco.html`
=> [DOCS] Removes // from filebeat link

docs/en/stack/ml/index-custom-title-page.html
**Problem:** In https://github.com/elastic/docs/pull/2752, we updated the URL prefix (`welcome-to-elastic`) and name for the "Welcome to Elastic Docs" docs. However, we still have some stray links that use the old `/welcome-to-elastic` URL prefix
**Solution:** Update an outdated link.
=> [ML] Fix `welcome-to-elastic` link

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Text similarity must use a cross encoder model which has caused some confusion
For https://github.com/elastic/elasticsearch/issues/99211
=> Add list of text similarity models to compatible NLP models

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
The Enterprise Search ELSER doc will be removed in the near future. Remove the link now to unblock link checking in PRs.
=> [DOCS] Remove link to doc that will be removed

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR adds a subsection to the ELSER v2 section about how to upgrade from v1 to v2. It also adds a link that points to the tutorial which shows how to create an index pipeline and how to reindex using that pipeline.
[ESLER v2]()
=> [DOCS] Highlights how to switch to ELSER v2 from v1

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Related to https://github.com/elastic/stack-docs/issues/2562.
This PR:
* removes the Job and Datafeed columns from the tables under `Security: Elastic integrations` section. Reason: Updates to integration packages are frequent and hard to maintain the URLs.
* adds a link to the job and datafeed config files after each table.
Scope: `8.9` and above.
* [Domain Generation Algorithm Detection](https://github.com/elastic/integrations/blob/main/packages/dga/kibana/ml_module/dga-ml.json#L21)
* [Living off the Land Detection](https://github.com/elastic/integrations/blob/main/packages/problemchild/kibana/ml_module/problemchild-ml.json#L27)
* [Data Exfiltration Detection](https://github.com/elastic/integrations/blob/main/packages/ded/kibana/ml_module/ded-ml.json#L42)
* [Lateral Movement …
=> Fixes URLs in OOTB security jobs and updates job IDs

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR adds a separate section to the ELSER conceptual docs about tokens and emphasizes that tokens are not synonyms and shouldn't be interpreted as synonyms.
[Tokens - not synonyms](https://stack-docs_2568.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html#elser-tokens)
=> [DOCS] Adds section about tokens to ELSER conceptual

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR adds an `IMPORTANT` block to the trained model deployment section that explains that users will experience downtime in the service of their trained model if the model has only one allocation deployed. 
[Deploy the model to your cluster](https://stack-docs_2567.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-deploy-model.html#ml-nlp-deploy-model)
=> [DOCS] Documents that models with one allocation might have downtime

docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
The first point in the list (upgrade the master-ineligible nodes) is
redundant and sort of contradicts the second one (upgrade the data nodes
tier-by-tier). This commit drops it.
The second point had some redundant sentences in a somewhat awkward
order. This commit cleans that up.
There's no mention of nodes that are neither data nodes nor
master-eligible nodes. In fact it doesn't really matter when these nodes
are upgraded, but this commit specifies to upgrade them before the
master-eligible nodes for the sake of completeness.
Finally, there were some over-long lines so this commit reflows the
source.
=> Improve rolling upgrade order docs

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR adds an `IMPORTANT` note about the fact that ELSER V2 is generally available while ELSER V1 is in (and will be in) technical preview.
[ELSER](https://stack-docs_2581.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html)
=> Adds note on ELSER V2 is GA and V1 is in preview

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
The Search Experiences team created a notebook for upgrading to v2. We could add a link here. :)
=> Add link to ELSER v2 upgrade notebook

docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
In 8.11 the `dense vector` field type has been simplified and some of the settings now have sensible default values:
* `"index": true` is implicit,
* `similarity` defaults to `cosine`.
This PR adjusts the dense vector mapping example in the text embedding NLP example to reflect the changes mentioned above.
* [Text embedding example](https://stack-docs_2593.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-text-emb-vector-search-example.html#ex-text-emb-ingest)
=> Updates the dense vector mappings in text embedding NLP example

docs/en/stack/ml/index-custom-title-page.html, docs/en/stack/ml/nlp/ml-nlp-examples.asciidoc, docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
This PR:
* changes the link of the "Search my data" title on the landing page to point to Search Labs,
* adds a link to the *APIs and developer docs* section on the landing page that points to the Search Labs,
* adds a link to the *Analyze natural language data* section on the landing page that points to Search Labs tutorials,
* adds a link to the NLP examples section that points to the multilingual semantic search notebook,
* adds a link to the overview page that points to the ML research section of the Search Labs.
=> Adds Search Lab links to the ML book

docs/en/install-upgrade/installing-stack.asciidoc
When reviewing our new landing page design, I noticed that Elastic Agent is completely missing from this list. 
I'm not sure why we are hard coding the product names, but decided to leave this as-is in case there is a reason.
@kilfoyle I hope I am not overstepping, but opening a PR was faster than creating an issue. :-)
=> Add Elastic Agent to stack installation instructions

docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
In https://github.com/elastic/stack-docs/pull/1929, the language identification example was added to the NLPinference pipeline page which made it harder to find a working example of the task. This PR puts the example back to the language identification page.
=> [DOCS] Puts lang ident example back

.github/workflows/docs-preview-links.yml
Relates to https://github.com/elastic/docs/pull/2848
Since this repo is used to generate multiple books, I set the `preview-path` to the top-level landing page instead of a particular book.
It seems that this change will need to be backported all the way to 8.4.
=> Edit github workflow for documentation previews

docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
This PR adds legal blurb to the end of the E5 model conceptual documentation page.
[Terms of use](https://stack-docs_2622.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-e5.html#terms-of-use-e5)
=> [DOCS] Adds E5 terms of use to docs

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR adds a note to the ELSER docs that ELSER is an English language model, so if the user would like to perform semantic search on non-English documents, use E5 instead.
[ELSER](https://stack-docs_2624.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html)
=> Adds reference to E5 model in ELSER docs

docs/en/install-upgrade/breaking.asciidoc
This reverts commit d16f81b58322845ec61476569c00caa98f4debb0.
=> [8.2] Revert "docs: temp comment out include (#2631)"

docs/en/install-upgrade/breaking.asciidoc
This reverts commit 2291f0671e7710be594ed177989f58cb71a41673.
=> [8.0] Revert "docs: temp comment out include (#2634)"

docs/en/install-upgrade/breaking.asciidoc
This reverts commit 4a3226d0d5af7709bc9b25eb6149ed2e5db3e4e3.
=> [7.17] Revert "docs: temp comment out include (#2635)"

docs/en/install-upgrade/breaking.asciidoc
This reverts commit 413a91f502c4d6fda5c5f841d86e72f3fb039de6.
=> [8.8] Revert "docs: temp comment out include (#2626)"

docs/en/install-upgrade/breaking.asciidoc
This reverts commit aaf84afc2ae14a619c6a2c50fe6c0c1817c83486.
=> [8.7] Revert "docs: temp comment out include (#2627)"

docs/en/install-upgrade/breaking.asciidoc
This reverts commit 66f0fbf096469d4547ba270d6765c43ff56af23e.
=> [8.6] Revert "docs: temp comment out include (#2626)"

docs/en/install-upgrade/breaking.asciidoc
This reverts commit ba72bddef3684a3d7e1451d78de51680d6a2b6d6.
=> [8.5] Revert "docs: temp comment out include (#2629)"

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR updates the commands on the `Deploy trained models` page based on the latest Eland repo [README](https://github.com/elastic/eland#docker).
=> Updates model deployment commands using Eland and Docker

docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
=> Renames Terms of Use section to Disclaimer in E5 docs

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR fills some gaps identified in the ELSER air-gapped install procedure documentation.
[ELSER](https://stack-docs_2655.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html)
=> [DOCS] Completes air-gapped ELSER install procedure

docs/en/install-upgrade/air-gapped-install.asciidoc
Related to https://github.com/elastic/kibana/pull/175551
This is a small edit in the EMS section to link to the full document and explain better the three options available to users regarding the product in air-gapped environments.
cc. @nreese
=> Update the EMS section in the air-gapped documentation

docs/en/stack/ml/index-custom-title-page.html, docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
Related issue: https://github.com/elastic/stack-docs/issues/2665
This PR adds air-gapped installation instructions to the E5 model page.
It also references the E5 conceptual docs page on the ML custom landing page.
[E5- air-gapped install](https://stack-docs_bk_2666.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-e5.html#air-gapped-install-e5)
[ML landing page](https://stack-docs_bk_2666.docs-preview.app.elstc.co/guide/en/machine-learning/master/index.html)
=> [DOCS] Adds air-gapped install instructions to E5 docs

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
Related issue: https://github.com/elastic/elasticsearch/issues/105878
This PR adds a limitation item to anomaly detection limitations about the fact that scripted metric aggregations are not supported in datafeeds.
[Anomaly detection limitations](https://stack-docs_bk_2669.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-limitations.html)
=> [DOCS] Adds limitation about scripted metric aggregations in datafeeds

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR fixes a typo (missing word) in a sentence in the deploy NLP models page.
=> [DOCS] Adds missing word to sentence in deploy NLP models docs

docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Related issue: https://github.com/elastic/search-docs-team/issues/83
This PR expands the NLP overview section with the _NLP in the Elastic stack_ subsection. This text explains the different options the users have for using NLP:
* NLP models as a service through the Inference API,
* NLP models uploaded and deployed in the cluster,
* store embeddings in an ES vector database.
[NLP in the Elastic stack](https://stack-docs_bk_2679.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-overview.html#nlp-elastic-stack)
=> Adds section about the different options to use NLP in the stack

docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
As of 8.13, Elasticsearch is supported on Bouncy Castle's BC-FIPS release for JDK17 
Relates: https://github.com/elastic/elasticsearch/pull/105041
=> Remove FIPS warning as of ES 8.13

docs/en/install-upgrade/installing-stack-demo-secure.asciidoc, docs/en/install-upgrade/installing-stack-demo-self.asciidoc
Just a tiny update to add "what's next" links to the on-prem install tutorials.
=> Add 'what's next' links to install guide

docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
This PR updates the legal disclaimer on the E5 model documentation page. The source of the updated text is the [HuggingFace page of the model](https://huggingface.co/elastic/multilingual-e5-small-optimized#disclaimer).
=> Updates legal disclaimer for E5

docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
This will backport the following commits from `main` to `8.14`:
- [Updates legal disclaimer for E5 (#2687)](https://github.com/elastic/stack-docs/pull/2687)
=> [8.14] Updates legal disclaimer for E5 (#2687)

docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
This PR adds the inference API reference docs pages to the ML NLP API page for better discoverability.
=> Adds inference API links to the NLP APIs page

docs/en/stack/ml/setup.asciidoc
As title states.
[Kibana security](https://stack-docs_bk_2696.docs-preview.app.elstc.co/guide/en/machine-learning/master/setup.html#kib-security)
=> Adds important callout about granting ML:all feature privilege to the setup page

docs/en/stack/ml/setup.asciidoc
This PR amends the text of the IMPORTANT admonition block about ML Kibana feature privileges on the ML setup page.
[Kibana security](https://stack-docs_bk_2699.docs-preview.app.elstc.co/guide/en/machine-learning/master/setup.html#kib-security)
=> Adjust important admonition in Kibana security section of ML setup page

docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc, docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
This PR removes an item from the NLP limitations sections that refer to the E5 model. The limitation is not applicable anymore starting from 8.12.
=> Removes E5 limitation that no longer applicable

docs/en/stack/ml/anomaly-detection/anomaly-how-tos.asciidoc
=> Fixes typo in link text on AD how-to main page

docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
Currently, ELSER deployments don't autoscale. This PR adds an item to the NLP limitations section about it.
[ELSER deployments don't autoscale](https://stack-docs_bk_2719.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-limitations.html#ml-nlp-elser-autoscale)
=> Documents ELSER autoscale limitation

docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
We maybe should do more, such as explain that `linux-x86-64` is indeed the version optimized for "Intel® silicon".
=> Fix links to E5 optimized version

docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
This will backport the following commits from `8.12` to `8.14`:
- [Fixed typo (#2678)](https://github.com/elastic/stack-docs/pull/2678)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [8.14] Fixed typo (#2678)

docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
This will backport the following commits from `8.12` to `8.13`:
- [Fixed typo (#2678)](https://github.com/elastic/stack-docs/pull/2678)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [8.13] Fixed typo (#2678)

docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
This will backport the following commits from `8.12` to `main`:
- [Fixed typo (#2678)](https://github.com/elastic/stack-docs/pull/2678)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [main] Fixed typo (#2678)

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
It is possible to deploy ELSER multiple times by using different deployment IDs. The recommended behavior is to have different deployments with different purposes. This PR adds an `important` callout to the ELSER page to highlight these pieces of information.
=> Adds important callout about the possibility of multiple ELSER deployment

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc, docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc, docs/en/stack/ml/nlp/ml-nlp-shared.asciidoc
This PR describes adaptive allocations in the `ml-nlp-shared.asciidoc` file. The feature description is then single-sourced from there in the ELSER, E5, and deploy trained model conceptual docs.
* [ELSER](https://stack-docs_bk_2763.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html#elser-adaptive-allocations)
* [E5](https://stack-docs_bk_2763.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-e5.html#e5-adaptive-allocations)
* [Deploy trained models](https://stack-docs_bk_2763.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-deploy-model.html#nlp-model-adaptive-allocations)
=> Adds adaptive allocations feature description to conceptual docs

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc, docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc, docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc, docs/en/stack/ml/nlp/ml-nlp-shared.asciidoc
Reverts elastic/stack-docs#2764
=> [8.15] Removes adaptive allocations feature description from conceptual docs

docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc, docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR overhauls the ELSER and E5 conceptual pages:
* indicates that the recommended and easiest way to download and deploy the models is using inference endpoints,
* introduces the procedure of creating an inference endpoint in the `Download and deploy` section,
* makes the alternative download and deploy methods less prominent by putting them into collapsible sections that are closed by default,
* propagates the semantic_text workflow for semantic search.
* [ELSER](https://stack-docs_bk_2765.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html)
* [E5](https://stack-docs_bk_2765.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-e5.html)
=> Makes inference endpoint the primary way to download and deploy ELSER and E5

docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
This PR forwardports the changes of the following commit to `main`: 
Update ml-nlp-e5.asciidoc #2769
=> Update ml-nlp-e5.asciidoc (#2769)

docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR updates the supported NLP task types on the `Import the trained model and vocabulary` page.
[Import the trained model and vocabulary](https://stack-docs_bk_2775.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-import-model.html#ml-nlp-import-script)
=> Updates the list of supported NLP task types

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Related to https://github.com/elastic/search-docs-team/issues/174
The `Metrics` app has been renamed to `Infrastructure` app. This PR updates the link text on the Metrics OOTB jobs page pointing to the Infrastructure app's docs to represent this change. It does not change the `metrics job` terminology as it remained unchanged. The Infrastructure documentation on the O11y side uses it, too.
=> Updates link text on Metrics configuration page

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR adds a new section to the ELSER conceptual page that recommends cleaning the input text before generating embeddings to achieve the best results.
[ELSER - Pre-cleaning input text](https://stack-docs_bk_2796.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html#pre-cleaning)
=> [DOCS] Adds pre-cleaning recommendation to ELSER docs

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Related to https://github.com/elastic/ml-team/issues/1239
This PR adds `DeBERTa` to the list of supported architectures on the Compatible third-party NLP models page.
=> Updates supported architectures list with DeBERTa

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR removes a anomaly detection limitation item about frozen indices that no longer applies from docs.
=> [DOCS] Removes frozen indices limitation item from anomaly detection docs

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR backports the changes of the following commits to the `8.3` branch: 
=> [8.3][DOCS] Removes frozen indices limitation item from anomaly detection docs

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR backports the changes of the following commits to the `8.0` branch: 
=> [8.0][DOCS] Removes frozen indices limitation item from anomaly detection docs

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR backports the changes of the following commits to the `8.1` branch: 
=> [8.1][DOCS] Removes frozen indices limitation item from anomaly detection docs

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR backports the changes of the following commits to the `8.2` branch: 
=> [8.2][DOCS] Removes frozen indices limitation item from anomaly detection docs

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR backports the changes of the following commits to the `8.4` branch: 
=> [8.4][DOCS] Removes frozen indices limitation item from anomaly detection docs

docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR backports the changes of the following commits to the `8.5` branch: 
=> [8.5][DOCS] Removes frozen indices limitation item from anomaly detection docs

.mergify.yml
Adds the ability to use `backport-main` to backport to `main`.
Useful when contributors use `edit` links in the public documentation.
=> Add the ability to backport to `main`

docs/en/stack/ml/anomaly-detection/ml-ad-run-jobs.asciidoc, docs/en/stack/ml/anomaly-detection/ml-detect-categories.asciidoc, docs/en/stack/ml/anomaly-detection/ml-jobs-from-visuals.asciidoc, docs/en/stack/ml/anomaly-detection/ml-population-analysis.asciidoc, docs/en/stack/ml/anomaly-detection/ml-revert-model-snapshot.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc, docs/en/stack/ml/get-started/ml-gs-results.asciidoc, docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc, docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc, docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc, docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc, docs/en/stack/ml/nlp/ml-nlp-ner-example.asciidoc, docs/en/stack/ml/setup.asciidoc
This PR updates app and page references to align with the new style guide guidelines, ensuring consistency across both the classic and solution views to help users locate pages regardless of their chosen view. Additionally, the update removes interactive checkboxes, replacing them with bullet points.
https://github.com/elastic/search-docs-team/issues/205
=> Updates phrasing when referring to pages

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR updates the ELSER conceptual documentation to replace the deprecated `elser` service with the `elasticsearch` service in the deployment example. The `PUT` inference API call now specifies the `elasticsearch` service along with the `model_id` required for deployment.
https://github.com/elastic/search-docs-team/issues/216
=> Updates ELSER documentation to use 'elasticsearch' service

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR fixes a typo on the [ELSER – Elastic Learned Sparse EncodeR](https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-elser.html) page.
https://github.com/elastic/stack-docs/issues/2869
=> Fixes typo on the "ELSER – Elastic Learned Sparse EncodeR" page

docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
forward backport of https://github.com/elastic/stack-docs/pull/2877
=> [ML] Add ML limitation for ingesting large documents

docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
On the ELSER page, there are two broken links pointing to the same blog post. This PR fixes both links.
https://github.com/elastic/stack-docs/issues/2885
=> [DOCS] [ML] Fixes broken links in ELSER documentation

.github/CODEOWNERS
To make sure the [Elastic Docs Terminology](https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html) and [Elastic in Writing: Writing style guide](https://brand.elastic.co/302f66895/p/194a3b-writing-style-guide) are consistent, adding @demisperazza as codeowner to docs/en/glossary/terms/.
=> Adds Demi as codeowner to glossary terms

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
With the change in https://github.com/elastic/eland/pull/740 Eland now supports uploading 3rd party sparse embedding models (other than ELSER). This PR adds some models to the list of known compatible models.
The Eland command to install one of these models must use the text_expansion task type
```
eland_import_hub_model \
--url 'http://localhost:9200' \
-u elastic-admin -p elastic-password \
--hub-model-id 'hotchpotch/japanese-splade-base-v1' \
--task-type text_expansion 
```
=> Add sparse embedding models to list of compatible models

docs/en/stack/ml/nlp/ml-nlp-elastic-rerank.asciidoc
This PR changes a URL that points to the Elastic Rerank intro blog post. The blog post URL has changed, so this PR updates the link on the page.
=> Changes blog URL on Rerank page

docs/en/stack/ml/anomaly-detection/functions/ml-count-functions.asciidoc, docs/en/stack/ml/anomaly-detection/functions/ml-functions.asciidoc, docs/en/stack/ml/anomaly-detection/functions/ml-geo-functions.asciidoc, docs/en/stack/ml/anomaly-detection/functions/ml-info-functions.asciidoc, docs/en/stack/ml/anomaly-detection/functions/ml-metric-functions.asciidoc, docs/en/stack/ml/anomaly-detection/functions/ml-rare-functions.asciidoc, docs/en/stack/ml/anomaly-detection/functions/ml-sum-functions.asciidoc, docs/en/stack/ml/anomaly-detection/functions/ml-time-functions.asciidoc, docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This is one of a sequence of PRs necessary to move the machine learning function reference pages out of an appendix in preparation for migration. The first step is to change the way the source files are referenced in the Machine learning guide.
The next PR will make the appropriate changes (removal of the appendix and exclude clauses) from the source files in the elasticsearch repo.
Then then final PR will remove the redundant copies from the stack-docs repo.
This PR also moves the supplied configurations out of the appendix as well so they can be migrated.
=> [DOCS] Move reference pages out of appendix for migration

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
This PR updates the documentation with details about the new Security: Host module introduced to the [prebuilt ML jobs in 8.18.0](https://github.com/elastic/kibana/tree/main/x-pack/platform/plugins/shared/ml/server/models/data_recognizer/modules/security_host/ml). Note that this doc change is for the 8.18 release.
- https://github.com/elastic/security-team/issues/10414
=> Add details for the new `Security: Host` module to OOTB ML jobs doc

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
This PR backports the following changes to the `8.x` branch: Add BGE reranker model to list of recommended text similarity models #2824
=> [8.x] Add BGE reranker model to list of recommended (#2824)

docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
This PR backports the following changes to the `8.17` branch: Add BGE reranker model to list of recommended text similarity models #2824
=> [8.17] Add BGE reranker model to list of recommended (#2824)

.github/workflows/comment-on-asciidoc-changes.yml
I accidentally removed the github action from main in https://github.com/elastic/stack-docs/pull/2944 instead of targetting the 9.0 branch, so this PR re-adds it to the main branch. Sigh.
=> [DOCS] Re-add AsciiDoc freeze warning (#2910)

docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/serverless-changelog.asciidoc
This PR drafts a copy of the Elasticsearch Serverless changelog in the Installation and upgrade guide.
It is dependent on https://github.com/elastic/stack-docs/pull/2943 and affected by https://github.com/elastic/stack-docs/pull/2944
=> Add serverless changelog

docs/en/install-upgrade/serverless-changelog.asciidoc
Removes 206313 since the gap feature hasn't been released in Serverless yet.
=> Removes 206313 from the Feb 3, 2025 Serverless changelog

docs/en/install-upgrade/upgrading-stack.asciidoc
We don't support (and will actively block) upgrades to
chronologically-older versions. This commit adds a note in the docs
about this.
=> Add upgrade note about release date constraint

docs/en/install-upgrade/upgrading-stack.asciidoc
"Backports" https://github.com/elastic/stack-docs/pull/2948 to 8.18 because mergify wasn't configured to backport from any branches other than `main`
=> [Backport][8.18] Add upgrade note about release date constraint (#2948)

.mergify.yml
This PR aims to ensure that PRs merged in the 9.0 branch can also be automatically backported, not just those that start in the main branch.
If this doesn't achieve that goal, we might need to remove the `base` clause entirely per https://github.com/elastic/observability-docs/pull/4109
=> Add 8.18 rule and change base in mergify configuration

.mergify.yml
This PR aims to ensure that PRs merged in the 8.18 branch can also be automatically backported, not just those that start in the main branch.
=> Change base in mergify configuration

docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/release-notes/release-notes-security.asciidoc, docs/en/install-upgrade/release-notes/release-notes.asciidoc
This PR adds an empty page for the Security 9.0.0-beta1 release notes.
=> Adds release notes placeholders for Security 9.0.0-beta1

docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/upgrade-deployment-cluster.asciidoc, docs/en/install-upgrade/upgrade-on-ece.asciidoc, docs/en/install-upgrade/upgrade-on-eck.asciidoc, docs/en/install-upgrade/upgrade-orchestrator.asciidoc, docs/en/install-upgrade/upgrading-elasticsearch.asciidoc, docs/en/install-upgrade/upgrading-kibana.asciidoc, docs/en/install-upgrade/upgrading-stack-cloud.asciidoc, docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc, docs/en/install-upgrade/upgrading-stack.asciidoc
Addresses https://github.com/elastic/docs-projects/issues/431 and publishes `9.0.beta1` upgrade docs. 
Preview [here](https://stack-docs_bk_2961.docs-preview.app.elstc.co/guide/en/elastic-stack/9.0/upgrading-elastic-stack.html).
=> [DOCS] Upgrade 9.0 beta1

docs/en/install-upgrade/serverless-changelog.asciidoc
This PR adds the latest release notes for Elastic Cloud Serverless.
=> Add serverless changelog for Feb 17

docs/en/install-upgrade/release-notes/release-notes-security.asciidoc
Adds content from https://github.com/elastic/security-docs/pull/6520 to the new temp release notes file for Security. Also resolves https://github.com/elastic/security-docs/issues/6400.
Preview: [9.0.0-beta release notes](https://stack-docs_bk_2960.docs-preview.app.elstc.co/guide/en/elastic-stack/9.0/release-notes-security-9.0.0-beta1.html)
=> 9.0.0 beta Security release notes

docs/en/install-upgrade/release-notes/release-notes-kibana.asciidoc, docs/en/install-upgrade/release-notes/release-notes-security.asciidoc
This PR removes the "coming" admonitions from the Kibana and Logstash release notes. It also removes some extra section levels from the security release notes.
=> Remove coming tags, fix security release note levels

docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/release-notes/release-notes-beats.asciidoc, docs/en/install-upgrade/release-notes/release-notes.asciidoc
This PR copies the Beats 9.0.0 beta1 release notes from https://github.com/elastic/beats/pull/42721 into the Installation and Upgrade Guide. It also fixes the order of the release notes in the navigation to match alphabetical sort order.
=> Add Beats release notes

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/release-notes/release-notes-elasticsearch.asciidoc, docs/en/install-upgrade/release-notes/release-notes-fleet-agent.asciidoc, docs/en/install-upgrade/release-notes/release-notes-kibana.asciidoc, docs/en/install-upgrade/release-notes/release-notes-logstash.asciidoc, docs/en/install-upgrade/release-notes/release-notes-security.asciidoc, docs/en/install-upgrade/release-notes/release-notes.asciidoc
This PR copies the Elasticsearch release notes and breaking changes from https://github.com/elastic/elasticsearch/pull/122884 into the Installation and Upgrade Guide.
It also fixes links from the breaking changes page to the appropriate release note pages and removes "beta1" from the URLs so that these pages can be used for rc1 and rc2 release details too.
=> Add Elasticsearch release notes

docs/en/install-upgrade/serverless-changelog.asciidoc
This PR adds the Serverless release notes for February 24, 2025.
=> [Docs] 02-24-25 Serverless changelog

docs/en/install-upgrade/upgrading-stack.asciidoc
Contributes to https://github.com/elastic/docs-projects/issues/454 by adding the Anomaly detection results migration subsection to the Prepare to upgrade section in the upgrade guide.
Preview: [Upgrade to Elastic 9.0.0-beta1 | Anomaly detection results migration](https://stack-docs_bk_2979.docs-preview.app.elstc.co/guide/en/elastic-stack/9.0/upgrading-elastic-stack.html#anomaly-detection-results-migration)
=> Anomaly detection results migration

docs/en/install-upgrade/upgrading-stack.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/123866
Added a note that all obsolete model snapshot warnings have to be resolved before the result indices can be marked as read-only.
=> [9.0] Updates ML migration guide

docs/en/install-upgrade/serverless-changelog.asciidoc
Adds the Serverless changelog for March 3
=> Adds March 3 Serverless changelog

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Related PR: https://github.com/elastic/stack-docs/pull/2987
This PR updates the steps to add & configure dashboard for the ML`Security: Host` OOTB module.
- https://github.com/elastic/security-team/issues/10414
This PR targets the 8.18 branch. The changes for 9.0.0 will be addressed in a separate PR because of the doc migration. Tracking issue: https://github.com/elastic/search-docs-team/issues/269
=> [8.18][DOCS] Update steps to configure dashboard for Security: Host module

docs/en/install-upgrade/upgrading-stack.asciidoc
This PR adds the 'Transform destination indices migration' section to the [Upgrade to Elastic 9.0.0-beta1](https://www.elastic.co/guide/en/elastic-stack/9.0/upgrading-elastic-stack.html) documentation.
Related issue: https://github.com/elastic/search-docs-team/issues/253
=> Adds transforms to Upgrade guide

docs/en/install-upgrade/serverless-changelog.asciidoc
Adds the Serverless changelog for March 10
=> Adds Serverless changelog for March 10

docs/en/install-upgrade/serverless-changelog.asciidoc
This PR adds the Serverless changelog for March 17, 2025.
=> Serverless changelog for March 17

docs/en/install-upgrade/upgrade-on-ece.asciidoc, docs/en/install-upgrade/upgrade-on-eck.asciidoc, docs/en/install-upgrade/upgrading-stack-cloud.asciidoc, docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc, docs/en/install-upgrade/upgrading-stack.asciidoc
Contributes to https://github.com/elastic/docs-projects/issues/452.
=> Updates for 9.0.0-rc1 release

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Contributes to https://github.com/elastic/docs-content/issues/755 by fixing broken prebuilt job links on the Security anomaly detection configurations page. 
Preview:
[Appendix H: Security anomaly detection configurations](https://stack-docs_bk_2999.docs-preview.app.elstc.co/guide/en/machine-learning/8.x/ootb-ml-jobs-siem.html)
=> Fix links on Security anomaly detection config page

docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/release-notes/release-notes-fleet-agent-rc1.asciidoc, docs/en/install-upgrade/release-notes/release-notes-fleet-agent.asciidoc
This adds the 9.0 RC1 Fleet & Elastic Agent Release Notes:
* No Fleet contents in [Kibana Release Notes PR](https://github.com/elastic/stack-docs/pull/2986)
* Fleet Server contents from [BC4 changelog ](https://github.com/elastic/fleet-server/tree/713533919d13e7614bbb606b80ae21ccd9c7c980/changelog/fragments)
* Elastic Agent contents from [BC4 changelog](https://github.com/elastic/elastic-agent/tree/2a3710cfef0b0b5f60b2fbddff15692d087247b1/changelog/fragments)
See [preview page](https://stack-docs_bk_2975.docs-preview.app.elstc.co/guide/en/elastic-stack/9.0/release-notes-fleet-agent-9.0.0.html#release-notes-fleet-agent-9.0.0-rc1)
Closes: https://github.com/elastic/ingest-docs/issues/1703
=> Add Fleet & Agent 9.0-RC1 Release Notes

docs/en/install-upgrade/release-notes/release-notes-elasticsearch-beta1.asciidoc, docs/en/install-upgrade/release-notes/release-notes-elasticsearch-rc1.asciidoc
This PR copies the RC1 release notes from https://github.com/elastic/elasticsearch/pull/125444 and edits some links to make them work in the context of the Installation and Upgrade Guide.
=> [DOCS] Add Elasticsearch 9.0 rc1 release notes

docs/en/install-upgrade/release-notes/release-notes-beats-rc1.asciidoc, docs/en/install-upgrade/release-notes/release-notes-beats.asciidoc
This PR copies the contents of the Beats 9.0 rc1 release notes from https://github.com/elastic/beats/pull/43419 into the appropriate section of the Installation and Upgrade Guide, which is temporarily used as a stop-gap for 9.0 release notes.
=> [DOCS] Beats 9.0 rc1 release notes

docs/en/install-upgrade/release-notes/release-notes-fleet-agent-rc1.asciidoc, docs/en/install-upgrade/release-notes/release-notes-logstash-rc1.asciidoc, docs/en/install-upgrade/release-notes/release-notes-security-rc1.asciidoc
This PR removes the "coming" tags from the 9.0 RC1 release notes
=> [DOCS] Remove 9.0 coming tags

docs/en/install-upgrade/upgrading-stack.asciidoc
Related to https://github.com/elastic/search-docs-team/issues/268
This PR updates the PUT settings request in the AD upgrade guide to set the `auto_expand_replicas` parameter to `false`.
=> [9.0] Amends the anomaly detection upgrade instructions

docs/en/install-upgrade/serverless-changelog.asciidoc
This PR adds the Serverless changelog for March 17, 2025. Modeled on https://github.com/elastic/stack-docs/pull/2995. Instructions here: https://elasticco.atlassian.net/wiki/spaces/DOC/pages/61604062/Release+Notes#ReleaseNotes-Serverless
=> Creates serverless changepg for March 24, 2025

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc, docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
Related issue: https://github.com/elastic/search-docs-team/issues/272
=> Fixes OOTB configuration links

docs/en/install-upgrade/upgrading-stack.asciidoc
Call out specifically to look for cluster stability, performance, and
snapshot repository bugs.
=> Expand guidance on testing an upgrade

docs/en/install-upgrade/upgrading-stack.asciidoc
Call out specifically to look for cluster stability, performance, and
snapshot repository bugs.
Co-authored-by: Liam Thompson <32779855+leemthompo@users.noreply.github.com>
=> Expand guidance on testing an upgrade (#3009)

docs/en/install-upgrade/upgrading-stack.asciidoc
This PR removes redundant sentences from the Transforms destination indices section.
=> Fixes redundancy in the Transforms migration section

docs/en/install-upgrade/serverless-changelog.asciidoc
Adds the Serverless changelog for this week. Will add the Markdown version in a separate PR.
Preview [here](https://stack-docs_bk_3019.docs-preview.app.elstc.co/guide/en/elastic-stack/9.0/serverless-changelog.html).
=> [Docs] Add Serverless changelog for 04/14/2025

docs/en/install-upgrade/installing-stack-demo-self.asciidoc
Adding an Important clarification. The enrollment script fails without proper error handling if the second node is not able to access the first node. the elasticsearch.yml ends up modified and the enrollment script is unable to be reran without undoing all the changes. Reminder added to ensure network access is available before proceeding.
second. the tail command is incorrect unless the cluster.name is also elasticsearch-demo. this value defaults to cluster.name
=> Update installing-stack-demo-self.asciidoc to mitigate error-handling issue. update variable on tail command
