- x-pack/docs/en/index.asciidoc
This PR updates the 6.x branch to use the appropriate shared versions file.
> [DOCS] Updated versions file to 6.4

- x-pack/docs/en/monitoring/production.asciidoc
This PR removes broken links to content about installing X-Pack.
> [DOCS] Removes broken links

- docs/upgrading-stack.asciidoc
This PR removes references to upgrading X-Pack, updates some related URLs, and adds missing attributes.
> [DOCS] Removes out-dated X-Pack content

- x-pack/docs/en/gs-index.asciidoc
- x-pack/docs/en/index.asciidoc
- x-pack/docs/en/monitoring/production.asciidoc
- x-pack/docs/en/xpack-troubleshooting.asciidoc
Related to https://github.com/elastic/kibana/pull/19516
> [DOCS] Fixes references to kibana x-pack directory

- docs/en/stack/index.asciidoc
Moves getting started to the correct location in the TOC.
> [Docs] Move getting started topic

- docs/installing-stack.asciidoc
Cherrypicks #65 into 6.3 branch
> [Docs] Backport to 6.3: Fix broken link

- docs/index.asciidoc
- docs/installing-stack.asciidoc
- docs/upgrading-stack.asciidoc
This PR depends on https://github.com/elastic/apm-server/pull/1125 to be merged first.
@dedemorton can you please review how I added APM-Server to the general installation and upgrade docs.
> [DOCS] Add APM Server.

- docs/en/stack/security/authentication/ldap-realm.asciidoc
Replaces "If fact" with "In fact".
> Fix typo in LDAP realm docs

- docs/upgrading-stack.asciidoc
Fixes https://github.com/elastic/stack-docs/issues/93
> [DOCS] Adds security note to upgrade instructions

- docs/en/stack/ml/rules.asciidoc
This PR adds a link between the rules overview and the configuration examples.
> [DOCS] Link custom rule pages

- docs/en/stack/security/troubleshooting.asciidoc
Fixes typo per https://github.com/elastic/stack-docs/issues/116
> [DOCS] Fixes filename error

- docs/en/infraops/installation.asciidoc
- docs/en/infraops/overview.asciidoc
Backports #150 to the 6.5 branch.
> Backport to 6.5: Add changes from review

- docs/en/infraops/installation.asciidoc
- docs/en/infraops/overview.asciidoc
Backports #150 to the 6.x branch.
> Backport to 6.x: Add changes from review

- .backportrc.json
This PR adds a configuration file for use by the backport tool: https://github.com/sqren/backport
> Adds configuration file for backport tool

- docs/en/getting-started/get-started-stack.asciidoc
Cherrypicks #162 into 6.5 branch.
> [6.5] [Docs] Add Journalbeat and Functionbeat to stack getting started (#162)

- docs/en/getting-started/index.asciidoc
- docs/en/stack/index.asciidoc
Related to https://github.com/elastic/docs/pull/514
This PR updates the 6.x branch to use new version information.
> [DOCS] Updates the version to 6.7.0

- docs/en/glossary/glossary.asciidoc
- docs/en/stack/license.asciidoc
- docs/en/stack/ml/getting-started-data.asciidoc
- docs/en/stack/ml/getting-started.asciidoc
- docs/upgrading-stack.asciidoc
This PR updates some occurrences of the {xpack}, {security}, and {xpackml} attributes in the stack-docs repo.
> [DOCS] Cleans up some X-Pack terms

- docs/en/stack/security/authorization/built-in-roles.asciidoc
Changed doc as per #37761
It should close this issue [#37761](https://github.com/elastic/elasticsearch/issues/37761)
> Changed doc as per #37761

- docs/en/infraops/installation.asciidoc
Merge pull request #210 from simianhacker/fixes-156
> [7.x] Update Infrastructure UI documentation with metric definitions

- docs/en/infraops/installation.asciidoc
Merge pull request #210 from simianhacker/fixes-156
> [7.0] Update Infrastructure UI documentation with metric definitions

- docs/en/infraops/installation.asciidoc
> [6.7] Update Infrastructure UI documentation with metric definitions

- docs/en/infraops/infra-ui-intro.asciidoc
- docs/en/infraops/installation.asciidoc
- docs/en/infraops/logs-ui-intro.asciidoc
Cherry-picks #181 to 6.6 branch
> [6.6] Add links to Kibana docs (#181)

- docs/en/infraops/infra-ui-intro.asciidoc
- docs/en/infraops/installation.asciidoc
- docs/en/infraops/logs-ui-intro.asciidoc
Cherry-picks #181 to 6.7 branch
> [6.7] Add links to Kibana docs (#181)

- docs/en/install-upgrade/breaking.asciidoc
Related to https://github.com/elastic/stack-docs/pull/197 and https://github.com/elastic/kibana/pull/30155
This PR starts including the tagged region from the kibana repo.
> [DOCS] Adds notable breaking changes from Kibana

- docs/en/getting-started/get-started-docker.asciidoc
- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/installing-stack.asciidoc
- docs/en/install-upgrade/overview.asciidoc
- docs/en/install-upgrade/upgrading-stack.asciidoc
- docs/en/stack/security/authentication/built-in-users.asciidoc
~~**DO NOT MERGE:** Blocked by elastic/docs#716~~
This muddies the water a bit, but I think it's the best solution for elastic/apm-server#1993. Whaddya think @lcawl?
> Update APM links to point to 7.0

- docs/en/glossary/glossary.asciidoc
Add Elastic Common Schema (ECS) to the glossary
> Add ecs to terminology list

- docs/en/infraops/installation.asciidoc
* Documenting known workarounds
* add 6.6 specific instructions
> [Backport][7.x][Infra UI] Add documentation for known workarounds (#253)

- docs/en/infraops/installation.asciidoc
* Documenting known workarounds
* add 6.6 specific instructions
> [Backport][7.0][Infra UI] Add documentation for known workarounds (#253)

- docs/en/infraops/installation.asciidoc
* Documenting known workarounds
* add 6.6 specific instructions
> [Backport][6.7][Infra UI] Add documentation for known workarounds (#253)

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/index.asciidoc
Related to elastic/docs#750
Dependent on elastic/beats#11439
This PR looks for tagged regions ("notable-breaking-changes") in https://www.elastic.co/guide/en/beats/libbeat/master/breaking-changes.html which are re-used in https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-breaking-changes.html
> [DOCS] Adds notable Beats breaking changes

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/267
Depends on https://github.com/elastic/apm-server/pull/2078
> Adds APM breaking changes to Install Upgrade Guide (#267)

- docs/en/install-upgrade/highlights.asciidoc
Backports https://github.com/elastic/stack-docs/pull/273
Depends on https://github.com/elastic/beats/pull/11708
> [7.0] Adds Beats highlights to Install Upgrade Guide

- docs/en/install-upgrade/upgrading-stack.asciidoc
Added some more context/motivation for upgrading.
> [DOCS] Added upgrade intro

- docs/en/getting-started/get-started-stack.asciidoc
> [7.0] Backport: Add linux examples (#198)

- docs/en/getting-started/get-started-stack.asciidoc
Cherry-picks #229 into 7.0 branch.
> [7.0] Backport: Link to infrastructure monitoring docs from the stack getting started

- docs/en/infraops/installation.asciidoc
* Adding note required field for metric detail page and fixing typos
* Update docs/en/infraops/installation.asciidoc
Co-Authored-By: simianhacker <chris@chriscowan.us>
> [Backport][7.x][Infra UI] Adding note required field for metric detail page and fixing typos (#285)

- docs/en/infraops/installation.asciidoc
* Adding note required field for metric detail page and fixing typos
* Update docs/en/infraops/installation.asciidoc
Co-Authored-By: simianhacker <chris@chriscowan.us>
> [Backport][7.0][Infra UI] Adding note required field for metric detail page and fixing typos (#285

- docs/en/stack/monitoring/how-monitoring-works.asciidoc
Added a tip about a separate monitoring cluster and Kibana instance.
> [DOCS] Recommended dedicated Kibana for dedicated monitoring cluster.

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
This PR removes the coming tag for 7.1.0
> [DOCS] Removes coming tag

- docs/en/install-upgrade/breaking.asciidoc
Backports #331 to the 7.x branch.
> Backport: [Docs] Change path to beats breaking changes file (#331)

- docs/en/stack/security/authorization/built-in-roles.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
Addresses issues raised here: https://github.com/elastic/kibana/issues/26819#issuecomment-490656312
> Updating terminology used when describing the privileges `kibana_user` has

- docs/en/install-upgrade/breaking.asciidoc
This PR must be merged at the same time as https://github.com/elastic/beats/pull/12326
> [DOCS] Change notable changes link for 7.2

- docs/en/install-upgrade/breaking.asciidoc
This PR must be merged at the same time as https://github.com/elastic/beats/pull/12328.
> [DOCS] Update notable changes link to point to 8.0

- docs/en/install-upgrade/highlights.asciidoc
Don't merge this PR until after https://github.com/elastic/beats/pull/12492 is merged.
> [DOCS] Add beats 7.2 release highlights

- docs/en/siem/installation.asciidoc
- docs/en/siem/overview.asciidoc
- docs/en/siem/siem-ui.asciidoc
Incorporate review comments from slack, email, and #362
*DO NOT MERGE* - This PR has open review comments and questions peppered throughout content
> [WIP] Incorporate review comments

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
Backports https://github.com/elastic/stack-docs/pull/273
> [7.x] Adds Beats highlights to Install Upgrade Guide

- docs/en/getting-started/get-started-stack.asciidoc
> [DOCS] [7.1] Add steps for homebrew (#384)

- docs/en/getting-started/get-started-stack.asciidoc
Backports the following PRs to 7.2 branch : #198, #229, and #384
> [DOCS][7.2] Backport mutliple PRs to 7.2 (#198, #229, and #384)

- docs/en/stack/monitoring/esms.asciidoc
- docs/en/stack/monitoring/intro.asciidoc
- docs/en/stack/monitoring/troubleshooting.asciidoc
Related to https://github.com/elastic/kibana/pull/39814
This PR updates references to the "Monitoring" page to "Stack Monitoring.
> Updates title for Stack Monitoring app

- docs/en/stack/security/authorization/privileges.asciidoc
Backport of: #395
Co-Authored-By: Lisa Cawley <lcawley@elastic.co>
> [Backport 7.x] Document "manage_api_key" cluster privilege

- docs/en/stack/ml/getting-started.asciidoc
- docs/en/stack/ml/overview.asciidoc
- docs/en/stack/security/authentication/index.asciidoc
- docs/en/stack/security/authorization/index.asciidoc
> [7.x] Removes edit_url attributes (#414)

- docs/en/siem/installation.asciidoc
Changed wording of Packetbeat description, as requested by Install Beats shippers in, as requested in https://github.com/elastic/stack-docs/pull/362#pullrequestreview-248993158
> [Doc] Changed wording of packetbeat description in S

- docs/en/siem/installation.asciidoc
Changed packetbeat description as per #460.
> [Backport] Changed wording of packetbeat description for 7.x

- docs/en/siem/installation.asciidoc
Changed packetbeat description as per #460.
> [Backport] Changed wording of packetbeat description for 7.3

- docs/en/install-upgrade/installing-stack.asciidoc
Add MS Azure as new supported cloud provider.
> Azure update

- docs/en/stack/security/authentication/pki-realm.asciidoc
Bring up PKI authn in Kibana in the Stack docs.
CC @azasypkin
> PKI authn in Kibana

- docs/en/stack/monitoring/esms.asciidoc
Related to https://github.com/elastic/kibana/pull/45594
This PR updates monitoring/esms.asciidoc to reflect the new location of the  kibana/docs/user/monitoring/monitoring-metricbeat.asciidoc file
> Updates path in Stack Overview to Kibana monitoring

- docs/en/install-upgrade/breaking.asciidoc
- Removed //
- Changed 7.2 to 7.4
- Updated intro sentence
> Updates to Kibana section

- docs/en/stack/ml/df-analytics/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/525
> [7.3][DOCS] Fixes link to transform APIs (#525)

- docs/en/siem/installation.asciidoc
- docs/en/siem/siem-ui.asciidoc
General corrections as requested in [#362](https://github.com/elastic/stack-docs/pull/362).
Previews:
- [Get up and running](http://stack-docs_502.docs-preview.app.elstc.co/guide/en/siem/guide/master/install-siem.html)
- [SIEM UI](http://stack-docs_502.docs-preview.app.elstc.co/guide/en/siem/guide/master/siem-ui-overview.html)
> [Docs] SIEM corrections from dev feedback

- docs/en/siem/installation.asciidoc
- docs/en/siem/siem-ui.asciidoc
> [Docs][Backport] SIEM corrections from dev feedback

- docs/en/siem/installation.asciidoc
- docs/en/siem/siem-ui.asciidoc
> [Docs] [Backport] SIEM corrections from dev feedback

- docs/en/siem/siem-ui.asciidoc
Corrects the pivot section title which was incorrectly backported
> [Docs] SIEM correct pivot section title

- docs/en/stack/index.asciidoc
- docs/en/stack/introduction.asciidoc
- docs/en/stack/redirects.asciidoc
Backports https://github.com/elastic/stack-docs/pull/546/
> [7.4] Removes Watcher from Stack Overview (#546)

- docs/en/stack/index.asciidoc
- docs/en/stack/introduction.asciidoc
- docs/en/stack/redirects.asciidoc
Backports https://github.com/elastic/stack-docs/pull/546/
> [7.3] Removes Watcher from Stack Overview (#546)

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
~Blocked by https://github.com/elastic/apm-server/pull/2734.~
OK to merge.
> [docs][7.4] Uncomment APM tagged regions

- docs/en/install-upgrade/highlights.asciidoc
Fix Elasticsearch link for release highlights.
> [DOCS] Update ES 7.4 release highlights include

- docs/en/stack/redirects.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/47585
This PR updates the redirects for pages that now have explicit anchors.
> Security anchor fixes

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/574
> [7.x] Stages removal of security content (#574)

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
> [7.4] Stages removal of security content 

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
> [7.3] Stages removal of security content

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
> [7.2]Stages removal of security content

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
> [7.1] Stages removal of security content

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
> [7.0] Stages removal of security content (#574) (#580)

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/574
> [6.8]Stages removal of security content (#574)

- docs/en/stack/redirects.asciidoc
Fixes a broken link that's blocking the docs buid.
> [DOCS] Fix broken link in redirects

- docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc
- docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
- docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
- docs/en/stack/ml/df-analytics/index.asciidoc
This PR marks the data frame analytics and the related analytics types as experimental features.
> [DOCS] Marks DFA and the related analytics types as experimental feataures

- docs/en/stack/ml/doc-template/ml-feature-template.asciidoc
This PR adds the `ml-feature-template.asciidoc` file to the Stack Docs.
> [DOCS] Adds ML feature template to the repository

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/authentication/active-directory-realm.asciidoc
- docs/en/stack/security/authentication/index.asciidoc
- docs/en/stack/security/authentication/ldap-realm.asciidoc
- docs/en/stack/security/authorization/index.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
> [6.6] Stages removal of security content (#574)

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/authentication/active-directory-realm.asciidoc
- docs/en/stack/security/authentication/index.asciidoc
- docs/en/stack/security/authentication/ldap-realm.asciidoc
- docs/en/stack/security/authorization/index.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
> [6.5][DOCS] Stages removal of security content

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/authentication/active-directory-realm.asciidoc
- docs/en/stack/security/authentication/index.asciidoc
- docs/en/stack/security/authentication/ldap-realm.asciidoc
- docs/en/stack/security/authorization/index.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
- docs/en/stack/security/troubleshooting.asciidoc
> [6.4] Stages removal of security content

- docs/en/stack/redirects.asciidoc
- docs/en/stack/security/authentication/active-directory-realm.asciidoc
- docs/en/stack/security/authentication/index.asciidoc
- docs/en/stack/security/authentication/ldap-realm.asciidoc
- docs/en/stack/security/authorization/index.asciidoc
- docs/en/stack/security/get-started-security.asciidoc
- docs/en/stack/security/index.asciidoc
> [6.3] Stages removal of security content

- docs/en/siem/siem-ui.asciidoc
> [Docs] [Backport] Adds note about map connection lines

- docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR renames the headings of the limitation items in the DFA limitations section.
> [DOCS] Renames limitation items in DFA limitations

- docs/en/getting-started/docker/.env
- docs/en/getting-started/docker/create-certs.yml
- docs/en/getting-started/docker/docker-compose.yml
- docs/en/getting-started/docker/elastic-docker-tls.yml
- docs/en/getting-started/docker/instances.yml
- docs/en/getting-started/get-started-docker.asciidoc
Backporting 
* Added instructions for 3 modes + kibana
* Added TLS section
* Incorporated review comments.
> [DOCS] Added instructions for 3 nodes + kibana (#586)

- docs/en/getting-started/get-started-docker.asciidoc
The broken conditionals are causing broken links from the ES Ref.
> [DOCS] Correcting release conditionals for sample files

- docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
This PR extends the DFA overview piece by adding short descriptions of the available analytics types.
> [DOCS] Extends DFA overview with outlier detection and regression reference

- docs/en/getting-started/docker/elastic-docker-tls.yml
- docs/en/getting-started/get-started-docker.asciidoc
The conditionals were breaking the numbering in the procedures.
> [DOCS] Fix formatting and conditionals. 

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
Updates the beats breaking changes and release highlights links. 
Must be merged along with https://github.com/elastic/beats/pull/14398.
> Updates the beats breaking changes and release highlights links

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
Updates links to Beats breaking changes and highlights
This must be merged at the same time as https://github.com/elastic/beats/pull/14572
> [7.5] Update Beats BC and highlights links

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
- docs/en/install-upgrade/overview.asciidoc
Adds APM release notes and breaking changes to the installation and upgrade guide.
~Blocked by https://github.com/elastic/apm-server/pull/2908.~
~Blocked by https://github.com/elastic/apm-server/pull/2929.~
> [APM][7.5] APM release notes and breaking changes

- docs/en/getting-started/page_header.html
- docs/en/install-upgrade/page_header.html
- docs/en/stack/page_header.html
Backports https://github.com/elastic/stack-docs/pull/694
Preview:
http://stack-docs_697.docs-preview.app.elstc.co/guide/en/elastic-stack/7.3/index.html
http://stack-docs_697.docs-preview.app.elstc.co/guide/en/elastic-stack-get-started/7.3/index.html
http://stack-docs_697.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/7.3/index.html
> Adds OOM banners in stack books

- docs/en/stack/ml/anomaly-detection/index.asciidoc
This PR amends the intro paragraph of the anomaly detection landing page.
Related issue: https://github.com/elastic/ml-team/issues/187#issuecomment-513162459
> [DOCS] Changes the intro paragraph on the anomaly detection landing page

- docs/en/siem/siem-ui.asciidoc
Backports [#792](https://github.com/elastic/stack-docs/pull/729)
> [SIEM] [Docs][Backport]Fixes ECS field name in map connection lines note

- docs/en/stack/index.asciidoc
- docs/en/stack/redirects.asciidoc
> [7.1][DOCS] Remove CCR docs from Stack Overview (#464)

- docs/en/stack/index.asciidoc
- docs/en/stack/redirects.asciidoc
> [7.0][DOCS] Remove CCR docs from Stack Overview (#464)

- docs/en/stack/index.asciidoc
- docs/en/stack/redirects.asciidoc
> [6.8][DOCS] Remove CCR docs from Stack Overview (#464)

- docs/en/stack/index.asciidoc
- docs/en/stack/redirects.asciidoc
> [6.7][DOCS] Remove CCR docs from Stack Overview (#464)

- docs/en/siem/installation.asciidoc
- docs/en/siem/siem-ui.asciidoc
> [SIEM][Docs][Backport]Clarifies SIEM index and Kibana index pattern requirements

- docs/en/siem/machine-learning.asciidoc
> [SIEM][Backport]7.x adds ecs fields for ml jobs

- docs/en/siem/machine-learning.asciidoc
> [SIEM][Backport]7.5 adds ecs fields for ml jobs

- docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Removes hyperparameter optimization link.
> [7.x][DOCS] Removes link from DFA limitation section

- docs/en/metrics/aws-ec2-metricset.asciidoc
- docs/en/metrics/aws-rds-metricset.asciidoc
- docs/en/metrics/aws-s3-metricset.asciidoc
- docs/en/metrics/aws-sqs-metricset.asciidoc
- docs/en/metrics/docker-metricset.asciidoc
- docs/en/metrics/host-metricset.asciidoc
- docs/en/metrics/infrastructure-metrics.asciidoc
- docs/en/metrics/kubernetes-metricset.asciidoc
* [Metrics UI] Update docs with AWS Metricset fields
* Adding includes for metricsets
* Fixing typo
* fixing typo
* Moving the includes for metricsets; increasing heading levels
> [7.x][Backport][Metrics UI] Update docs with AWS Metricset fields (#797)

- docs/en/stack/ml/anomaly-detection/getting-started.asciidoc
Companion PR to
https://github.com/elastic/elasticsearch/pull/46456 / https://github.com/elastic/kibana/pull/54606
> Deprecate kibana_user role

- docs/en/siem/machine-learning.asciidoc
Sorts list of prebuilt ML jobs in alphabetical order. No review required as no text was changed.
> [SIEM][Docs]Sorts list of prebuilt ml jobs

- docs/en/gke-on-prem/page_header.html
Related docs PR: https://github.com/elastic/docs/pull/1699
Closes https://github.com/elastic/stack-docs/issues/495.
> [docs] Add deprecation warning to Google Cloud's Anthos docs

- docs/en/siem/detection-engine-intro.asciidoc
> [Docs][SIEM] Improves detections permissions docs

- docs/en/stack/ml/anomaly-detection/algorithms.asciidoc
- docs/en/stack/ml/anomaly-detection/analyzing.asciidoc
- docs/en/stack/ml/anomaly-detection/overview.asciidoc
This PR augments the machine learning anomaly detection overview with information about which algorithms it uses.
http://stack-docs_833.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-overview.html#anomaly-algorithms
> [DOCS] Adds overview of anomaly detection algorithms

- docs/en/siem/rule-details/web-application-suspicious-activity-no-user-agent.asciidoc
- docs/en/siem/rule-details/web-application-suspicious-activity-post-request-declined.asciidoc
- docs/en/siem/rule-details/web-application-suspicious-activity-sqlmap-user-agent.asciidoc
- docs/en/siem/rule-details/web-application-suspicious-activity-unauthorized-method.asciidoc
Escapes asterisks characters in APM indices.
> [Docs][SIEM]Escapes asterisk character in apm indices

- docs/en/siem/siem-ui.asciidoc
> [Docs][SIEM]Fixes APM text and link

- docs/en/siem/overview.asciidoc
- docs/en/siem/siem-ui.asciidoc
Adds info about the `apm-*-transaction*` index pattern.
> [Docs][SIEM]Adds APM indices

- docs/en/siem/detection-engine-intro.asciidoc
- docs/en/siem/installation.asciidoc
- docs/en/siem/privileges-api-overview.asciidoc
Might help users deal with this issue: https://github.com/elastic/kibana/issues/57414.
[Preview](http://stack-docs_873.docs-preview.app.elstc.co/guide/en/siem/guide/master/detection-engine-overview.html#detections-permissions)
> [Docs][SIEM]Updates for Detections configuration requirements and errors

- docs/en/siem/detection-engine-intro.asciidoc
- docs/en/siem/installation.asciidoc
- docs/en/siem/privileges-api-overview.asciidoc
- [Docs][SIEM]Updates for Detections configuration requirements and errors (#873)
> [7.x] [Docs][SIEM]Updates for Detections configuration requirements and errors (#873)

- docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
Adds Further readings section with a link that points to a related blog post.
> [DOCS] Adds Further readings section to the lang ident docs

- docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR fine-tunes one of the DFA limitation items.
> [DOCS] Refines DFA memory limitation

- docs/en/endpoint/index.asciidoc
- [DOCS]: Fix endpoint image (#898)
> [7.x] [DOCS]: Fix endpoint image (#898)

- docs/en/endpoint/index.asciidoc
- [DOCS]: Fix endpoint image (#898)
> [7.6] [DOCS]: Fix endpoint image (#898)

- docs/en/siem/tune-rule-signals.asciidoc
Small change to indicate the rules tuning section is for prebuilt rules.
> [Docs][SIEM]Corrects tuning prebuilt rules section title

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
This PR depends on https://github.com/elastic/beats/pull/16584
It adds the Beats highlights and breaking changes to the Installation and Upgrade Guide.
> [DOCS] Adds Beats highlights and breaking changes

- docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
- [ML] adding multi-field limitation for inference + analytics (#920)
> [7.x] [ML] adding multi-field limitation for inference + analytics (#920)

- docs/en/siem/rules-api-bulk-actions.asciidoc
- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-api-update.asciidoc
- [Docs][SIEM]Adds PATCH method to update rule api (#921)
> [7.6] [Docs][SIEM]Adds PATCH method to update rule api (#921)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
- [Docs][ML]Updates prebuilt ml jobs file links (#918)
> [7.x] [Docs][ML]Updates prebuilt ml jobs file links (#918)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
- [Docs][ML]Updates prebuilt ml jobs file links (#918)
> [7.6] [Docs][ML]Updates prebuilt ml jobs file links (#918)

- docs/en/stack/ml/get-started/get-started-jobs.asciidoc
- docs/en/stack/ml/get-started/get-started-next.asciidoc
- docs/en/stack/ml/get-started/get-started-prereqs.asciidoc
- docs/en/stack/ml/get-started/index.asciidoc
This PR makes several minor edits to the "getting started with machine learning" content (https://www.elastic.co/guide/en/machine-learning/master/ml-getting-started.html)
> [DOCS] Edits machine learning tutorial

- docs/en/siem/privileges-api-overview.asciidoc
- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-api-update.asciidoc
Fixes an error in the docs for rule/privileges API.
Preview: http://stack-docs_947.docs-preview.app.elstc.co/guide/en/siem/guide/master/privileges-api-overview.html
https://github.com/elastic/kibana/issues/60269
> [Docs][SIEM]Fixes rules privileges example and typo

- docs/en/siem/index-api-overview.asciidoc
- docs/en/siem/installation.asciidoc
- docs/en/siem/privileges-api-overview.asciidoc
- docs/en/siem/rules-api-bulk-actions.asciidoc
- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-api-delete.asciidoc
- docs/en/siem/rules-api-export.asciidoc
- docs/en/siem/rules-api-find.asciidoc
- docs/en/siem/rules-api-get.asciidoc
- docs/en/siem/rules-api-import.asciidoc
- docs/en/siem/rules-api-overview.asciidoc
- docs/en/siem/rules-api-prebuilt.asciidoc
- docs/en/siem/rules-api-update.asciidoc
- docs/en/siem/signals-api-overview.asciidoc
- docs/en/siem/tags-api-overview.asciidoc
Fixes API request URLs and add ref to CCS.
Fixes: https://github.com/elastic/stack-docs/issues/950
> [Docs][SIEM]General doc improvements 

- docs/en/siem/index-api-overview.asciidoc
- docs/en/siem/installation.asciidoc
- docs/en/siem/privileges-api-overview.asciidoc
- docs/en/siem/rules-api-bulk-actions.asciidoc
- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-api-delete.asciidoc
- docs/en/siem/rules-api-export.asciidoc
- docs/en/siem/rules-api-find.asciidoc
- docs/en/siem/rules-api-get.asciidoc
- docs/en/siem/rules-api-import.asciidoc
- docs/en/siem/rules-api-overview.asciidoc
- docs/en/siem/rules-api-prebuilt.asciidoc
- docs/en/siem/rules-api-update.asciidoc
- docs/en/siem/signals-api-overview.asciidoc
- docs/en/siem/tags-api-overview.asciidoc
- [Docs][SIEM]General doc improvements  (#957)
> [7.7] [Docs][SIEM]General doc improvements  (#957)

- docs/en/siem/index-api-overview.asciidoc
- docs/en/siem/installation.asciidoc
- docs/en/siem/privileges-api-overview.asciidoc
- docs/en/siem/rules-api-bulk-actions.asciidoc
- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-api-delete.asciidoc
- docs/en/siem/rules-api-export.asciidoc
- docs/en/siem/rules-api-find.asciidoc
- docs/en/siem/rules-api-get.asciidoc
- docs/en/siem/rules-api-import.asciidoc
- docs/en/siem/rules-api-overview.asciidoc
- docs/en/siem/rules-api-prebuilt.asciidoc
- docs/en/siem/rules-api-update.asciidoc
- docs/en/siem/signals-api-overview.asciidoc
- docs/en/siem/tags-api-overview.asciidoc
- [Docs][SIEM]General doc improvements  (#957)
> [7.6] [Docs][SIEM]General doc improvements  (#957)

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
This PR updates the "coming" tags in the Installation and Upgrade Guide and comments out tagged sections that aren't ready yet.
> [DOCS] Update Install and Upgrade tagged sections

- docs/en/siem/prebuilt-rules-changelog.asciidoc
- docs/en/siem/prebuilt-rules-reference.asciidoc
- docs/en/siem/rule-details/adobe-hijack-persistence.asciidoc
Updates Adobe Hijack Persistence rule.
[Preview](http://stack-docs_966.docs-preview.app.elstc.co/guide/en/siem/guide/master/prebuilt-rules-changelog.html)
> [Docs][SIEM] Updates rule changeling for 7.6.2

- docs/en/siem/prebuilt-rules-changelog.asciidoc
- docs/en/siem/prebuilt-rules-reference.asciidoc
- docs/en/siem/rule-details/adobe-hijack-persistence.asciidoc
- [Docs][SIEM] Updates rule changeling for 7.6.2 (#966)
> [7.x] [Docs][SIEM] Updates rule changeling for 7.6.2 (#966)

- docs/en/siem/prebuilt-rules-changelog.asciidoc
- docs/en/siem/prebuilt-rules-reference.asciidoc
- docs/en/siem/rule-details/adobe-hijack-persistence.asciidoc
- [Docs][SIEM] Updates rule changeling for 7.6.2 (#966)
> [7.7] [Docs][SIEM] Updates rule changeling for 7.6.2 (#966)

- docs/en/siem/prebuilt-rules-changelog.asciidoc
- docs/en/siem/prebuilt-rules-reference.asciidoc
- docs/en/siem/rule-details/adobe-hijack-persistence.asciidoc
- [Docs][SIEM] Updates rule changeling for 7.6.2 (#966)
> [7.6] [Docs][SIEM] Updates rule changeling for 7.6.2 (#966)

- docs/en/siem/case-api-update-connector.asciidoc
- docs/en/siem/cases-api-add-comment.asciidoc
- docs/en/siem/cases-api-assign-connector.asciidoc
- docs/en/siem/cases-api-associate-sn.asciidoc
- docs/en/siem/cases-api-create.asciidoc
- docs/en/siem/cases-api-delete-all-comments.asciidoc
- docs/en/siem/cases-api-delete-case.asciidoc
- docs/en/siem/cases-api-delete-comment.asciidoc
- docs/en/siem/cases-api-find-cases.asciidoc
- docs/en/siem/cases-api-find-connectors.asciidoc
- docs/en/siem/cases-api-get-case-activity.asciidoc
- docs/en/siem/cases-api-get-case-comments.asciidoc
- docs/en/siem/cases-api-get-case.asciidoc
- docs/en/siem/cases-api-get-comment.asciidoc
- docs/en/siem/cases-api-get-connector.asciidoc
- docs/en/siem/cases-api-get-reporters.asciidoc
- docs/en/siem/cases-api-get-status.asciidoc
- docs/en/siem/cases-api-get-tags.asciidoc
- docs/en/siem/cases-api-update-comment.asciidoc
- docs/en/siem/cases-api-update.asciidoc
- docs/en/siem/cases-api.asciidoc
- docs/en/siem/cases-kbn-actions-api.asciidoc
- docs/en/siem/cases-overview.asciidoc
- docs/en/siem/index.asciidoc
- [SIEM] [Docs] Cases API (#761)
> [7.x] [SIEM] [Docs] Cases API (#761)

- docs/en/siem/siem-ui.asciidoc
- [Docs][SIEM] 7.7 timeline and reputation link updates (#981)
> [7.x] [Docs][SIEM] 7.7 timeline and reputation link updates (#981)

- docs/en/siem/siem-ui.asciidoc
- [Docs][SIEM] 7.7 timeline and reputation link updates (#981)
> [7.7] [Docs][SIEM] 7.7 timeline and reputation link updates (#981)

- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-api-update.asciidoc
- [Docs][SIEM]Rules API ml rule type (#983)
> [7.x] [Docs][SIEM]Rules API ml rule type (#983)

- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-api-update.asciidoc
- [Docs][SIEM]Rules API ml rule type (#983)
> [7.7] [Docs][SIEM]Rules API ml rule type (#983)

- docs/en/siem/detection-engine-intro.asciidoc
- [Docs][SIEM]Corrects required detections privileges (#1003)
> [7.x] [Docs][SIEM]Corrects required detections privileges (#1003)

- docs/en/siem/cases-kbn-actions-api.asciidoc
- docs/en/siem/cases-overview.asciidoc
- docs/en/siem/cases-ui-integrations.asciidoc
- docs/en/siem/detection-engine-intro.asciidoc
- docs/en/siem/installation.asciidoc
- docs/en/siem/overview.asciidoc
- docs/en/siem/privileges-api-overview.asciidoc
- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-ui-create.asciidoc
- docs/en/siem/tune-anomaly-results.asciidoc
- docs/en/siem/tune-rule-signals.asciidoc
- [Docs][SIEM]General proofing and editing (#1019)
> [7.x] [Docs][SIEM]General proofing and editing (#1019)

- docs/en/siem/cases-kbn-actions-api.asciidoc
- docs/en/siem/cases-overview.asciidoc
- docs/en/siem/cases-ui-integrations.asciidoc
- docs/en/siem/detection-engine-intro.asciidoc
- docs/en/siem/installation.asciidoc
- docs/en/siem/overview.asciidoc
- docs/en/siem/privileges-api-overview.asciidoc
- docs/en/siem/rules-api-create.asciidoc
- docs/en/siem/rules-ui-create.asciidoc
- docs/en/siem/tune-anomaly-results.asciidoc
- docs/en/siem/tune-rule-signals.asciidoc
- [Docs][SIEM]General proofing and editing (#1019)
> [7.7] [Docs][SIEM]General proofing and editing (#1019)

- docs/en/siem/detection-engine-intro.asciidoc
- docs/en/siem/installation.asciidoc
- docs/en/siem/machine-learning.asciidoc
- docs/en/siem/overview.asciidoc
- docs/en/siem/privileges-api-overview.asciidoc
- docs/en/siem/rules-ui-create.asciidoc
- docs/en/siem/tune-anomaly-results.asciidoc
- docs/en/siem/tune-rule-signals.asciidoc
Updates the ml license text and fixes typos.
> [Docs][SIEM]License text change and proofing

- docs/en/siem/installation.asciidoc
- docs/en/siem/machine-learning.asciidoc
- docs/en/siem/overview.asciidoc
- docs/en/siem/siem-ui.asciidoc
- docs/en/siem/tune-anomaly-results.asciidoc
Updates structure for merging with Endpoint docs.
> [Docs][SIEM]Structure update

- docs/en/siem/installation.asciidoc
- docs/en/siem/machine-learning.asciidoc
- docs/en/siem/overview.asciidoc
- docs/en/siem/siem-ui.asciidoc
- docs/en/siem/tune-anomaly-results.asciidoc
- [Docs][SIEM]Structure update (#1027)
> [7.x] [Docs][SIEM]Structure update (#1027)

- docs/en/siem/installation.asciidoc
- docs/en/siem/machine-learning.asciidoc
- docs/en/siem/overview.asciidoc
- docs/en/siem/siem-ui.asciidoc
- docs/en/siem/tune-anomaly-results.asciidoc
- [Docs][SIEM]Structure update (#1027)
> [7.7] [Docs][SIEM]Structure update (#1027)

- docs/en/getting-started/get-started-docker.asciidoc
Backports https://github.com/elastic/stack-docs/pull/991 to 7.x/7.8
> Deprecate kibana user in favor of kibana_system user

- docs/en/siem/rules-api-overview.asciidoc
Adds a link to a Detections API postman collection.
> [Docs][SIEM]Adds link to postman collection example

- docs/en/siem/rules-api-overview.asciidoc
- adds link to postman collection example (#1034)
> [7.x] adds link to postman collection example (#1034)

- docs/en/getting-started/get-started-stack.asciidoc
Providing some cursory edits to the introductory section of the _Getting Started Guide_.
> Edits to introductory section

- docs/en/getting-started/get-started-stack.asciidoc
Backport of #940 
Providing some cursory edits to the introductory section of the _Getting Started Guide_.
Co-authored-by: Adam <adam.locke@datastax.com>
> Edits to introductory section (#940)

- docs/en/install-upgrade/breaking.asciidoc
This PR updates links to breaking changes from the Installation and Upgrade Guide.
> [DOCS] Update links for breaking changes

- docs/en/siem/rule-details/adversary-behavior-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/credential-dumping-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/credential-dumping-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/credential-manipulation-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/credential-manipulation-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/exploit-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/exploit-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/malware-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/malware-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/permission-theft-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/permission-theft-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/process-injection-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/process-injection-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/ransomware-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/ransomware-prevented-elastic-endpoint.asciidoc
Updates the prebuilt rules doc with the new endpoint rules look back time.
> [Docs][SIEM]Updates prebuilt endpoint rules look back time

- docs/en/siem/rule-details/adversary-behavior-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/credential-dumping-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/credential-dumping-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/credential-manipulation-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/credential-manipulation-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/exploit-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/exploit-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/malware-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/malware-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/permission-theft-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/permission-theft-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/process-injection-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/process-injection-prevented-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/ransomware-detected-elastic-endpoint.asciidoc
- docs/en/siem/rule-details/ransomware-prevented-elastic-endpoint.asciidoc
- updates prebuilt endpoint rules look back time (#1040)
> [7.x] updates prebuilt endpoint rules look back time (#1040)

- docs/en/siem/cases-kbn-actions-api.asciidoc
- docs/en/siem/siem-ui.asciidoc
Adds a link to the geoip-info pipeline in the examples repo
> [Docs][SIEM]Adds link to beats pipeline example and corrects typo

- docs/en/siem/detections/rules-ui-create.asciidoc
Adds ml admin role requirement for creating and editing ml detection rules.
[Preview](http://stack-docs_1081.docs-preview.app.elstc.co/guide/en/siem/guide/master/rules-ui-create.html#create-rule-ui)
> [Docs][SIEM]Adds ml admin role requirement

- docs/en/siem/detections/rules-ui-create.asciidoc
- adds ml admin role requirement (#1081)
> [7.x] adds ml admin role requirement (#1081)

- docs/en/siem/detections/rules-ui-create.asciidoc
- adds ml admin role requirement (#1081)
> [7.8] adds ml admin role requirement (#1081)

- docs/en/siem/detections/api/rules-api-create.asciidoc
- docs/en/siem/detections/rules-ui-create.asciidoc
Adds the list of available signal notification placeholders.
[Preview](http://stack-docs_1090.docs-preview.app.elstc.co/guide/en/siem/guide/master/rules-ui-create.html#rule-action-variables)
> [Docs][SIEM]Adds list of signal notification placeholders

- docs/en/siem/detections/api/rules-api-create.asciidoc
- docs/en/siem/detections/rules-ui-create.asciidoc
- adds list of rule notifications placeholders (#1090)
> [7.x] adds list of rule notifications placeholders (#1090)

- docs/en/siem/detections/api/rules-api-create.asciidoc
- docs/en/siem/detections/rules-ui-create.asciidoc
- adds list of rule notifications placeholders (#1090)
> [7.8] adds list of rule notifications placeholders (#1090)

- docs/en/siem/detections/api/rules-api-create.asciidoc
- docs/en/siem/detections/rules-ui-create.asciidoc
- adds list of rule notifications placeholders (#1090)
> [7.7] adds list of rule notifications placeholders (#1090)

- docs/en/siem/field-ref.asciidoc
- docs/en/siem/index.asciidoc
- docs/en/siem/installation.asciidoc
- [Docs][SIEM]Adds field reference list (#1033)
> [7.x] [Docs][SIEM]Adds field reference list (#1033)

- docs/en/siem/field-ref.asciidoc
- docs/en/siem/index.asciidoc
- docs/en/siem/installation.asciidoc
- [Docs][SIEM]Adds field reference list (#1033)
> [7.8] [Docs][SIEM]Adds field reference list (#1033)

- docs/en/siem/field-ref.asciidoc
- docs/en/siem/index.asciidoc
- docs/en/siem/installation.asciidoc
- [Docs][SIEM]Adds field reference list (#1033)
> [7.7] [Docs][SIEM]Adds field reference list (#1033)

- docs/en/getting-started/get-started-stack.asciidoc
> Remove LS steps from the stack getting started

- docs/en/getting-started/get-started-stack.asciidoc
- Remove LS steps from the stack getting started (#1099)
> [7.8] Remove LS steps from the stack getting started (#1099)

- docs/en/getting-started/get-started-stack.asciidoc
- Remove LS steps from the stack getting started (#1099)
> [7.x] Remove LS steps from the stack getting started (#1099)

- docs/en/stack/index-landing-all-collapsible.adoc
- docs/en/stack/index-landing-all.adoc
- docs/en/stack/landing-all.asciidoc
- docs/en/stack/landing.asciidoc
This PR builds on https://github.com/elastic/stack-docs/pull/1078. The content is still a work in progress.
> [DOCS] Drafts shared landing page

- docs/en/getting-started/index.asciidoc
- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
- docs/en/install-upgrade/index.asciidoc
- docs/en/siem/index.asciidoc
- docs/en/stack/index.asciidoc
- docs/en/stack/ml/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1116
> [7.x][DOCS] Replace docdir attributes with root attributes (#1116)

- docs/en/getting-started/index.asciidoc
- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
- docs/en/install-upgrade/index.asciidoc
- docs/en/siem/index.asciidoc
- docs/en/stack/index.asciidoc
- docs/en/stack/ml/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1116
> [7.8][DOCS] Replace docdir attributes with root attributes (#1116)

- docs/en/getting-started/index.asciidoc
- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
- docs/en/install-upgrade/index.asciidoc
- docs/en/siem/index.asciidoc
- docs/en/stack/index.asciidoc
- docs/en/stack/ml/index.asciidoc
> [7.7][DOCS] Replace docdir attributes with root attributes (#1116)

- docs/en/stack/index-landing.adoc
- docs/en/stack/landing-all.asciidoc
- docs/en/stack/landing.asciidoc
- docs/en/stack/redirects-landing.adoc
This PR adds content related to transform to the WIP landing page and revamps the "Analyze your data" section.
> [DOCS] Adds transform content to landing page

- docs/en/stack/index-landing-observability-collapsible.adoc
- docs/en/stack/index-landing-observability.adoc
- docs/en/stack/landing-all.asciidoc
- docs/en/stack/landing-observability.asciidoc
This is a work in progress related to Observability landing pages.
> [DOCS] Drafts layout of Observability content

- docs/en/siem/field-ref.asciidoc
Need to double-check that all listed fields are actually required - especially non-ECS field.
Original PR that added the fields: https://github.com/elastic/stack-docs/pull/1033
[Preview](http://stack-docs_1103.docs-preview.app.elstc.co/guide/en/siem/guide/master/siem-field-reference.html)
> [Docs][SIEM]Updates required fields section

- docs/en/siem/field-ref.asciidoc
- [Docs][SIEM]Updates required fields section (#1103)
> [7.x] [Docs][SIEM]Updates required fields section (#1103)

- docs/en/siem/field-ref.asciidoc
- [Docs][SIEM]Updates required fields section (#1103)
> [7.8] [Docs][SIEM]Updates required fields section (#1103)

- docs/en/siem/field-ref.asciidoc
- [Docs][SIEM]Updates required fields section (#1103)
> [7.7] [Docs][SIEM]Updates required fields section (#1103)

- docs/en/ingest-management/troubleshooting.asciidoc
First pass of Ingest Manager Troubleshooting Docs.  @ph @dedemorton @ruflin @skh thanks for the help and review.  cheers.
> Add Ingest Manager Troubleshooting FAQ doc

- docs/en/ingest-management/troubleshooting.asciidoc
- Add Ingest Manager Troubleshooting FAQ doc (#1148)
> [7.x] Add Ingest Manager Troubleshooting FAQ doc (#1148)

- docs/en/ingest-management/troubleshooting.asciidoc
- Add Ingest Manager Troubleshooting FAQ doc (#1148)
> [7.8] Add Ingest Manager Troubleshooting FAQ doc (#1148)

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/overview.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
First pass:
- Clean up asciidoc coding
- Make a few minor tweaks to text (edits are still required)
To do before merging:
> Get ingest management docs ready to publish

- docs/en/ingest-management/getting-started.asciidoc
Temporarily comments out link until I get everything hooked up.
> Fix broken link

- docs/en/ingest-management/getting-started.asciidoc
> [7.x] fix broken link (#1154)

- docs/en/ingest-management/getting-started.asciidoc
> [7.8] fix broken link (#1154)

- docs/en/ingest-management/index.asciidoc
Commenting out overview to avoid breaking the build.
> Temporarily comment out overview

- docs/en/ingest-management/index.asciidoc
Activates the Elastic Agent docs in the ingest management guide.
> Get agent docs building

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
Please answer all questions flagged for reviewers.
Summary of changes:
* Edit to conform to Elastic style guidelines
* Break walls of text into easy-to-scan list
* Use attributes for product names
Ooof. The diff is hard to follow. It's probably best to review the preview: https://stack-docs_1160.docs-preview.app.elstc.co/guide/en/ingest-management/master/ingest-management-troubleshooting.html
> Edit ingest management troubleshooting docs

- docs/en/ingest-management/troubleshooting.asciidoc
- Edit ingest management troubleshooting docs (#1160)
> [7.8] Edit ingest management troubleshooting docs (#1160)

- docs/en/ingest-management/troubleshooting.asciidoc
- Edit ingest management troubleshooting docs (#1160)
> [7.x] Edit ingest management troubleshooting docs (#1160)

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
Summary of changes:
- Apply edits to align with Elastics style guidelines for writing about UIs.
- Move all prereqs to a single section and added to the list.
- Change procedures to use numbered lists for improved scanability.
- Movedstandalone steps to appear after fleet steps as requested by @mostlyjason.
> Edit ingest management getting started guide

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Edit ingest management getting started guide (#1175)
> [7.x] Edit ingest management getting started guide (#1175)

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Edit ingest management getting started guide (#1175)
> [7.8] Edit ingest management getting started guide (#1175)

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/ingest-management-limitations.asciidoc
- docs/en/ingest-management/ingest-management-overview.asciidoc
- docs/en/ingest-management/overview.asciidoc
- Edit ingest management overview (#1168)
> [7.x] Edit ingest management overview (#1168)

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/ingest-management-limitations.asciidoc
- docs/en/ingest-management/ingest-management-overview.asciidoc
- docs/en/ingest-management/overview.asciidoc
- Edit ingest management overview (#1168)
> [7.8] Edit ingest management overview (#1168)

- docs/en/install-upgrade/highlights.asciidoc
Merge after https://github.com/elastic/beats/pull/18493
> Activate include for 7.8 Beats release highlights

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/ingest-management-limitations.asciidoc
- docs/en/ingest-management/ingest-management-overview.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
Adds changes for remaining work listed in https://github.com/elastic/beats/issues/19036
> Clean up ingest management docs

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
Fixes doc changes required by https://github.com/elastic/kibana/issues/69677.
> [DOCS] Document encryption key setting needed by Fleet

- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
- docs/en/stack/ml/df-analytics/index.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1259
> [7.x][DOCS] Removes ML content from index.asciidoc files

- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
- docs/en/stack/ml/df-analytics/index.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
> [7.8][DOCS] Removes ML content from index.asciidoc files

- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc
- docs/en/stack/ml/df-analytics/index.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
> [7.7][DOCS] Removes ML content from index.asciidoc files

- docs/en/getting-started/get-started-docker.asciidoc
- docs/en/install-upgrade/installing-stack.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1237
> [7.x][DOCS] Clarify trial subscription levels (#1237)

- docs/en/getting-started/get-started-docker.asciidoc
- docs/en/install-upgrade/installing-stack.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1237
> [7.8][DOCS] Clarify trial subscription levels (#1237)

- docs/en/getting-started/get-started-docker.asciidoc
- docs/en/install-upgrade/installing-stack.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1237
> [7.7][DOCS] Clarify trial subscription levels (#1237)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1276
> [7.x][DOCS] Sorts APM ML modules (#1276)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1270#pullrequestreview-448053372
This PR groups the machine learning jobs by module rather than sorting them alphabetically in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html
https://stack-docs_1275.docs-preview.app.elstc.co/diff
> [DOCS] Sorts SIEM ML modules

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1275
> [7.x][DOCS] Sorts SIEM ML modules (#1275)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1275
> [7.9][DOCS] Sorts SIEM ML modules (#1275)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
> [Docs][ML]Fixes broken SIEM link

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1270
> [7.x][DOCS] Adds siem_cloudtrail module (#1270)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1270
> [7.9][DOCS] Adds siem_cloudtrail module (#1270)

- docs/en/install-upgrade/highlights.asciidoc
Cherry-picks #1307 to 7.9 branch.
> [7.9] Change highlights path

- docs/en/install-upgrade/highlights.asciidoc
Cherry-picks #1307 to 7.x branch.
> [7.x] Change highlights path

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- [Docs][ML]Updates ML job group names (#1317)
> [7.x] [Docs][ML]Updates ML job group names (#1317)

- docs/en/stack/ml/setup.asciidoc
Related to https://github.com/elastic/stack-docs/issues/1303
This PR updates the details about the feature controls required to use machine learning features in Kibana.
It must be merged after https://github.com/elastic/docs/pull/1926
https://stack-docs_1304.docs-preview.app.elstc.co/guide/en/machine-learning/master/setup.html
> [DOCS] Update machine learning security privileges

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1304
> [7.x][DOCS] Update machine learning security privileges (#1304)

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1304
> [7.9][DOCS] Update machine learning security privileges (#1304)

- docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
This PR adds a title to the third column of the DFA overview table.
[DFA overview](https://stack-docs_1329.docs-preview.app.elstc.co/guide/en/machine-learning/7.9/ml-dfa-overview.html)
> [7.9] [DOCS] Adds column title to overview table

- docs/en/glossary/glossary.asciidoc
Related to https://github.com/elastic/kibana/pull/74410
https://stack-docs_1330.docs-preview.app.elstc.co/guide/en/elastic-stack-glossary/current/terms.html#k-glos
> [DOCS] Add Kibana privileges to glossary

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
This PR uncomments the Kibana highlights and breaking changes in the Installation and Upgrade Guide.
https://stack-docs_1335.docs-preview.app.elstc.co/guide/en/elastic-stack/7.9/kibana-higlights.html
> [DOCS] Add Kibana highlights to Install Upgrade Guide

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
This PR uncomments the APM breaking changes and a highlight link in the Installation and Upgrade Guide.
> [DOCS] Uncomments APM breaking changes

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
Remove coming tags and activate links to breaking changes.
> Remove coming tags and activate links

- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Forward-fits https://github.com/elastic/stack-docs/pull/1337
> [7.x][DOCS] Adds ML troubleshooting for upgrade (#1337)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
This PR fixes a typo in the OOTB metricbeat jobs piece.
> [DOCS] Fixes typo in OOTB metricbeat jobs

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
This PR adds the `Working anomaly detection at scale` piece to the AD documentation under the `Configuration` section.
* [Configuring anomaly detection](https://stack-docs_1353.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-configuration.html)
* [Working with anomaly detection at scale](https://stack-docs_1353.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-detection-scale.html)
> [DOCS] Adds Working with anomaly detection at scale to ML AD docs

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
- [DOCS] Adds Working with anomaly detection at scale to ML AD docs (#1353)
> [7.x] [DOCS] Adds Working with anomaly detection at scale to ML AD docs (#1353)

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
- [DOCS] Adds Working with anomaly detection at scale to ML AD docs (#1353)
> [7.9] [DOCS] Adds Working with anomaly detection at scale to ML AD docs (#1353)

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
This PR adds two more sentences to the section about forecasts.
[Reduce the cost of forecasting](https://stack-docs_1356.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-detection-scale.html#forecasting)
> [DOCS] Adds further info to forecast section in AD at scale

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds further info to foreceast section in AD at scale. (#1356)
> [7.x] [DOCS] Adds further info to foreceast section in AD at scale. (#1356)

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds further info to foreceast section in AD at scale. (#1356)
> [7.9] [DOCS] Adds further info to foreceast section in AD at scale. (#1356)

- docs/en/install-upgrade/highlights.asciidoc
Companion PR to this commit (which I accidentally pushed so I'm racing against the clock here)
https://github.com/elastic/apm-server/commit/017761e66e5375b6d2e1943642ebd539185c12d9
> docs: update apm include

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1363
> [7.x][DOCS] Add metadata and discovery analysis jobs

- docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Related to https://github.com/elastic/kibana/issues/80003 and https://github.com/elastic/elasticsearch/pull/63781
This PR adds prerequisite information in the [AUC ROC evaluation details](https://www.elastic.co/guide/en/machine-learning/master/ml-dfanalytics-evaluate.html#ml-dfanalytics-class-aucroc)
https://stack-docs_1420.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfanalytics-evaluate.html#ml-dfanalytics-class-aucroc
> [DOCS] Adds AUC ROC prerequisite

- docs/en/install-upgrade/highlights.asciidoc
Related to https://github.com/elastic/kibana/pull/81963
> [DOCS] Add Kibana highlights

- docs/en/install-upgrade/breaking.asciidoc
Related to https://github.com/elastic/kibana/pull/80926
> Adds Kibana breaking changes

- docs/en/install-upgrade/highlights.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/64666
> [DOCS] Enable stack highlights

- docs/en/install-upgrade/breaking.asciidoc
Final PR! Uncomments the APM breaking changes for 7.10
> [7.10] docs: uncomment APM breaking changes

- docs/en/glossary/glossary.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/64838 and https://github.com/elastic/elasticsearch/pull/64834
> Add data tier defs to glossary

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)
> [7.x] [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)
> [7.10] [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)
> [7.9] [DOCS] Adds scroll_size related recommendation to AD at scale (#1445)

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
This PR expands the `Pre-aggregate your data` section in the Anomaly detection at scale piece with recommendation around `chunking_config`.
[ADAS – Pre-aggregate your data](https://stack-docs_1449.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-detection-scale.html#pre-aggregate-data)
> [DOCS] Adds chunking_config recommendation to AD at scale

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds chunking_config recommendation to AD at scale (#1449)
> [7.x] [DOCS] Adds chunking_config recommendation to AD at scale (#1449)

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds chunking_config recommendation to AD at scale (#1449)
> [7.10] [DOCS] Adds chunking_config recommendation to AD at scale (#1449)

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
- [DOCS] Adds chunking_config recommendation to AD at scale (#1449)
> [7.9] [DOCS] Adds chunking_config recommendation to AD at scale (#1449)

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1453
> [7.x][DOCS] ML setup clarifications (#1453)

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs
> [7.10][DOCS] ML setup clarifications (#1453)

- docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
- [DOCS] Reviews anomaly detection limitations (#1471)
> [7.10] [DOCS] Reviews anomaly detection limitations (#1471)

- docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
- [DOCS] Reviews anomaly detection limitations (#1471)
> [7.x] [DOCS] Reviews anomaly detection limitations (#1471)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
- [DOCS] Expands supplied configurations docs (#1477)
> [7.x] [DOCS] Expands supplied configurations docs (#1477)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
- [DOCS] Expands supplied configurations docs (#1477)
> [7.10] [DOCS] Expands supplied configurations docs (#1477)

- docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
> [DOCS] Fixes comment block on trained models page

- docs/en/glossary/glossary.asciidoc
- docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
- docs/en/stack/ml/get-started/ml-gs-next.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/66347
> [DOCS] Deprecate anomaly detection post data endpoint

- docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
- docs/en/stack/ml/get-started/ml-gs-next.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1499
> [7.x][DOCS] Deprecate anomaly detection post data endpoint (#1499)

- docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1498
> [7.x][DOCS] Updates guide to exporting/importing models (#1498)

- docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1498
> [7.11][DOCS] Updates guide to exporting/importing models (#1498)

- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
This PR adds a brief summary of supervised and unsupervised machine learning to the "getting started with machine learning" tutorial.
> [DOCS] Add machine learning overview to tutorial

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Backport https://github.com/elastic/stack-docs/pull/1510
> [7.x][DOCS] Fixes branch in path to module (#1510)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1510
> [7.11][DOCS] Fixes branch in path to module (#1510)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1510
> [7.10][DOCS] Fixes branch in path to module (#1510)

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
Reuses the Elasticsearch highlights and breaking changes for 7.11
> [DOCS] Reuse ES 7.11 highlights and breaking changes

- docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1503
> [7.x][DOCS] Add space limitations for ML objects (#1503)

- docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1503
> [7.11][DOCS] Add space limitations for ML objects (#1503)

- docs/en/install-upgrade/breaking.asciidoc
This PR uncomments the Kibana breaking changes from the Installation and Upgrade Guide.
> [DOCS] Add Kibana breaking changes to Install Upgrade Guide

- docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
This PR expands the conceptual docs of hyperparameters about how the importance of optimized hyperparameters is calculated.
[Calculating the importance of hyperparameters](https://stack-docs_1522.docs-preview.app.elstc.co/guide/en/machine-learning/master/hyperparameters.html#hyperparameter-importance)
> [DOCS] Expands hyperparameters conceptual docs

- docs/en/stack/ml/df-analytics/hyperparameters.asciidoc
- [DOCS] Expands hyperparameters conceptual docs (#1522)
> [7.x] [DOCS] Expands hyperparameters conceptual docs (#1522)

- docs/en/install-upgrade/upgrading-stack.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1527
> [7.x][DOCS] Remove unnecessary license details

- docs/en/install-upgrade/upgrading-stack.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1527
> [7.11][DOCS] Remove unnecessary license details

- docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1528
> [7.11][DOCS] Add known issue for zero memory on Debian 8 (#1528)

- docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1528
> [7.10][DOCS] Add known issue for zero memory on Debian 8 (#1528)

- docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1528
> [6.8][DOCS] Add known issue for zero memory on Debian 8

- docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1548
> [7.x][DOCS] Update ML link for ES #68051 (#1548)

- docs/en/install-upgrade/upgrading-stack.asciidoc
Preview: https://stack-docs_1551.docs-preview.app.elstc.co/guide/en/elastic-stack/master/upgrading-elastic-stack.html
> [DOCS] Add the HLRC to the list. Closes #1550

- docs/en/install-upgrade/upgrading-stack.asciidoc
* [DOCS] Add the HLRC to the list. Closes #1550
* Fix formatting
* Edits
> [DOCS] Add the HLRC to the list. Closes #1550 (#1551)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1504
> [7.x][DOCS] Adds security_linux and security_windows modules (#1504)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1504
> [7.11][DOCS] Adds security_linux and security_windows modules (#1504)

- docs/en/install-upgrade/breaking.asciidoc
Must be merged after https://github.com/elastic/beats/pull/23943.
Also removes the coming tags (since I had the file open anyhow).
> Add Beats breaking changes to installation and upgrade guide

- docs/en/glossary/glossary.asciidoc
Relates to https://github.com/elastic/elasticsearch/pull/68938
> [DOCS] Add EQL glossary def

- docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
This PR splits the steps within https://www.elastic.co/guide/en/machine-learning/7.11/ml-troubleshooting.html#ml-troubleshooting-mappings, since otherwise they can be run as bulk requests and cause additional problems.
https://stack-docs_1572.docs-preview.app.elstc.co/guide/en/machine-learning/7.x/ml-troubleshooting.html
> [DOCS] Address feedback on ML troubleshooting

- docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1572
> [7.11][DOCS] Address feedback on ML troubleshooting (#1572)

- docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1572
> [7.10][DOCS] Address feedback on ML troubleshooting (#1572)

- docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
backports https://github.com/elastic/stack-docs/pull/1572
> [7.9][DOCS] Address feedback on ML troubleshooting (#1572)

- docs/en/stack/ml/df-analytics/ml-dfa-feature-processors.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1581
> [7.x][DOCS] Fixes n-gram terminology (#1581)

- docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
- docs/en/stack/ml/anomaly-detection/index.asciidoc
- [DOCS] Adds anomaly detection alert config docs to ML book (#1573)
> [7.12] [DOCS] Adds anomaly detection alert config docs to ML book (#1573)

- docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1590
> [7.x][DOCS] Link to preview data frame analytics API (#1590)

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1597
> [7.x][DOCS] Adds operator privileges to ML setup (#1597)

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1597
> [7.12][DOCS] Adds operator privileges to ML setup (#1597)

- docs/en/glossary/glossary.asciidoc
This PR pulls the new "rule" and "Rules and Connectors" terms into the glossary. It must be merged after https://github.com/elastic/kibana/pull/94447
> [DOCS] Add new alerting terms to glossary

- docs/en/install-upgrade/breaking.asciidoc
Updates the link to the Kibana breaking changes.
> Updates Kibana breaking changes link

- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Reorganizes DFA limitations (#1607)
> [7.x] [DOCS] Reorganizes DFA limitations (#1607)

- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Reorganizes DFA limitations (#1607)
> [7.12] [DOCS] Reorganizes DFA limitations (#1607)

- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Reorganizes DFA limitations (#1607)
> [7.11] [DOCS] Reorganizes DFA limitations (#1607)

- docs/en/stack/ml/setup.asciidoc
https://github.com/elastic/kibana/pull/95190 updates File Data Visualizer permissions. This PR updates the corresponding ML docs.
> Update file upload privileges documenation

- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1638
> [7.x][ML] Adds link to anomaly detection video (#1638)

- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1638
> [7.12][ML] Adds link to anomaly detection video (#1638)

- docs/en/install-upgrade/upgrading-stack.asciidoc
This PR adds Elastic Agent content to the upgrade topic.
> [DOCS] Add Elastic agent upgrade link and note

- docs/en/install-upgrade/upgrading-stack.asciidoc
> [7.x] Add agent content (#1672)

- docs/en/install-upgrade/upgrading-stack.asciidoc
> [7.13] Add agent content (#1672)

- docs/en/install-upgrade/breaking.asciidoc
Activates the include for the section about Beats breaking changes.
> Add Beats BCs for 7.13

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1680
> [7.x][DOCS] Adds ML security network modules (#1680)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1680
> [7.13][DOCS] Adds ML security network modules (#1680)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1681
> [7.x][DOCS] Update list of Apache and Nginx ML modules (#1681)

- docs/en/stack/page_header.html
> [7.3][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [7.2][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [7.1][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [7.0][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [6.8][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [6.7][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [6.6][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [6.5][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [6.4][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/page_header.html
> [6.3][DOCS] Add legacy header for Stack Overview (#1701)

- docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1699
> [7.x][DOCS] Adds ML document metadata (#1699)

- docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1699
> [7.13][DOCS] Adds ML document metadata (#1699)

- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Adds nested fields related item to DFA limitations (#1714)
> [7.x] [DOCS] Adds nested fields related item to DFA limitations (#1714)

- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Adds nested fields related item to DFA limitations (#1714)
> [7.13] [DOCS] Adds nested fields related item to DFA limitations (#1714)

- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Adds nested fields related item to DFA limitations (#1714)
> [7.12] [DOCS] Adds nested fields related item to DFA limitations (#1714)

- docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Adds nested fields related item to DFA limitations (#1714)
> [7.11] [DOCS] Adds nested fields related item to DFA limitations (#1714)

- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
- docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
- docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
- docs/en/stack/ml/get-started/ml-gs-next.asciidoc
- docs/en/stack/ml/get-started/ml-gs-results.asciidoc
- docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
- docs/en/stack/ml/index.asciidoc
- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1728
> [7.x][DOCS] Adds chapter, removes part from ML guide (#1728)

- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
- docs/en/stack/ml/get-started/ml-gs-forecasts.asciidoc
- docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
- docs/en/stack/ml/get-started/ml-gs-next.asciidoc
- docs/en/stack/ml/get-started/ml-gs-results.asciidoc
- docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
- docs/en/stack/ml/index.asciidoc
- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1728
> [7.13][DOCS] Adds chapter, removes part from ML guide (#1728)

- docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1742
> [7.13][DOCS] Fixes links to Kibana sample data documentation (#1742)

- docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1742
> [7.14][DOCS] Fixes links to Kibana sample data documentation (#1742)

- docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
Backport https://github.com/elastic/stack-docs/pull/1742
> [7.x][DOCS] Fixes links to Kibana sample data documentation (#1742)

- docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
This PR adds info about job validation to examples.
> [7.x][DOCS] Adds sentence about job validation to examples

- docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
This PR backports the changes of the following commits to the 7.14 branch:
[7.x][DOCS] Adds sentence about job validation to examples #1741
> [7.14][DOCS] Adds sentence about job validation to examples

- docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
- docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
This PR backports the changes of the following commits to the 7.13 branch:
[7.x][DOCS] Adds sentence about job validation to examples #1741
> [7.13][DOCS] Adds sentence about job validation to examples

- docs/en/install-upgrade/breaking.asciidoc
Updates the Kibana breaking changes links.
> [DOCS] Updates Kibana breaking changes

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/highlights.asciidoc
> [DOCS] Remove coming tags from breaking changes + release highlights (#1776)

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1719
> [7.x][DOCS] Update file data visualizer permissions (#1719)

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1719
> [7.14][DOCS] Update file data visualizer permissions (#1719)

- docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
As title states.
[DFA overview](https://stack-docs_1785.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-overview.html)
> Fixes a bulleted list in DFA overview

- docs/en/stack/ml/setup.asciidoc
This PR replaces the File Data Visualizer term with the more generic "Data Visualizer".
> [DOCS] Removes File Data Visualizer term

- docs/en/stack/ml/setup.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1786
> [7.x][DOCS] Removes File Data Visualizer term

- docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc
- docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
- docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1793
> [7.x][DOCS] Update datafeed details in ML docs (#1793)

- docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc
- docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
- docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1793
> [7.15][DOCS] Update datafeed details in ML docs (#1793)

- docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
- docs/en/stack/ml/move-jobs.asciidoc
Related to elastic/kibana#101037
* https://stack-docs_1792.docs-preview.app.elstc.co/guide/en/machine-learning/master/move-jobs.html
* https://stack-docs_1792.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-trained-models.html#export-import
> [DOCS] Import and export jobs

- docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
- docs/en/stack/ml/anomaly-detection/index.asciidoc
- docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
- docs/en/stack/ml/move-jobs.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1792
https://stack-docs_1791.docs-preview.app.elstc.co/guide/en/machine-learning/7.x/move-jobs.html
> [7.x][DOCS] Import and export jobs

- docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
This PR fixes some improper linebreaks and reduces the word number of the piece.
[Regression](https://stack-docs_1800.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-regression.html)
> [DOCS] Further edits regression conceptual docs

- docs/en/gke-on-prem/gke-on-prem-deploy-beats.asciidoc
- docs/en/siem/detections/machine-learning/machine-learning.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
- docs/en/stack/ml/get-started/ml-gs-jobs.asciidoc
- docs/en/stack/ml/get-started/ml-gs-visualizer.asciidoc
- docs/en/stack/ml/move-jobs.asciidoc
- docs/en/stack/ml/setup.asciidoc
Relates to https://github.com/elastic/kibana/pull/110421
This PR replaces occurrences of "index pattern" with the appropriate shared attribute from https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc
https://stack-docs_1799.docs-preview.app.elstc.co/diff
> [DOCS] Replaces index pattern with data view attribute

- docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1805
> [7.x][DOCS] Refreshes list of data frame analytics APIs

- docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1805
> [7.15][DOCS] Refreshes list of data frame analytics APIs (#1805)

- docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1805
> [7.14][DOCS] Refreshes list of data frame analytics APIs (#1805)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1814
> [7.x][DOCS] Clarifies rare security job details (#1814)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1814
> [7.15][DOCS] Clarifies rare security job details (#1814)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Relates to https://github.com/elastic/kibana/pull/101840 and https://github.com/elastic/stack-docs/issues/1794
https://stack-docs_1813.docs-preview.app.elstc.co/guide/en/security/master/prebuilt-ml-jobs.html#security-authentication
> [DOCS] Add security:authentication jobs

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1813
> [7.x][DOCS] Add security:authentication jobs (#1813)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1813
> [7.15][DOCS] Add security:authentication jobs (#1813)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1813
> [7.14][DOCS] Add security:authentication jobs (#1813)

- docs/en/install-upgrade/breaking.asciidoc
Depends on https://github.com/elastic/elasticsearch/pull/77971
> [DOCS] Add ES breaking changes section for ingest pipelines

- docs/en/install-upgrade/breaking.asciidoc
For https://github.com/elastic/apm-server/pull/6219/files.
> 7.15: Add APM breaking changes

- docs/en/install-upgrade/breaking.asciidoc
This PR fixes the breaking changes in the Installation and Upgrade Guide.
It must be merged after https://github.com/elastic/docs/pull/2225
> [DOCS] Fixes breaking changes

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1790
> [7.15] spelling fixd. (#1790)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1790
> [7.x] spelling fixd. (#1790)

- docs/en/install-upgrade/highlights.asciidoc
- docs/en/install-upgrade/redirects.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1830
> [7.15][DOCS] Fixes typos (#1830)

- docs/en/stack/ml/get-started/ml-gs-results.asciidoc
This PR adds a paragraph to the machine learning tutorial about the types of links you can find in the actions column of the anomaly detection results.
https://stack-docs_1835.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-gs-results.html#ml-gs-results-smv
> [DOCS] Add raw data to machine learning tutorial

- docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1835
> [7.x][DOCS] Add raw data to machine learning tutorial (#1835)

- docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1835
> [7.15][DOCS] Add raw data to machine learning tutorial (#1835)

- docs/en/install-upgrade/breaking.asciidoc
Depends on https://github.com/elastic/elasticsearch/pull/78277
> [DOCS] Add ES breaking changes section for Watcher

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
This PR updates the documentation of APM transaction jobs to reflect the changes introduced by https://github.com/elastic/kibana/pull/111957
[OOTB AD jobs – APM tranasactions](https://stack-docs_1842.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-apm.html#apm-transaction-jobs)
> Updates APM OOTB transaction job docs

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
- Updates APM OOTB transaction job docs (#1842)
> [7.x] Updates APM OOTB transaction job docs (#1842)

- docs/en/install-upgrade/breaking.asciidoc
Updates the ES breaking changes headings for elastic/elasticsearch#79162
> [DOCS] Update headings for ES 8.0 breaking changes

- docs/en/install-upgrade/breaking.asciidoc
Relates to https://github.com/elastic/elasticsearch/pull/80729
> [DOCS] Uncomment include statements for 8.0 ES breaking changes

- docs/en/install-upgrade/highlights.asciidoc
This PR fixes a broken link on https://www.elastic.co/guide/en/elastic-stack/7.16/elastic-stack-highlights.html
> [DOCS] Fixes broken link

- docs/en/install-upgrade/highlights.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1880
> [7.15][DOCS] Fixes broken link (#1880)

- docs/en/getting-started/get-started-stack.asciidoc
> [DOCS] Updating Stack getting started for security ON (#1883)

- docs/en/getting-started/get-started-stack.asciidoc
Added note about keeping ELK in this doc for SEO so this info doesn't get lost in the future.
> Add comment for maintainers to getting started docs

- docs/en/getting-started/get-started-stack.asciidoc
- docs/en/gke-on-prem/gke-on-prem-deploy-beats.asciidoc
This PR removes all links and references to Journalbeat, which is being removed in 7.16.
> Remove links and references to journalbeat

- docs/en/getting-started/get-started-stack.asciidoc
- docs/en/gke-on-prem/gke-on-prem-deploy-beats.asciidoc
- Remove links and references to journalbeat (#1893)
> [8.0] Remove links and references to journalbeat (#1893)

- docs/en/stack/ml/df-analytics/ml-dfa-shared.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1890
> [8.0][DOCS] Fix link to ingest pipelines (#1890)

- docs/en/stack/ml/df-analytics/ml-inference.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1890
> [7.16][DOCS] Fix link to ingest pipelines (#1890)

- docs/en/glossary/glossary.asciidoc
Updates the glossary xref for elastic/elasticsearch#79081
> [DOCS] Update xref for SLM definition

- docs/en/getting-started/docker/docker-compose.yml
- docs/en/getting-started/docker/elastic-docker-tls.yml
- docs/en/getting-started/docker/instances.yml
- docs/en/getting-started/get-started-docker.asciidoc
- docs/en/getting-started/index.asciidoc
- docs/en/getting-started/redirects.asciidoc
> [DOCS] Update Docker getting started for the Stack (#1888)

- docs/en/stack/ml/df-analytics/index.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
- docs/en/stack/ml/index.asciidoc
- docs/en/stack/ml/nlp/index.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-apis.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
- docs/en/stack/ml/nlp/ml-nlp.asciidoc
- docs/en/stack/ml/redirects.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1903
> [8.0][DOCS] Adds NLP folders to ML Guide (#1903)

- docs/en/stack/ml/nlp/index.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
- docs/en/stack/ml/nlp/ml-nlp.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1905
> [8.0][DOCS] Draft NLP model deployment (#1905)

- docs/en/stack/ml/nlp/index.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-search-compare.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1914
> [8.0] Drafts Search and compare section for NLP docs (#1914)

- docs/en/getting-started/get-started-docker.asciidoc
> [DOCS] Add section for enrolling new nodes on Docker (#1922)

- docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1918
> [8.0][DOCS] Add language identification model details (#1918)

- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
I compared the upgrade steps against the Cloud UI, and there were just a few minor things to fix up.
> Minor fixup for Cloud upgrade steps

- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Manually generated backport for #1932 to 8.0
> [Backport] [8.0] [1932]Minor fixup for Cloud upgrade steps

- docs/en/stack/ml/get-started/ml-gs-results.asciidoc
👋🏼 Explicates for search discoverability purposes that our "bounds" terminology is the 95% central confidence interval
> [DOC] explicate confidence interval on single metrics viewer

- docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1930
> [8.0][DOC] explicate confidence interval on single metrics viewer (#1930)

- docs/en/stack/ml/get-started/ml-gs-results.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1930
> [7.17][DOC] explicate confidence interval on single metrics viewer (#1930)

- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
This addresses feedback I received on the Cloud Upgrade docs for 8.0.
> Address comments from Cloud upgrade docs review

- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Manually generated backport for #1939 to 8.0
> [Backport] [8.0] [1939]Address comments from Cloud upgrade docs review

- docs/en/stack/ml/anomaly-detection/ml-ad-overview.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1945
> [8.0] Revert anomaly detection part to chapter (#1945)

- docs/en/install-upgrade/highlights.asciidoc
This PR updates [Kibana highlights](https://www.elastic.co/guide/en/elastic-stack/7.17/kibana-highlights.html) in the Installation and Upgrade Guide.
> [DOCS] Update Kibana 7.17 highlights

- docs/en/install-upgrade/breaking.asciidoc
Merge after https://github.com/elastic/beats/issues/30114.
> Activate Beats breaking changes include

- docs/en/install-upgrade/index.asciidoc
- docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
- docs/en/install-upgrade/upgrading-kibana.asciidoc
- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
- docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc
- docs/en/install-upgrade/upgrading-stack.asciidoc
8.0 upgrade: https://stack-docs_1970.docs-preview.app.elstc.co/guide/en/elastic-stack/8.0/upgrading-elastic-stack.html
Cloud upgrade: https://stack-docs_1970.docs-preview.app.elstc.co/guide/en/elastic-stack/8.0/upgrade-elastic-stack-for-elastic-cloud.html
On-prem upgrade: https://stack-docs_1970.docs-preview.app.elstc.co/guide/en/elastic-stack/8.0/upgrading-elastic-stack-on-prem.html
Elasticsearch upgrade: https://stack-docs_1970.docs-preview.app.elstc.co/guide/en/elastic-stack/8.0/upgrading-elasticsearch.html
Kibana upgrade: https://stack-docs_1970.docs-preview.app.elstc.co/guide/en/elastic-stack/8.0/upgrading-kibana.html
> [DOCS] Consolidated upgrade info

- docs/en/install-upgrade/index.asciidoc
- docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
- docs/en/install-upgrade/upgrading-kibana.asciidoc
- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
- docs/en/install-upgrade/upgrading-stack-on-prem.asciidoc
- docs/en/install-upgrade/upgrading-stack.asciidoc
* [DOCS] Consolidated upgrade info
* Updated ES instructions to sync with ES changes.
* Incorporated review feedback
* Update docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Co-authored-by: gchaps <33642766+gchaps@users.noreply.github.com>
* Edits
* Update docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
* Apply suggestions from code review
Co-authored-by: gchaps <33642766+gchaps@users.noreply.github.com>
* Update docs/en/install-upgrade/upgrading-kibana.asciidoc
* Update docs/en/install-upgrade/upgrading-stack.asciidoc
* Update docs/en/install-upgrade/upgrading-kibana.asciidoc
* Update docs/en/install-upgrade/upgrading-elasticsearch.asciidoc
* Apply suggestions from code review
* Update docs/en/install-upgrade/upgrading-kibana.asciidoc
Co-authored-by: gchaps …
> [DOCS] Consolidated upgrade info (#1970)

- docs/en/install-upgrade/upgrading-kibana.asciidoc
Updated link to fix cross doc error in Kibana PR.
> [DOCS] Updated link to Kibana

- docs/en/install-upgrade/upgrading-stack.asciidoc
Relates to https://github.com/elastic/stack-docs/pull/1983
> Re-add link to API compat topic

- docs/en/glossary/glossary.asciidoc
- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
- docs/en/install-upgrade/upgrading-stack.asciidoc
This is an automatic backport to `main` of:
- #1990
> [main] [DOCS] Link to the 7.17 upgrade assistant docs (#1990)

- docs/en/glossary/glossary.asciidoc
- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
- docs/en/install-upgrade/upgrading-stack.asciidoc
This is an automatic backport to `8.1` of:
- #1990
> [8.1] [DOCS] Link to the 7.17 upgrade assistant docs (#1990)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1994
> [8.1][DOCS] Restructure Auditbeat jobs in tables (#1994)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1994
> [8.0][DOCS] Restructure Auditbeat jobs in tables (#1994)

- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1998
> [8.1][DOCS] Update upgrading-stack-cloud.asciidoc (#1998)

- docs/en/install-upgrade/upgrading-stack-cloud.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1998
> [8.0][DOCS] Update upgrading-stack-cloud.asciidoc (#1998)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1999
> [8.1][DOCS] Restructures log jobs in table (#1999)

- docs/en/install-upgrade/upgrading-kibana.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1997
> [8.1][DOCS] Update upgrading-kibana.asciidoc (#1997)

- docs/en/install-upgrade/upgrading-kibana.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1997
> [8.0][DOCS] Update upgrading-kibana.asciidoc (#1997)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1999
> [8.0][DOCS] Restructures log jobs in table (#1999)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2006
> [8.1][DOCS] Restructures Metrics jobs in table (#2006)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metrics-ui.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2006
> [8.0][DOCS] Restructures Metrics jobs in table (#2006)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2002
> [8.0][DOCS] Restructures Metricbeat jobs in table (#2002)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2009
> [8.1][DOCS] Restructures Nginx jobs in table

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2009
> [8.0][DOCS] Restructures Nginx jobs in table

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2012
> [8.1][DOCS] Restructures Uptime jobs in table (#2012)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2012
> [8.0][DOCS] Restructures Uptime jobs in table (#2012)

- docs/en/install-upgrade/breaking.asciidoc
Updates the breaking changes links for 8.0.0.
> [DOCS] Fixes Kibana 8.0.0 breaking changes

- docs/en/getting-started/get-started-stack.asciidoc
Fixes related to https://github.com/elastic/observability-docs/issues/1544
> Remove Homebrew instructions from getting started docs

- docs/en/install-upgrade/upgrading-stack.asciidoc
This is an automatic backport to `8.1` of:
- #2024
> [8.1] [DOCS] Re-add anchor for stack upgrade order (#2024)

- docs/en/install-upgrade/upgrading-stack.asciidoc
This is an automatic backport to `8.0` of:
- #2024
> [8.0] [DOCS] Re-add anchor for stack upgrade order (#2024)

- docs/en/install-upgrade/upgrading-kibana.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2031
> [8.0][DOCS] Omit link to logging config changes

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1955
> [8.1][DOCS] Restructures reference for preconfigured security jobs (#1955)

- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Backports https://github.com/elastic/stack-docs/pull/1955
> [8.0][DOCS] Restructures reference for preconfigured security jobs (#1955)

- docs/en/install-upgrade/upgrading-kibana.asciidoc
This PR updates links to the the Kibana docs
> [8.0] Update upgrading-kibana.asciidoc

- README.md
This PR adds more information in the readme for the stack-docs repo, modelled on the excellent https://github.com/elastic/observability-docs/blob/main/README.md
> Augments the readme

- README.md
Backports https://github.com/elastic/stack-docs/pull/2047
> [8.1] Augments the readme (#2047)

- README.md
Backports https://github.com/elastic/stack-docs/pull/2047
> [8.0] Augments the readme (#2047)

- docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2050
> [8.1][DOCS] Fix links to ML APIs (#2050)

- docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2050
> [8.0][DOCS] Fix links to ML APIs (#2050)

- docs/en/getting-started/get-started-stack.asciidoc
Cherry-picks changes from https://github.com/elastic/stack-docs/pull/1973
> [DOCS] Minor typos on get-started-stack.asciidoc (#1973)

- docs/en/install-upgrade/breaking.asciidoc
Do not merge until after https://github.com/elastic/beats/pull/30695
The build will fail until this ^^ PR is merged.
> Add Beats breaking changes to Installation and Upgrade Guide for 8.1

- docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
Relates to: https://github.com/elastic/elasticsearch/pull/84777
> add roberta & bart support and example models

- docs/en/install-upgrade/upgrading-stack.asciidoc
Forward-fits https://github.com/elastic/stack-docs/pull/2092
> [8.3] Update upgrading-stack.asciidoc (#2092)

- docs/en/install-upgrade/upgrading-stack.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2092
> [8.0] Update upgrading-stack.asciidoc (#2092)

- docs/en/install-upgrade/upgrading-stack.asciidoc
Forward-fits https://github.com/elastic/stack-docs/pull/2092
> [8.2] Update upgrading-stack.asciidoc (#2092)

- docs/en/install-upgrade/breaking.asciidoc
This PR comments out some links in the Installation and Upgrade Guide which are seeking 8.2 highlights and breaking changes that don't yet exist.
> [DOCS] Comment out incomplete 8.2 links

- docs/en/install-upgrade/breaking.asciidoc
Relates to https://github.com/elastic/elasticsearch/pull/85965
> [DOCs] Uncomment Elasticsearch breaking changes

- docs/en/install-upgrade/breaking.asciidoc
For https://github.com/elastic/apm-server/pull/7956.
> [8.2] Update APM tagged region

- docs/en/install-upgrade/breaking.asciidoc
For https://github.com/elastic/apm-server/pull/7478.
> [8.1] Update APM tagged region

- docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
https://stack-docs_2153.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-model-ref.html
> Add Farsi NER model to list of supported NLP models

- docs/en/glossary/glossary.asciidoc
- docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc
- docs/en/stack/ml/anomaly-detection/geographic-anomalies.asciidoc
- docs/en/stack/ml/anomaly-detection/mapping-anomalies.asciidoc
- docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
- docs/en/stack/ml/df-analytics/ml-trained-models.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
This PR addresses some of the typos found by the linting project.
> [DOCS] Address linting issues

- docs/en/glossary/glossary.asciidoc
Related to https://github.com/elastic/observability-docs/pull/1977.
> Update definition of Elastic Agent

- docs/en/stack/ml/nlp/ml-nlp.asciidoc
Relates to https://github.com/elastic/elasticsearch/pull/90418
> [DOCS] Change inference functionality to beta

- docs/en/stack/ml/nlp/ml-nlp.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2234
> [8.5][DOCS] Change inference functionality to beta (#2234)

- docs/en/install-upgrade/breaking.asciidoc
Do not merge until after https://github.com/elastic/beats/pull/33376 is merged.
@lcawl Are you still the best person to review PRs like this, or should I just ask someone on my team?
> Update beats BC include for 8.5

- docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
This PR adjusts the sections that describe the used algorithms for regression and classification to make them more accurate.
> Adjusts the description of regression and classification algorithms

- docs/en/getting-started/index.asciidoc
- docs/en/stack/ml/anomaly-detection/anomaly-how-tos.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-regression-loss-functions.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
- docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
- docs/en/stack/ml/index.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-inference.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-lang-ident.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
This PR removes unused and duplicate attributes (if they already exist in https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc) and uses the shared attributes in pages in this repo.
> [DOCS] Synch or remove shared attributes

- docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
> [8.8][DOCS] Removes unnecessary section ID from NLP model deployment page

- docs/en/stack/ml/anomaly-detection/ml-ad-explain.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-ad-finding-anomalies.asciidoc
- docs/en/stack/ml/anomaly-detection/ml-ad-job-types.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-classification.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-outlier-detection.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
- docs/en/stack/ml/df-analytics/ml-dfa-regression.asciidoc
- docs/en/stack/ml/df-analytics/ml-how-dfa-works.asciidoc
- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
- docs/en/stack/ml/machine-learning-intro.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-classify-text.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-extract-info.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
- docs/en/stack/ml/nlp/ml-nlp.asciidoc
Backports https://github.com/elastic/stack-docs/pull/2402
> [8.8][DOCS] Add frontmatter for migration (#2402)

- docs/en/siem/cases/api/actions-api/cases-actions-api-intro.asciidoc
Fixes https://github.com/elastic/platform-docs-team/issues/62.
> Removes sensitive information.

- docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
> Fixes indentation on third party models page

- docs/en/stack/ml/nlp/ml-nlp-text-emb-vector-search-example.asciidoc
> [DOCS] Fixes typo on text embedding page

- docs/en/install-upgrade/breaking.asciidoc
This PR comments out some breaking change references for which the source files don't exist yet and uncomments some links that are ready.
> [DOCS] Update breaking changes links

- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
> Fixes typo in benchmark section anchor

- docs/en/install-upgrade/upgrading-stack.asciidoc
Addressing https://github.com/elastic/sdh-beats/issues/3175
> a small correction ins the upgrade process.

- docs/en/install-upgrade/breaking.asciidoc
- docs/en/install-upgrade/index.asciidoc
Partially revert after APM Server PRs are merged. Keep changes to `docs/en/install-upgrade/index.asciidoc`.
> Temporarily comment out include statement

- docs/en/install-upgrade/breaking.asciidoc
This reverts commit dbb169d03b318b8cd389f75fadb7378ba4d8bfd4.
> [8.1] Revert "docs: temp comment out include (#2633)"

- docs/en/install-upgrade/breaking.asciidoc
This reverts commit fdcce3502fe3e77414b27f8089d4a727c89fb370.
> [8.4] Revert "docs: temp comment out include (#2630)"

- docs/en/install-upgrade/breaking.asciidoc
This reverts commit 879418f85dcef686a1f4682c33231587a6383f52.
> [8.3] Revert "docs: temp comment out include (#2632)"

- docs/en/stack/ml/nlp/ml-nlp-overview.asciidoc
Found this minor typo while reading the ML docs.
> Fixed typo

- docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR forwardport the changes of the following PR to the `8.14` branch:
Update ml-limitations.asciidoc #2713
> [8.14] [Backport] Update ml-limitations.asciidoc (#2713)

- docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc
This PR forwardport the changes of the following PR to the `main` branch:
Update ml-limitations.asciidoc #2713
> [Forwardport] Update ml-limitations.asciidoc (#2713)

- docs/en/stack/ml/nlp/ml-nlp-deploy-models.asciidoc
This PR forward-ports the following changes to the `main` branch: Update ml-nlp-deploy-models.asciidoc #2738
> Update ml-nlp-deploy-models.asciidoc (#2738)

- docs/en/stack/ml/get-started/ml-getting-started.asciidoc
> Fixes typo in ML getting started

- docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
As title states.
[ELSER - Download](https://stack-docs_bk_2750.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html#download-deploy-elser)
[E5 - Download](https://stack-docs_bk_2750.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-e5.html#download-deploy-e5)
> [DOCS] Adds a note that the intel and linux optimized versions of ELSER and E5 are recommended

- docs/en/stack/ml/nlp/ml-nlp-e5.asciidoc
Docs component of https://github.com/elastic/ml-team/issues/1320
How far back should we backport?
> [DOCS] [URGENT] Update e5 warranty verbiage

- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
> Removes dead link from ELSER page

- docs/en/stack/ml/nlp/ml-nlp-model-ref.asciidoc
making sure links are bidirectional with the [the semantic reranking docs page](https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-reranking.html#semantic-reranking-in-es)
> Add link to semantic re-ranking in model ref

- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
- docs/en/stack/ml/nlp/ml-nlp.asciidoc
This PR improves the ELSER recommendations section on the ELSER docs page.
> Improves ELSER recommendations

- docs/en/stack/ml/nlp/ml-nlp-autoscaling.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
This PR improves the trained model autoscaling documentation based on @linyaru feedback.
[ELSER recommendations](https://stack-docs_bk_2857.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-elser.html#elser-recommendations)
[Trained model autoscaling](https://stack-docs_bk_2857.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-nlp-auto-scale.html)
> Improves trained model autoscaling docs

- docs/en/stack/ml/nlp/ml-nlp-autoscaling.asciidoc
- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
> Fixes typo in autoscaling docs

- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Does what it says on tin
cc @linyaru
> Update "Download and deploy ELSER" snippet with adaptive allocations

- docs/en/stack/ml/nlp/ml-nlp-limitations.asciidoc
https://github.com/elastic/elasticsearch/issues/116022
> [ML] Add ML limitation for ingesting large documents

- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
> [DOCS] Fixes a config line in ELSER docs

- docs/en/stack/ml/anomaly-detection/anomaly-detection-scale.asciidoc
> Language Error

- docs/en/install-upgrade/release-notes/release-notes-kibana.asciidoc
This PR adds release notes for Kibana 9.0.0-beta1
Those are the items currently retrieved by the automation, to which I made some minor consistency edits. Please check that what's relevant for you is correct and communicated properly, and flag anything missing.
Thank you all!
Preview here: https://stack-docs_bk_2959.docs-preview.app.elstc.co/guide/en/elastic-stack/9.0/release-notes-kibana-9.0.0-beta1.html
> Kibana release notes for 9.0.0-beta1

- docs/en/install-upgrade/release-notes/release-notes-kibana-rc1.asciidoc
> Unique ID fix

- docs/en/install-upgrade/serverless-changelog.asciidoc
> Mention semantic_text going GA in serverless changelog

- docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
Removing extra comma from code sample.
> Correct code sample

- docs/en/install-upgrade/upgrading-stack.asciidoc
Call out specifically to look for cluster stability, performance, and
snapshot repository bugs.
> Expand guidance on testing an upgrade (#3009)
