x-pack/docs/en/monitoring/production.asciidoc
This PR removes outdated information related to installing X-Pack in the "Monitoring in a production environment" page.
=> [DOCS] Removes X-Pack installation info

x-pack/docs/en/index.asciidoc, x-pack/docs/en/xpack-limitations.asciidoc, x-pack/docs/en/xpack-troubleshooting.asciidoc
This PR fixes the "edit" links, which were failing to locate the files in the elasticsearch and kibana repos.
=> [DOCS] Fixes edit links

docs/installing-stack.asciidoc, docs/upgrading-stack.asciidoc
This PR fixes the following broken links in the documentation build:
17:07:17 Bad cross-document links:
17:07:17   html/en/elastic-stack/5.6/installing-elastic-stack.html:
17:07:17    - en/cloud/current/getting-started.html
17:07:17   html/en/elastic-stack/5.6/upgrading-elastic-stack.html:
17:07:17    - en/cloud/current/cluster-config.html
17:07:17    - en/cloud/current/upgrading.html
=> [DOCS] Fixes broken links to Cloud docs

docs/en/stack/index.asciidoc, docs/en/stack/security/authentication/active-directory-realm.asciidoc, docs/en/stack/security/authentication/built-in-users.asciidoc, docs/en/stack/security/authentication/custom-realm.asciidoc, docs/en/stack/security/authentication/file-realm.asciidoc, docs/en/stack/security/authentication/internal-users.asciidoc, docs/en/stack/security/authentication/ldap-realm.asciidoc, docs/en/stack/security/authentication/native-realm.asciidoc, docs/en/stack/security/authentication/overview.asciidoc, docs/en/stack/security/authentication/pki-realm.asciidoc, docs/en/stack/security/authentication/realms.asciidoc, docs/en/stack/security/authentication/saml-realm.asciidoc, docs/en/stack/security/getting-started.asciidoc, docs/en/stack/security/how-security-works.asciidoc, docs/en/stack/security/index.asciidoc
This PR moves the source files for https://www.elastic.co/guide/en/elastic-stack-overview/master/setting-up-authentication.html to the stack-docs repo.
This conceptual content is not tied as closely to the code as other pages in the elasticsearch repo, so it makes sense to move it to where the Stack Overview book is built.
=> [DOCS] Moves authentication overview to stack-docs

docs/installing-stack.asciidoc
The content from installing-beats.html is now available in getting-started.html (it's basically just a set of links to the GS guides for all the Beats.
=> Fix broken link

docs/en/stack/getting-started/get-started-stack.asciidoc
This PR clarifies two points that caused confusion in the Stack Overview Getting Started tutorial related to starting Logstash.
=> [DOCS] Clarifies Logstash gotchas

docs/en/stack/security/authorization/document-level-security.asciidoc, docs/en/stack/security/authorization/field-level-security.asciidoc, docs/en/stack/security/authorization/index.asciidoc
This PR splits off separate overview pages for field-level security and document-level security and moves them higher in the table of contents. 
It also adds code snippet testing for the examples. 
This content had previously been rather buried in this long page:
https://www.elastic.co/guide/en/elastic-stack-overview/master/field-and-document-access-control.html#field-level-security
https://www.elastic.co/guide/en/elastic-stack-overview/master/field-and-document-access-control.html#document-level-security
=> [DOCS] Creates field and document level security overview

docs/en/stack/license.asciidoc
This PR updates the License Management page in the Stack Overview (https://www.elastic.co/guide/en/elastic-stack-overview/master/license-management.html).
In general, we should keep the licensing details to a minimum in the docs and instead refer to the elastic.co/subscriptions page.
Related to https://github.com/elastic/kibana/pull/20316 and https://github.com/elastic/elasticsearch/pull/31667
=> [DOCS] Clarified license management

docs/en/stack/security/authorization/built-in-roles.asciidoc
This role is require for Beats central management and was added to X-Pack Elasticsearch as part of https://github.com/elastic/elasticsearch/pull/30520.
=> Documents built-in `beats_admin` role

docs/en/stack/ml/getting-started-data.asciidoc, docs/en/stack/ml/getting-started-multi.asciidoc, docs/en/stack/ml/getting-started-single.asciidoc, docs/en/stack/ml/getting-started-wizards.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/31541
This PR updates the machine learning tutorial to use alternative scripts (https://github.com/elastic/machine-learning-utils/pull/61) when security is not enabled. It also removes unnecessary comments about logging into Kibana.
=> [DOCS] Update ML tutorial for when security is not enabled

docs/en/stack/monitoring/troubleshooting.asciidoc, docs/en/stack/troubleshooting.asciidoc
This PR copies the content of https://github.com/elastic/kibana/blob/master/docs/monitoring/monitoring-troubleshooting.asciidoc to this repo for use in the Stack Overview.
=> [DOCS] Moves monitor troubleshooting content kibana repo

docs/60_upgrade_guide.html, docs/upgrading-stack.asciidoc
- Removed ref to installing X-Pack in Logstash in the interactive guide.
- Added step for removing old X-Pack plugin in the interactive guide & docs.
- Added step for enabling data collection for monitoring to the interactive guide & made it clear that you always need to enable data collection after upgrade.
=> Corrected upgrade steps in the interactive guide & stack upgrade doc.

docs/en/stack/index.asciidoc
This PR updates the version information in the 6.x Stack Overview.
Related to https://github.com/elastic/docs/pull/398
=> [DOCS] Updates version information

docs/en/stack/ml/getting-started-multi.asciidoc, docs/en/stack/ml/getting-started-single.asciidoc
This PR addresses some confusion about where to obtain the create_single_metric.sh, create_single_metric_noauth.sh, create_multi_metric.sh, and create_multi_metric_noauth.sh scripts. It adds links to the page where we describe how to download and extract the server_metrics.tar.gz (which contains these scripts).
=> [DOCS] Adds link for ML getting started scripts

docs/en/stack/ml/rules.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/32785
=> [DOCS] Refer to rules feature as custom rules

docs/en/stack/security/authorization/built-in-roles.asciidoc
Changing the descriptions of the `kibana_user` and `kibana_dashboard_only_user` roles to no longer reference giving direct access to the Kibana index, as this isn't necessarily true any longer given the changes discussed [here](https://github.com/elastic/kibana/pull/21178/files#diff-842ecf04b8ee3030ff5611b2030f69d4).
=> Adding RBAC Phase 1 Docs

docs/en/stack/security/authentication/ldap-realm.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/32797
This PR fixes a broken link to the role mapping APIs.
=> [DOCS] Updates link to role mapping API

docs/en/stack/security/authorization/privileges.asciidoc
This PR adds an introduction to the concept of application privileges in the Stack Overview. In particular, it updates the "Security privileges" page: https://www.elastic.co/guide/en/elastic-stack-overview/master/security-privileges.html
NOTE: This PR contains links to content that is added by https://github.com/elastic/elasticsearch/pull/32635
=> [DOCS] Adds overview of application privileges

docs/en/stack/index.asciidoc, docs/en/stack/ml/api-quickref.asciidoc, docs/en/stack/ml/index.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/30665 and https://github.com/elastic/elasticsearch/pull/33248
This PR updates the Stack Overview to use appropriate links to the new location of the machine learning content in the elasticsearch repo.
=> [DOCS] Updates location of ML pages

docs/en/getting-started/get-started-docker.asciidoc, docs/en/getting-started/get-started-kubernetes.asciidoc, docs/en/getting-started/index.asciidoc
Related to https://github.com/elastic/stack-docs/issues/108
This PR creates placeholder pages for Docker and Kubernetes, which currently just link to the existing documentation.
=> [DOCS] Adds placeholders for Docker and Kubernetes pages

docs/en/stack/ml/api-quickref.asciidoc
There is a duplication of content between the list of machine learning APIs in the Stack Overview (https://www.elastic.co/guide/en/elastic-stack-overview/master/ml-api-quickref.html) and the Elasticsearch Reference (https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-apis.html)
There are also endpoints missing from the former. 
The information in the Elasticsearch Reference should be the source of truth. This PR removes the  duplicated information from the Stack Overview and points to the appropriate pages in the Elasticsearch Reference.
=> [DOCS] Remove duplicated API info

docs/en/stack/security/authentication/built-in-users.asciidoc, docs/en/stack/security/authorization/built-in-roles.asciidoc, docs/en/stack/security/get-started-builtin-users.asciidoc, docs/en/stack/security/get-started-security.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/32515
This PR adds information about the apm_system builtin user and role to the Stack Overview.
=> [DOCS] Adds apm_system user and role

docs/en/stack/security/troubleshooting.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/33688 and https://github.com/elastic/elasticsearch/pull/33541
This PR adds information to the troubleshooting section of the Stack Overview.
=> [DOCS] Add security troubleshooting item

docs/upgrading-stack.asciidoc
This PR fixes the following broken links:
> 14:41:18 Bad cross-document links:
> 14:41:18   html/en/elastic-stack/5.0/upgrading-elastic-stack.html:
> 14:41:18    - en/cloud/current/ec-upgrading.html
> 14:41:18   html/en/elastic-stack/5.1/upgrading-elastic-stack.html:
> 14:41:18    - en/cloud/current/ec-upgrading.html
> 14:41:18   html/en/elastic-stack/5.2/upgrading-elastic-stack.html:
> 14:41:18    - en/cloud/current/ec-upgrading.html
> 14:41:18   html/en/elastic-stack/5.3/upgrading-elastic-stack.html:
> 14:41:18    - en/cloud/current/ec-upgrading.html
> 14:41:18   html/en/elastic-stack/5.4/upgrading-elastic-stack.html:
> 14:41:18    - en/cloud/current/ec-upgrading.html
> 14:41:18   html/en/elastic-stack/5.5/upgrading-elastic-stack.html:
> 14:41:18    - en/cloud/current/ec-upgrading.html …
=> [DOCS] Fixes broken link to Cloud documentation

docs/en/glossary/index.asciidoc
Fixes https://github.com/elastic/stack-docs/issues/130
The {ref} attribute value contains a {branch} attribute, so the versions.asciidoc (which defines :branch:) must be included before the attributes.asciidoc (which defines :ref:).
=> [DOCS] Fixes broken links in Glossary

docs/en/stack/security/authorization/built-in-roles.asciidoc
Related to https://github.com/elastic/kibana/pull/23974 and https://github.com/elastic/kibana/issues/21592
This PR clarifies what members of the reporting_user role can do.
=> [DOCS] Clarify description of reporting_user role

docs/en/stack/security/authentication/built-in-users.asciidoc, docs/en/stack/security/authorization/built-in-roles.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/34369
Updates to https://www.elastic.co/guide/en/elastic-stack-overview/master/monitoring-production.html will occur in a separate PR.
=> [DOCS] Adding stack_monitoring_agent role

docs/en/stack/index.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/34726
This PR adds the "Overview" and "Getting started" content for cross-cluster replication to the Elastic Stack Overview. For example:
NOTE: This PR must be merged *after* https://github.com/elastic/elasticsearch/pull/34726
=> [DOCS] Adds CCR to Stack Overview

docs/en/stack/ml/limitations.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/31999
This PR documents the current machine learning limitations related to the rollup feature.
=> [DOCS] Adds machine learning limitation related to rollups

docs/en/stack/security/get-started-builtin-users.asciidoc, docs/en/stack/security/get-started-security.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/34369
This PR updates the security tutorial (https://www.elastic.co/guide/en/elastic-stack-overview/master/get-started-built-in-users.html) to include the remote_monitoring_user builtin user.
=> [DOCS] Adds remote_monitoring_user to security tutorial

docs/en/stack/monitoring/production.asciidoc
This PR cleans up the content in the following page: https://www.elastic.co/guide/en/elastic-stack-overview/master/monitoring-production.html
Related to https://github.com/elastic/elasticsearch/pull/35111
=> [DOCS] Minimizes the duplicated information in the production monitoring page

docs/en/stack/ml/limitations.asciidoc
This PR documents limitations related to the use of Kibana spaces with machine learning objects.
=> [DOCS] Adds machine learning limitations related to Kibana spaces

docs/en/infraops/installation.asciidoc, docs/en/infraops/overview.asciidoc
Restructured the section about enabling modules based on feedback from @weltenwort submitted here: https://github.com/elastic/stack-docs/pull/142#discussion_r232353501
I removed a bit of the detail because I was motivated by the notion that less is more.
Note that I've uploaded the changes to firebase so you can see the output: https://inframonitoring-62ede.firebaseapp.com/
=> Add changes from review

docs/en/stack/security/authorization/privileges.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/35434
This PR documents the new read_ccr and manage_ccr cluster privileges.
=> [DOCS] Adds read_ccr and manage_ccr privileges

docs/en/stack/license.asciidoc, docs/en/stack/ml/analyzing.asciidoc, docs/en/stack/ml/architecture.asciidoc, docs/en/stack/ml/buckets.asciidoc, docs/en/stack/ml/forecasting.asciidoc, docs/en/stack/ml/getting-started-data.asciidoc, docs/en/stack/ml/getting-started-forecast.asciidoc, docs/en/stack/ml/getting-started-multi.asciidoc, docs/en/stack/ml/getting-started-single.asciidoc, docs/en/stack/ml/getting-started-wizards.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/limitations.asciidoc, docs/en/stack/ml/troubleshooting.asciidoc, docs/en/stack/monitoring/troubleshooting.asciidoc, docs/en/stack/security/authorization/built-in-roles.asciidoc, docs/en/stack/security/limitations.asciidoc, docs/en/stack/security/troubleshooting.asciidoc, docs/en/stack/troubleshooting.asciidoc, docs/en/stack/watcher/limitations.asciidoc, docs/en/stack/watcher/troubleshooting.asciidoc, docs/en/stack/xpack-enabling.asciidoc, docs/index.asciidoc
This PR replaces the X-Pack-specific attributes with feature-specific attributes to remove a lot of X-Pack terminology from the Stack Overview. It also changes the titles to sentence case.
=> [DOCS] Stack Overview cleanup

docs/en/stack/security/troubleshooting.asciidoc
Kerberos realm only supports Spnego mechanism (Oid 1.3.6.1.5.5.2) and
does not yet support Kerberos mechanism (Oid 1.2.840.113554.1.2.2).
Customers usually start initial testing using `curl` to test
Elasticsearch - Kerberos integration and may face problems
authenticating users using Kerberos.
Usually, the problems are due to:
- Known issues with older versions of `curl`.
It is recommended to use `curl` version 7.49 or above as earlier
versions are known to have issues
(like https://bugzilla.redhat.com/show_bug.cgi?id=1333004)
- Sometimes the support for `GSS-API`, `Kerberos` and `SPNEGO`
features are missing from the curl. One will need to download and install
the appropriate version of curl where these features exist or need to
compile with the required support.
This commit adds the …
=> [DOCS] Kerberos troubleshooting documentation for problems with curl

docs/en/getting-started/get-started-kubernetes.asciidoc
Related to https://github.com/elastic/stack-docs/issues/140
This PR adds introductory text to the list of Kubernetes links.  When this PR is backported, I will remove the Auditbeat links, since that page doesn't exist in 6.x or earlier branches.
=> [DOCS] Adds intro for Kubernetes

docs/en/getting-started/get-started-stack.asciidoc, docs/en/stack/limitations.asciidoc, docs/en/stack/ml/datafeeds.asciidoc, docs/en/stack/ml/getting-started-data.asciidoc, docs/en/stack/ml/getting-started-multi.asciidoc, docs/en/stack/ml/getting-started-single.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/limitations.asciidoc, docs/en/stack/redirects.asciidoc, docs/en/stack/security/authentication/kerberos-realm.asciidoc, docs/en/stack/security/authentication/overview.asciidoc, docs/en/stack/security/authorization/privileges.asciidoc, docs/en/stack/security/get-started-security.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/security/limitations.asciidoc, docs/en/stack/security/troubleshooting.asciidoc, docs/en/stack/troubleshooting.asciidoc, docs/en/stack/watcher/limitations.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/36232
This PR cleans up the references to the "Security files" page in the Stack Overview.
It also updates the location and title of the "Getting started with security" tutorial and cleans up some out-dated uses of the {security} attribute.
=> [DOCS] Moves security config file info

docs/en/stack/ml/api-quickref.asciidoc, docs/en/stack/ml/getting-started-next.asciidoc, docs/en/stack/ml/troubleshooting.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/36315
This PR removes occurrences of /_xpack/ml
=> [DOCS] Deprecate X-Pack-centric ML endpoints

docs/upgrading-stack.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/35976
Replaces occurrences of /_xpack/migration with /_migration.
=> [DOCS] Deprecate X-Pack-centric migration endpoints

docs/en/stack/monitoring/production.asciidoc, docs/en/stack/security/authentication/built-in-users.asciidoc, docs/en/stack/security/authorization/document-level-security.asciidoc, docs/en/stack/security/authorization/field-level-security.asciidoc, docs/en/stack/security/troubleshooting.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/36293
This PR changes occurrences of /_xpack/security to /_security/
=> [DOCS] Deprecate _xpack/security in favor of _security

docs/upgrading-stack.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/35959
Replaces occurrences of /_xpack/license with /_license
=> [DOCS] Deprecate X-Pack-centric license endpoints

docs/en/stack/monitoring/production.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/36508
This PR adds information about the ingest node requirement in the following page in the Stack Overview: https://www.elastic.co/guide/en/elastic-stack-overview/master/index.html
It also simplifies the page's introduction.
=> [DOCS] Adds monitoring requirement for ingest node

docs/en/stack/security/authorization/privileges.asciidoc
This adds details about ILM-specific roles:
- manage_ilm (index), manage_ilm (cluster)
- read_ilm (cluster)
- changes to view_index_metadata (index)
relates to: https://github.com/elastic/elasticsearch/pull/36749 and https://github.com/elastic/elasticsearch/pull/36493
=> add ILM privilege descriptions

docs/en/infraops/installation.asciidoc
Infrastructure UI makes use of the data collected by these processors, they are enabled by default starting with Beats 6.5 but I think its good to add them to the list of required info for awareness.
=> Add missing `host` and `cloud` metadata processors

docs/en/infraops/installation.asciidoc
* Add missing `host` and `cloud` metadata processors
Infrastructure UI makes use of the data collected by these processors, they are enabled by default starting with Beats 6.5 but I think its good to add them to the list of required info for awareness.
* Indicate the modules and processors that are enabled by default
=> Backport to 6.5: Add missing `host` and `cloud` metadata processors (#157)

docs/en/infraops/installation.asciidoc
* Add missing `host` and `cloud` metadata processors
Infrastructure UI makes use of the data collected by these processors, they are enabled by default starting with Beats 6.5 but I think its good to add them to the list of required info for awareness.
* Indicate the modules and processors that are enabled by default
=> Backport to 6.x: Add missing `host` and `cloud` metadata processors (#157)

docs/en/stack/security/authorization/privileges.asciidoc
Hellow.
I using ElasticCloud for role change when I lookup  `manage_ingest_pipelines`.
but It was not in the document.
=> Add Cluster privileges 's   `manage_ingest_pipelines`

docs/en/infraops/infra-ui-intro.asciidoc, docs/en/infraops/installation.asciidoc, docs/en/infraops/logs-ui-intro.asciidoc
=> Add links to Kibana docs

docs/en/stack/ml/limitations.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/34864 and https://github.com/elastic/elasticsearch/pull/36792
This PR adds information about the search size limitation to the machine learning limitations in the Stack Overview (https://www.elastic.co/guide/en/elastic-stack-overview/master/ml-limitations.html).
=> [DOCS] Adds ML api size limitation

docs/en/stack/monitoring/how-monitoring-works.asciidoc, docs/en/stack/monitoring/intro.asciidoc, docs/en/stack/monitoring/production.asciidoc, docs/en/stack/monitoring/troubleshooting.asciidoc
Related to https://github.com/elastic/beats/pull/10222
This PR removes the "beta[]" tags from the Metricbeat monitoring information in the Stack Overview.
It also replaces outdated "X-Pack monitoring" terminology ({monitoring} attribute) with {stack-monitor-features}, which resolves to "Elastic Stack monitoring features".
=> [DOCS] Removes beta tags from monitoring

docs/en/stack/security/authorization/privileges.asciidoc
This PR adds the manage_saml cluster privilege to https://www.elastic.co/guide/en/elastic-stack-overview/master/security-privileges.html
=> [DOCS] Adds manage_saml privilege

docs/en/glossary/glossary.asciidoc
This link from the glossary was broken after merging our ECE docs reshuffle.
=> Fix broken link to ECE docs

docs/en/getting-started/get-started-stack.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/37881
This PR updates the installation package names in the stack-docs repo. For example, it adds a new Linux section to https://www.elastic.co/guide/en/elastic-stack-get-started/master/get-started-elastic-stack.html#install-elasticsearch
=> [DOCS] Add OS/architecture classifier to distributions

docs/en/stack/security/authorization/index.asciidoc
The custom-roles-provider.asciidoc file is removed in https://github.com/elastic/elasticsearch/pull/37785
and replaced by custom-authorization.asciidoc
This PR updates the Stack Overview to use the new file.
=> [DOCS] Replace use of custom-roles-provider.asciidoc

docs/en/getting-started/get-started-stack.asciidoc
Adds Linux example commands to getting started docs. This is meant to complement https://github.com/elastic/stack-docs/pull/194.
Question: I'm not sure why we use the linux distros for Deb and RPM for Kibana. Maybe for historical reasons? Should we change this to show steps for using the Deb/RPM packages and starting Kibana as a service?
=> Add linux examples to the stack getting started

docs/en/getting-started/index.asciidoc, docs/en/infraops/index.asciidoc, docs/en/secops/index.asciidoc, docs/en/stack/index.asciidoc
Related to https://github.com/elastic/docs/pull/585
This PR updates the name of the shared version attributes file that is used by the Getting Started Guide, Infrastructure Monitoring Guide, Security Monitoring Guide, and Stack Overview.
=> [DOCS] Update shared versions file

docs/en/getting-started/index.asciidoc, docs/en/infraops/index.asciidoc, docs/en/secops/index.asciidoc, docs/en/stack/index.asciidoc
Reverts elastic/stack-docs#201
It ought to be merged into 7.x instead.
=> Revert "[DOCS] Update shared versions file"

docs/en/getting-started/index.asciidoc, docs/en/infraops/index.asciidoc, docs/en/secops/index.asciidoc, docs/en/stack/index.asciidoc
Related to https://github.com/elastic/docs/pull/585
This PR updates the name of the shared version attributes file that is used by the Getting Started Guide, Infrastructure Monitoring Guide, Security Monitoring Guide, and Stack Overview.
=> Update shared versions file

docs/en/install-upgrade/breaking.asciidoc, docs/index.asciidoc, docs/upgrading-stack.asciidoc
This PR adds a "Breaking Changes" page to the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/index.html) and lays the groundwork for adding highlighted breaking changes from across the stack to this book.
After we move to an Asciidoctor build for this book, we can use tagged regions to pull in content from  breaking change pages across the library (per https://asciidoctor.org/docs/user-manual/#by-tagged-regions). At that time, the build command will need to change as follows (with --resources parameters added for each repo we pull from):
docbldstk  --resource=elasticsearch/docs --resource=kibana/docs --asciidoctor
NOTE: The presence of these tagged regions cannot be processed by our current asciidoc builds, thus the following line must be added to the …
=> [DOCS] Adds breaking changes page with content re-use

docs/en/stack/security/troubleshooting.asciidoc
Relates: https://github.com/elastic/elasticsearch/pull/38628
=> Add trb information for InvalidNameIDPolicy

docs/en/infraops/installation.asciidoc
This PR adds definitions for each of the metrics (CPU Usage, Memory Usage, etc) for each of the node types (Hosts, Containers, Pods) available in the waffle map per #156
=> Update Infrastructure UI documentation with metric definitions

docs/en/infraops/installation.asciidoc
Merge pull request #210 from simianhacker/fixes-156
=> [6.6] Update Infrastructure UI documentation with metric definitions

docs/en/install-upgrade/index.asciidoc, docs/en/install-upgrade/overview.asciidoc
The "Overview" page in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack.html) does not have an anchor, so it's inheriting the "elastic-stack" anchor from the previous section.  That inheritance behaviour changes when we use Asciidoctor to build the book. Instead of relying on inheritance, this PR explicitly adds an anchor.
It also splits the "Overview" content into a separate source file to have a better 1:1 ratio between pages and source files.
=> [DOCS] Adds missing anchor in Installation Upgrade Guide

docs/en/install-upgrade/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/222
... though in this case it uses the existing anchor and does not split out a separate file for the Overview.
=> [6.7] [DOCS] Adds missing anchor in Installation Upgrade Guide

docs/en/install-upgrade/upgrading-stack.asciidoc
This PR updates the "important" warning at the top of https://www.elastic.co/guide/en/elastic-stack/master/upgrading-elastic-stack.html
Per https://github.com/elastic/stack-docs/pull/219#issuecomment-465162904
> ... The "2.x" in that bit should be whatever is two major versions earlier, so for 8.x it should be 6.x and for 7.x it should be 5.x.
=> [DOCS] Update version detail in upgrade instructions

docs/en/install-upgrade/upgrading-stack.asciidoc
This PR updates the "important" warning at the top of https://www.elastic.co/guide/en/elastic-stack/7.x/upgrading-elastic-stack.html
Per https://github.com/elastic/stack-docs/pull/219#issuecomment-465162904
> ... The "2.x" in that bit should be whatever is two major versions earlier, so for 8.x it should be 6.x and for 7.x it should be 5.x.
=> [7.x] [DOCS] Update version detail in upgrade instructions

docs/en/getting-started/get-started-stack.asciidoc
This PR fixes a problem with the numbering in a list in the Getting Started Guide when it's built via asciidoctor:
Per https://asciidoctor.org/docs/user-manual/#anchordef this problem can be fixed by using an inline anchor
=> [DOCS] Fixes anchor for asciidoctor

docs/en/getting-started/get-started-stack.asciidoc
This PR addresses a difference in the way Asciidoc and Asciidoctor handle sections that do not have anchors explicitly defined.  In particular:
Asciidoc generates:           <a id="_whats_next">
Asciidoctor generates:           <a id="_what_8217_s_next">
This PR explicitly defines an anchor rather than relying on generated text.
=> [DOCS] Fixes undefined anchor

docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
This PR fixes the following error when building the Stack Overview with AsciiDoctor:
INFO:build_docs:asciidoctor: WARNING: security/securing-communications/tutorial-tls-certificates.asciidoc: line 120: no callout found for <2>
INFO:build_docs:asciidoctor: WARNING: security/securing-communications/tutorial-tls-certificates.asciidoc: line 122: no callout found for <3>
This is related to https://github.com/elastic/docs/pull/566
=> [DOCS] Fixes inline callout in TLS tutorial

docs/en/install-upgrade/upgrading-stack.asciidoc, docs/en/stack/security/authentication/built-in-users.asciidoc, docs/en/stack/security/authentication/internal-users.asciidoc, docs/en/stack/security/authentication/overview.asciidoc, docs/en/stack/security/authorization/built-in-roles.asciidoc, docs/en/stack/security/authorization/overview.asciidoc, docs/en/stack/security/how-security-works.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/security/limitations.asciidoc
Related to https://github.com/elastic/docs/issues/407
This PR replaces occurrences of {security} or "X-Pack Security" with the new {security-features}, {stack-security-features}, or {es-security-features} terminology.
=> [DOCS] Replaces X-Pack security terminology

docs/en/stack/security/authorization/built-in-roles.asciidoc, docs/en/stack/security/authorization/privileges.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/39661
This PR drafts definitions for the `manage_data_frame_transforms` and `monitor_data_frame_transforms` cluster privileges and the `data_frame_transforms_admin` and 
`data_frame_transforms_user` built-in roles.
=> [DOCS] Drafts data frame privileges

docs/en/install-upgrade/breaking.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/38238 
This PR starts including the tagged region from the elasticsearch repo in the Installation and Upgrade Guide.  It also adds a section title for the Kibana breaking changes too.
=> Adds notable breaking changes from Elasticsearch

docs/en/glossary/glossary.asciidoc
This PR adds "cross-cluster replication", "follower index", and "leader index" to the Glossary (https://www.elastic.co/guide/en/elastic-stack-glossary/current/index.html).
These definitions are copied from https://github.com/elastic/elasticsearch/pull/39516
=> Adds CCR, leader and follower indices to Glossary

docs/en/stack/security/authorization/privileges.asciidoc
This commit adds a description of the manage_leader_index privilege, which is required to manage a leader index (specifically for use of the forget follower API).
Relates elastic/elasticsearch#39718
=> Add description of manage_leader_index privilege

docs/en/install-upgrade/upgrading-stack.asciidoc
The Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/upgrading-elastic-stack.html#upgrade-elastic-stack-for-elastic-cloud) contains broken links to Cloud documentation:
This PR fixes the link to go to https://www.elastic.co/guide/en/cloud/current/ec-upgrade-cluster.html
=> Fixes link to Cloud documentation

docs/en/stack/security/authorization/built-in-roles.asciidoc
The ML built in roles were adjusted in 6.6 because:
1. We added a .ml-config index that we do not want
any user to access directly
2. We added a .ml-annotations index that users as
well as admins require write access to
=> Fix ML built in role docs

docs/en/install-upgrade/upgrading-stack.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/40072
This PR adds deprecation notes to the migration assistance and migration upgrade APIs and suggests alternative methods.
=> [DOCS] Deprecates migration assistance and upgrade APIs

docs/en/glossary/glossary.asciidoc
Adds a definition for `recovery` to the Glossary. Closes /elastic/elasticsearch#7264.
=> [DOCS] Add 'recovery' to glossary for issue #7264

docs/en/install-upgrade/highlights.asciidoc, docs/en/install-upgrade/index.asciidoc
This PR drafts a "Highlights" page in the Installation and Upgrade Guide and re-uses content that's tagged as "notable-highlights" from the Elasticsearch Reference and Kibana Guide.
Depends on https://github.com/elastic/kibana/pull/33675 and https://github.com/elastic/elasticsearch/pull/40330
=> [DOCS] Adds highlights to the Installation and Upgrade Guide

docs/en/getting-started/get-started-stack.asciidoc
Added a link that points to the infrastructure monitoring docs.
I would have put this info earlier in the document to raise visibility, but it seemed wrong given the existing tutorial format. The getting started steps are still valid. I put the link in the "What's Next" section where we discuss other related resources.
I also made a small tweak to how we describe Logstash because it might help with some of the confusion customers experience when they are trying to understand whether they need to use Logstash. 
Closes #224
=> Link to infrastructure monitoring docs from the stack getting started

docs/en/install-upgrade/upgrading-stack.asciidoc
First pass at the upgrade changes for 7.0.
=> 7.0 upgrade

docs/en/infraops/installation.asciidoc
This PR closes https://github.com/elastic/kibana/issues/33375 by adding documentation for a known workaround for running <=6.5 data with 6.6+ Kibana.
=> [Infra UI] Add documentation for known workarounds

docs/en/install-upgrade/breaking.asciidoc
Depends on https://github.com/elastic/elasticsearch/pull/40478
This PR adds more Elasticsearch 7.0 breaking changes to the Installation and Upgrade Guide.
=> Adds 7.0 Elasticsearch breaking changes

docs/en/glossary/glossary.asciidoc
Adds a few [Elasticsearch definitions](https://www.elastic.co/guide/en/elasticsearch/reference/current/glossary.html) missing from the [Stack Docs glossary](https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html):
- [Cross-cluster search](https://github.com/elastic/elasticsearch/blame/master/docs/reference/glossary.asciidoc#L36)
- [Filter](https://github.com/elastic/elasticsearch/blame/master/docs/reference/glossary.asciidoc#L69)
- [Query](https://github.com/elastic/elasticsearch/blame/master/docs/reference/glossary.asciidoc#L140)
Uncovered this while working on these issues:
- elastic/elasticsearch#40560
- elastic/docs#759
=> [DOCS] Sync missing definitions from Elasticsearch glossary

docs/en/stack/watcher/troubleshooting.asciidoc
This PR works around https://github.com/elastic/docs/issues/760 by adding a substitutions attribute for the abbreviated title in https://www.elastic.co/guide/en/elastic-stack-overview/master/watcher-troubleshooting.html
=> [DOCS] Work around for titleabbrev errors

docs/en/stack/monitoring/how-monitoring-works.asciidoc
Per https://github.com/elastic/stack-docs/issues/226#issuecomment-467457287, 
> ...the monitoring docs say: "A monitoring cluster cannot monitor production clusters running newer versions of the stack. If necessary, the monitoring cluster can monitor production clusters running older versions, but the versions cannot differ by more than one major version." The last part is wrong. It should say - the same major version, or major-1.latest to major.latest (in some more human-readable form).
This PR addresses that inaccuracy.
=> [DOCS] Clarify version compability in monitoring docs

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/264
This PR looks for a tagged region ("notable-breaking-changes") in https://www.elastic.co/guide/en/beats/libbeat/7.0/breaking-changes-7.0.html so that it can be re-used in https://www.elastic.co/guide/en/elastic-stack/7.0/elastic-stack-breaking-changes.html
=> [DOCS] Adds notable Beats breaking changes

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Related to https://github.com/elastic/docs/pull/768
This page splits the Highlights and Breaking Changes pages in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/index.html) into multiple sub-pages. It also adds an introductory sentence and a bulleted list of links in the Highlights page
=> Splits highlights and breaking changes into multiple pages

docs/en/glossary/glossary.asciidoc
Condenses and simplifies the `query` definition from the [Elasticsearch glossary](https://www.elastic.co/guide/en/elasticsearch/reference/current/glossary.html).
Lateral port (sideport?) of elastic/elasticsearch#40746
Resolves elastic/elasticsearch#40643
=> [DOCS] Rewrite query def

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/index.asciidoc
Depends on https://github.com/elastic/apm-server/pull/2076 and https://github.com/elastic/docs/pull/788
This PR re-uses the tagged regions from APM Overview > Breaking Changes (https://www.elastic.co/guide/en/apm/get-started/master/apm-breaking-changes.html) in the Installation and Upgrade Guide > Breaking Changes (https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-breaking-changes.html)
=> Adds APM breaking changes to Install Upgrade Guide

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/index.asciidoc
Depends on https://github.com/elastic/docs/pull/789 and https://github.com/elastic/elasticsearch-hadoop/pull/1271
This PR re-uses the tagged regions from the Elasticsearch Hadoop breaking changes (https://www.elastic.co/guide/en/elasticsearch/hadoop/master/breaking-changes.html) in the Installation and Upgrade Guide > Breaking Changes (https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-breaking-changes.html)
=> Adds Elasticsearch Hadoop breaking changes to Install Upgrade Guide

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/index.asciidoc
Depends on https://github.com/elastic/docs/pull/791
This PR re-uses the tagged regions from the Logstash Reference > Breaking Changes (https://www.elastic.co/guide/en/logstash/master/breaking-changes.html) in the Installation and Upgrade Guide > Breaking Changes (https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-breaking-changes.html)
=> Adds Logstash breaking changes to Install Upgrade Guide

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/271
Depends on https://github.com/elastic/logstash/pull/10661
=> Adds Logstash breaking changes to Install Upgrade Guide (#271)

docs/en/install-upgrade/highlights.asciidoc
Depends on https://github.com/elastic/beats/pull/11621
This PR adds Beats notable highlights to the following section of the Installation and Upgrade Guide: https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-highlights.html
The inclusion of the tagged region is commented out at this point since the 8.0.0 file does not exist yet.
=> Adds Beats highlights to Install Upgrade Guide

docs/en/infraops/installation.asciidoc
This PR fixes a typo with the Kubernetes Memory field, it changes `kubernetes.pod.memory.usage.pct` to `kubernetes.pod.memory.usage.node.pct`
=> [Infra UI] Fixing Kubernetes memory field typo

docs/en/install-upgrade/breaking.asciidoc
Depends on https://github.com/elastic/elasticsearch/pull/40990
This PR re-uses content from the Elasticsearch Reference's breaking changes in the Installation and Upgrade Guide.
=> Adds more Elasticsearch breaking changes

docs/en/install-upgrade/upgrading-stack.asciidoc
This PR clarifies the upgrade process with respect to installing X-Pack and using the Upgrade Assistant.
=> Updates X-Pack and Upgrade Assistant details

docs/en/install-upgrade/breaking.asciidoc
Depends on https://github.com/elastic/elasticsearch/pull/41049
This PR configures the Installation and Upgrade Guide to pull breaking changes from new migrate_7_0/ingest.asciidoc and migrate_7_0/ml.asciidoc files in the elasticsearch repo
=> Adds ingest and ml breaking changes

docs/en/install-upgrade/breaking.asciidoc
This PR cleans up a reference to 2.x in the 7.0 Installation and Upgrade Guide.
=> Removes 2.x references from Install Upgrade breaking changes

docs/en/gke-on-prem/index.asciidoc
Related to https://github.com/elastic/docs/pull/815
This PR shortens the title of the book and adds a sub-title, with the following results:
The shorter title is also used in the breadcrumbs on each page, for example:
=> Changes title and adds subtitle for gke-on-prem book

docs/en/install-upgrade/breaking.asciidoc
Depends on https://github.com/elastic/elasticsearch/pull/41095
This PR re-uses the tagged region in the Elasticsearch Reference for breaking changes in index lifecycle management (ILM).
=> Adds ILM breaking changes

docs/en/install-upgrade/breaking.asciidoc
Depends on https://github.com/elastic/elasticsearch/pull/40918
This PR re-uses notable breaking changes from the Elasticsearch Reference (https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-8.0.html) in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/elasticsearch-breaking-changes.html)
=> Adds Elasticsearch 8.0 notable breaking changes

docs/en/gke-on-prem/gke-on-prem-architecture.asciidoc
This PR changes the following text in https://www.elastic.co/guide/en/elastic-stack-gke/current/architecture.html:
> The sample application referenced in "Example Application", below, exposes a port to the external network.
It adds a link to https://www.elastic.co/guide/en/elastic-stack-gke/current/gke-on-prem-deploy.html#gke-on-prem-example so that it's clearer what is meant by "below".
=> Fixes link in gke-on-prem-architecture

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 5.0

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 5.1

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 5.2

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 5.3

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 5.4

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 5.5

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 5.6

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 6.0

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 6.1

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 6.2

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 6.3

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 6.4

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 6.5

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 6.6

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 6.7

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 7.x

docs/en/install-upgrade/upgrading-stack.asciidoc
=> [DOCS] Fix broken Cloud link for 7.0

docs/en/install-upgrade/upgrading-stack.asciidoc
Looks like `{cloud}/ec-upgrade-cluster.html` might need to be `{cloud}/ec-upgrade-deployment.html`.
=> Fix broken link to Cloud docs

docs/en/infraops/installation.asciidoc
This PR fixes a few typos (thanks @gingerwizard) and adds a section about how `event.dataset` is a required field for the Metrics detail page.
=> [Infra UI] Adding note required field for metric detail page and fixing typos

docs/en/stack/monitoring/how-monitoring-works.asciidoc
When we switch to Asciidoctor builds, the image scale attribute is no longer necessary and causes the image to be too small in https://github.com/elastic/stack-docs/edit/master/docs/en/stack/monitoring/how-monitoring-works.asciidoc:
This change should be deferred until after we've migrated the Stack Overview to Asciidoctor builds.
=> [DOCS] Remove scale attributes

docs/en/stack/security/authentication/ldap-realm.asciidoc
Fixes a small typo on https://www.elastic.co/guide/en/elastic-stack-overview/master/ldap-realm.html
Relates to elastic/elasticsearch#40427
=> [DOCS] Fix typo

docs/en/gke-on-prem/index.asciidoc
I had shortened the title of this doc and removed the possessive `'s` in `Google Cloud's Anthos`.  Google's naming guideline asks for `'s`.
=> fixed branding mentioned in issue 320

docs/en/gke-on-prem/gke-on-prem-introduction.asciidoc
typo correction:
was: in your data center of Google Cloud 
changed to: in your data center or in
Google Cloud
=> Typo in gke-on-prem-introduction

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Depends on https://github.com/elastic/kibana/pull/35994 and https://github.com/elastic/elasticsearch/pull/41773
This PR updates the Installation and Upgrade Guide for 7.1 such that it references the appropriate files from the elasticsearch and kibana repos.
=> [DOCS] Updates links to Kibana and Elasticsearch breaking changes

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Depends on https://github.com/elastic/kibana/pull/35989
This PR updates the Installation and Upgrade Guide for 7.x such that it references the appropriate files from the Kibana Guide.
=> Updates links to Kibana breaking changes and highlights

docs/en/install-upgrade/breaking.asciidoc
This change must be merged along with https://github.com/elastic/beats/pull/12173
I'm using the breaking-7.0.asciidoc because an 8.0 version of the file doesn't exist yet. After I backport my changes in the beats repo, I'll create the 8.0 file in master and update the stack-docs. Just want to get everything working in 7.0 before I do that.
=> [Docs] Change path to beats breaking changes file

docs/en/stack/security/authentication/index.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/41423
This PR adds the configuration information for the OpenID Connect realm in the Stack Overview.
=> Adds OIDC guide to Stack Overview

docs/en/stack/security/get-started-enable-security.asciidoc, docs/en/stack/security/get-started-security.asciidoc, docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
This PR updates the following tutorials in the Stack Overview: 
https://www.elastic.co/guide/en/elastic-stack-overview/master/security-getting-started.html
https://www.elastic.co/guide/en/elastic-stack-overview/master/encrypting-internode-communications.html
NOTE: It also changes the step related to looking at the privileges for the `kibana_user` role, since that information was no longer correct.
=> [DOCS] Updates to the Getting started with security tutorial

docs/en/install-upgrade/upgrading-stack.asciidoc
Relates to elastic/elasticsearch#42255
=> [DOCS] Fix assumption that 6.7 is last 6.x release

docs/en/stack/security/authorization/privileges.asciidoc
Related to elastic/elasticsearch#41423
=> Add information about manage_oidc privilege

docs/en/getting-started/index.asciidoc, docs/en/infraops/index.asciidoc, docs/en/secops/index.asciidoc, docs/en/stack/index.asciidoc
Related to https://github.com/elastic/docs/pull/894
This PR updates the books in the stack-docs repo to use the new shared file: https://github.com/elastic/docs/blob/master/shared/versions73.asciidoc
=> Updates shared version attributes file

docs/en/stack/security/get-started-security.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/42202
This PR and https://github.com/elastic/elasticsearch/pull/42459 fix the following build errors:
12:04:56 INFO:build_docs:/tmp/docsbuild/target_repo/html/en/elastic-stack-overview/master/index.xml:5905: element xref: validity error : IDREF attribute linkend references an unknown ID "java-clients"
=> [DOCS] Fixes broken link to java-clients

docs/en/stack/ml/limitations.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/42529 and https://github.com/elastic/elasticsearch/issues/42295
This PR adds information about the SSE4.2 requirement to the "Machine learning limitations" in the Stack Overview.
=> [DOCS] Adds ML SSE4.2 limitation

docs/en/install-upgrade/breaking.asciidoc
Backports #331 to the 7.0 branch.
Must be merged at the same time as https://github.com/elastic/beats/pull/12321
=> [7.0][Docs] Backport: Change path to beats breaking changes file (#331)

docs/en/install-upgrade/breaking.asciidoc
Backports #331 to the 7.1 branch. Must be merged at the same time as https://github.com/elastic/beats/pull/12322
=> [7.1][Docs] Backport: Change path to beats breaking changes file (#331)

docs/en/stack/monitoring/esms.asciidoc, docs/en/stack/monitoring/index.asciidoc, docs/en/stack/monitoring/production.asciidoc, docs/en/stack/monitoring/troubleshooting.asciidoc
This PR adds information similar to https://www.elastic.co/guide/en/elastic-stack-overview/master/monitoring-production.html, but instead of sending the monitoring data to a monitoring cluster, it is sent to the Elasticsearch Stack Monitoring Service.
Initially this page contains instructions for using Metricbeat to monitor Kibana and Elasticsearch.  It will be expanded to describe using collectors and exporters and monitoring Logstash.
This PR depends on tagged regions that are implemented in https://github.com/elastic/kibana/pull/37123,  https://github.com/elastic/elasticsearch/pull/42547, https://github.com/elastic/elasticsearch/pull/42601,  and https://github.com/elastic/kibana/pull/37198 to permit content-reuse. It also uses attributes implemented in …
=> [DOCS] Adds configuration information for ESMS

docs/en/stack/security/authorization/built-in-roles.asciidoc
Users who create roles that are similar to the reserved roles
need to know about these.
The privileges were added to the reserved roles in
elastic/elasticsearch#40651 and elastic/elasticsearch#42757
=> Add Kibana application privileges to the reserved role docs

docs/en/install-upgrade/highlights.asciidoc
Adds release highlights for 7.1. This PR needs to be merged at the same time as https://github.com/elastic/beats/pull/12376.
=> [DOCS] Add beats 7.1 release highlights

docs/en/stack/security/get-started-enable-security.asciidoc, docs/en/stack/security/get-started-security.asciidoc, docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
This PR addresses comments such as https://github.com/elastic/stack-docs/pull/329#discussion_r285728857 by stating that the two security tutorials (https://www.elastic.co/guide/en/elastic-stack-overview/master/security-getting-started.html and https://www.elastic.co/guide/en/elastic-stack-overview/master/encrypting-internode-communications.html) require the use of the basic license. 
It also adds a step to enable single-node discovery so that TLS setup is postponed from the first tutorial.
=> [DOCS] Updates license details in security tutorials

docs/en/stack/security/authentication/realm-chains.asciidoc
This PR makes the following clearer.
- The order list does not matter. What matters is the `order` parameter.
- Also, it is not clear which order is consulted first.
=> Fix confusion on the order parameter

docs/en/stack/ml/limitations.asciidoc
This PR updates the following limitation, since it is no longer accurate:
https://www.elastic.co/guide/en/elastic-stack-overview/master/ml-limitations.html#_time_based_index_patterns_are_not_supported
=> [DOCS] Update ML limitation

docs/en/getting-started/get-started-stack.asciidoc
* recommend using config-dir as best practice on mac, because
* implicitly suggesting .conf-files in the root-dir is a bad idea
* clutters the users dir and provokes inconsistency across platforms
* the config-dir is created on install anyway, so have people use it (or don't create it - clutter)
* add missing `cd logstash$version` in docs (`./` is referred to as that dir, but no cd was indicated previously - this is inconsistent with the docs otherwise comprehensive style)
* add `config/` to demo-arg for logstash -f with respect to the aforementioned recommendation
=> minor guide-improvements for mac

docs/en/stack/data-frames/dataframes.asciidoc, docs/en/stack/data-frames/index.asciidoc, docs/en/stack/index.asciidoc
This PR adds a page to the Stack Overview related to creating a data frame transform that pivots your data.
It also adds a link to the data frame APIs in the Elasticsearch Reference.
https://github.com/elastic/elasticsearch/pull/42971 must be merged before the pivoting page can be uncommented.
=> [DOCS] Adds pivoting to Stack Overview

docs/en/install-upgrade/highlights.asciidoc
Dependent on https://github.com/elastic/apm-server/pull/2292
This PR adds an APM section to the Installation and Upgrade Guide's Highlights page: https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-highlights.html
=> Adds APM release highlights to Installation Upgrade Guide

docs/en/getting-started/get-started-stack.asciidoc, docs/en/stack/index.asciidoc, docs/en/stack/security/get-started-builtin-users.asciidoc, docs/en/stack/security/get-started-kibana-users.asciidoc, docs/en/stack/security/securing-communications/tutorial-tls-addnodes.asciidoc, docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc, docs/en/stack/security/securing-communications/tutorial-tls-internode.asciidoc, docs/en/stack/security/securing-communications/tutorial-tls-intro.asciidoc
This PR updates the TLS tutorial (https://www.elastic.co/guide/en/elastic-stack-overview/master/encrypting-internode-communications.html) such that it:
1) No longer uses out-dated zen settings
2) Changes the order of the steps such that they work for nodes with basic licenses.
3) Re-uses some existing content via tagged sections so that we don't have to maintain the same information in multiple places.
=> [DOCS] Updates TLS tutorial for use with basic licenses and new cluster formation settings

docs/en/getting-started/get-started-stack.asciidoc
Decided to include `brew tap elastic/tap` in each section for readers who don't read all the things.
Also kept the instructions to the default packages (since the rest of the guide doesn't show OSS). Tweaked the wording because it was based on the older wording before basic was in the default.
=> [DOCS] Add steps for homebrew

docs/en/getting-started/get-started-stack.asciidoc
I  missed a couple of backports to 7.x awhile back ago.
Also backpports #384 to 7.x branch.
=> [DOCS][7.x] Backport #384 and catchup missing backports

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR removes the coming[7.2.0] tags from the stack-docs repo.
=> Removes coming tags from Installation & Upgrade Guide

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR backports https://github.com/elastic/stack-docs/pull/375 to 7.2
It is related to https://github.com/elastic/apm-server/pull/2298
=> [7.2] Adds APM release highlights to Installation Upgrade Guide

docs/en/install-upgrade/breaking.asciidoc
Related to https://github.com/elastic/kibana/pull/39818
This PR updates the Installation and Upgrade Guide such that it clearly states that there are no breaking changes for Kibana in 7.1.
=> Updates Kibana breaking changes

docs/en/getting-started/index.asciidoc, docs/en/infraops/index.asciidoc, docs/en/stack/index.asciidoc
Related to https://github.com/elastic/docs/pull/962
This PR updates the version attributes for various books in the stack-docs repo so that they're set appropriately for the 7.x branch.
=> Updates version attributes

docs/en/stack/security/authorization/privileges.asciidoc
Relates: elastic/elasticsearch#43728
=> Document "manage_api_key" cluster privilege

docs/en/glossary/glossary.asciidoc, docs/en/stack/ml/api-quickref.asciidoc
Related to https://github.com/elastic/stack-docs/issues/237
This PR updates occurrences of machine learning job terminology with the appropriate shared attribute from https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc, such that it's clear whether anomaly detection jobs or data frame analytics jobs (or both types of machine learning jobs) are discussed.
=> Updates ML job terminology

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR updates uncomments the inclusions on the following pages in the Installation and Upgrade Guide:
https://www.elastic.co/guide/en/elastic-stack/7.3/kibana-higlights.html
https://www.elastic.co/guide/en/elastic-stack/7.3/kibana-breaking-changes.html
... since that content now exists in the Kibana User Guide https://www.elastic.co/guide/en/kibana/7.3/index.html
=> Adds Kibana highlights and breaking changes

docs/en/stack/data-frames/ecommerce-example.asciidoc
elastic/elasticsearch/pull/44238 moved several Elasticsearch APIs to a REST APIs section.
As a result of that move, some pages were converted to anchored sections. This will fix links to those pages once the above PR is re-applied.
I plan to merge this PR simultaneously with:
- elastic/elasticsearch/pull/44238
- elastic/elasticsearch/pull/44279
- elastic/kibana/pull/41001
- elastic/elasticsearch-hadoop/pull/1317
=> [DOCS] Fix broken links for ES API docs move

docs/en/stack/ml/analyzing.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/jobs.asciidoc
Related to https://github.com/elastic/stack-docs/pull/225
The current machine learning tutorial (https://www.elastic.co/guide/en/elastic-stack-overview/master/ml-getting-started.html) is out-dated and is in the process of being replaced. 
This PR removes it from the documentation since it uses scripts that no longer works (i.e. they use mapping types).  The scripts could perhaps be fixed by removing the PUT mapping call and letting Elasticsearch infer the correct types and removing the type from the bulk update. Since we're overhauling the tutorial anyway, we'll just remove it for now instead.
NOTE: https://github.com/elastic/elasticsearch/pull/44251 and https://github.com/elastic/kibana/pull/40943 must be merged first.
=> Removes the machine learning tutorial

docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc
Related to https://github.com/elastic/stack-docs/issues/413
This PR removes unnecessary edit_url attributes from the master branch
=> Removes edit_url attributes

docs/en/stack/data-frames/dataframes.asciidoc, docs/en/stack/index.asciidoc, docs/en/stack/ml/df-analytics/api-quickref.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc, docs/en/stack/ml/index.asciidoc
This PR adds a "Machine learning data frame analytics" section to the Stack Overview and an API quick reference page within that section. 
It also rename the "Data frames" section to "Data frame transforms" and renames the "Machine learning in the Elastic Stack" to "Machine learning anomaly detection".
=> Adds data frame analytics placeholder to Stack Overview

docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc
This PR removes unnecessary edit_url attributes from the 7.3 branch
=> [7.3] Removes edit_url attributes (#414)

docs/en/stack/index.asciidoc, docs/en/stack/limitations.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/troubleshooting.asciidoc
This PR removes unnecessary edit_url attributes from the 7.2 branch
=> [7.2] Removes edit_url attributes (#414)

docs/en/stack/index.asciidoc, docs/en/stack/limitations.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/troubleshooting.asciidoc
This PR removes unnecessary edit_url attributes from the 7.1 branch
=> [7.1] Removes edit_url attributes (#414)

docs/en/stack/index.asciidoc, docs/en/stack/limitations.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/troubleshooting.asciidoc
This PR removes unnecessary edit_url attributes from the 7.0 branch
=> [7.0] Removes edit_url attributes (#414)

docs/en/stack/index.asciidoc, docs/en/stack/limitations.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/troubleshooting.asciidoc
This PR removes unnecessary edit_url attributes from the 6.6 branch
=> [6.6] Removes edit_url attributes (#414)

docs/en/stack/index.asciidoc, docs/en/stack/limitations.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/troubleshooting.asciidoc
This PR removes unnecessary edit_url attributes from the 6.4 branch
=> [6.4] Removes edit_url attributes (#414)

docs/en/stack/index.asciidoc, docs/en/stack/limitations.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/troubleshooting.asciidoc
This PR removes unnecessary edit_url attributes from the 6.8 branch
=> [6.8] Removes edit_url attributes (#414)

docs/en/stack/data-frames/dataframe-examples.asciidoc, docs/en/stack/data-frames/ecommerce-example.asciidoc, docs/en/stack/data-frames/index.asciidoc
This PR reorganizes the data frame examples in the Stack Overview.  In particular, it moves the "Transforming your data" page under the "Examples" section and makes all of the example subsections into separate pages.
=> [DOCS] Reorganizes data frame examples

docs/en/stack/index.asciidoc, docs/en/stack/ml/getting-started.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/overview.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authorization/index.asciidoc, docs/en/stack/security/index.asciidoc, docs/en/stack/xpack-limitations.asciidoc, docs/en/stack/xpack-troubleshooting.asciidoc
This PR removes unnecessary edit_url attributes from the 6.3 branch
=> [6.3] Removes edit_url attributes (#414)

docs/en/stack/data-frames/ecommerce-example.asciidoc
elastic/elasticsearch#44372 moved the navigation for several Elasticsearch APIs under the [REST APIs section](https://www.elastic.co/guide/en/elasticsearch/reference/master/rest-apis.html). That PR included [several redirects](https://github.com/elastic/elasticsearch/pull/44372/files#diff-427622c7e85f29d0b8f204c583e153f1) to avoid broken links.
This PR updates a link pointing to one of those redirected links. This saves users a step when visiting this link. It also rewraps the paragraph containing the link.
Will backport to 7.3
=> [DOCS] Update anchors and links for Elasticserach API relocation.

docs/en/stack/data-frames/checkpoints.asciidoc, docs/en/stack/data-frames/index.asciidoc, docs/en/stack/data-frames/limitations.asciidoc, docs/en/stack/data-frames/overview.asciidoc
This PR moves the content from docs/en/stack/data-frames/dataframes.asciidoc into a lower-level "Overview" page.  It then adds information to the highest-level "Data frame transforms" page about when it makes sense to use data frames instead of aggregations.
=> Adds info about when to use data frames

docs/en/stack/ml/df-analytics/api-quickref.asciidoc
This PR adds the evaluate API endpoint base to the API quick reference page.
Related issue: https://github.com/elastic/ml-team/issues/187#issuecomment-513165387
=> [DOCS] Adds the evaluate API endpoint base to the quick reference page

docs/en/stack/security/troubleshooting.asciidoc
The failed audience restriction exception message was changed in
elastic/elasticsearch#44334
This commit updates the troubleshooting guide to match the new
messages.
=> Update "audience condition" SAML troubleshooting

docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc, docs/en/stack/ml/anomaly-detection/buckets.asciidoc, docs/en/stack/ml/anomaly-detection/calendars.asciidoc, docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc, docs/en/stack/ml/anomaly-detection/forecasting.asciidoc, docs/en/stack/ml/anomaly-detection/jobs.asciidoc, docs/en/stack/ml/anomaly-detection/limitations.asciidoc, docs/en/stack/ml/anomaly-detection/rules.asciidoc, docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
Related to https://github.com/elastic/stack-docs/issues/237
This PR updates pages in the Stack Overview that use out-dated or unspecific "job" terminology to use the appropriate "anomaly detection job" attributes.
=> Updates anomaly detection job terminology in Stack Overview

docs/en/stack/data-frames/limitations.asciidoc
This PR fixes a couple of heading errors in 7.3 data frame transform limitations.
=> [DOCS] Fixes the headings in the data frame transform limitations

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR removes the coming[7.3.0] tags from the Installation and Upgrade Guide. It also makes changes to pick up the APM and Elasticsearch release highlights and breaking changes.
This PR must be merged after https://github.com/elastic/elasticsearch/pull/45066
=> Updates 7.3.0 release highlights and breaking changes

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc
This PR adds the data frame analytics limitations subsection to the Machine learning data frame analytics section.
=> [DOCS] Adds data frame analytics limitations

docs/en/stack/redirects.asciidoc
Adds a redirect for a broken link currently blocking the docs build.
This link is live in 7.3+ so it only affects the 7.2 branch.
=> [DOCS] Add Kerberos configration redirect

docs/en/install-upgrade/highlights.asciidoc
This PR depends on https://github.com/elastic/beats/pull/13138
After that PR is backported to 7.3, this PR can integrate those release highlights in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/current/beats-highlights.html)
=> [DOCS] Adds Beats 7.3 release highlights

docs/en/stack/security/securing-communications/tutorial-tls-certificates.asciidoc
This fixes two issues with the example command to generate a node certificate:
- it adds a backslash that was missing on one of the lines, which prevented the subsequent flag from being read
- it removes the blank space between the end-of-line backslashes and the line markings (e.g. `"\ <2>"` becomes `"\<2>"`), which added invisible spaces to the command when copied-and-pasted, resulting in most of the lines being ignored even though it looked right on the terminal
@lcawl, I don't know much about our asciidoc practices / build system, and my only concern is that the second item (removing the spaces) might keep it from recognizing the footnote symbols. If so I imagine you can advise me how to do it correctly :-)
=> fix typo in command-line for certificate generation

docs/en/stack/index.asciidoc, docs/en/stack/monitoring/esms.asciidoc, docs/en/stack/monitoring/intro.asciidoc
Related to https://github.com/elastic/beats/issues/12647 and https://github.com/elastic/docs/pull/1043
This PR updates the instructions in the Stack Overview > Elastic Stack Monitoring Service page
(https://www.elastic.co/guide/en/elastic-stack-overview/master/esms.html) to include setup steps for collecting Beats monitoring data.
=> Adds instructions for sending Beats monitoring data to ESMS

docs/en/stack/ml/anomaly-detection/jobs.asciidoc
This PR fixes an incorrect substitution on the Jobs page.
=> [DOCS] Fixes incorrect substitution in Jobs section

docs/en/install-upgrade/breaking.asciidoc
I think the hardwiring of `7.3.0` is a bug. Everywhere else, including the header for this section, uses `{version}`.
=> [docs] Update Hadoop to use version attribute

docs/en/stack/security/troubleshooting.asciidoc
Add addition to SSLHandshakeException troubleshooting guide for ECDH ServerKeyExchange
that might be caused by cert/cacert/key mismatch.
Backport of: #332
Co-Authored-By: Tim Vernum <tim@adjective.org>
Co-Authored-By: Peter Dyson <peter.dyson@geekpete.com>
=> [Backport 7.x] add additional SSLHandshakeException

docs/en/stack/security/troubleshooting.asciidoc
Add addition to SSLHandshakeException troubleshooting guide for ECDH ServerKeyExchange
that might be caused by cert/cacert/key mismatch.
Backport of: #332
Co-Authored-By: Tim Vernum <tim@adjective.org>
Co-Authored-By: Peter Dyson <peter.dyson@geekpete.com>
=> [Backport 7.3] add additional SSLHandshakeException

docs/en/getting-started/index.asciidoc, docs/en/infraops/index.asciidoc, docs/en/stack/index.asciidoc
Related to https://github.com/elastic/docs/pull/1109 and https://github.com/elastic/docs/pull/1108
This PR updates the books in the 7.x branch to use the appropriate shared version attributes file.
=> Updates version attributes filename

docs/en/stack/security/authorization/privileges.asciidoc
This commit documents `manage_own_api_key` cluster privilege.
Related to https://github.com/elastic/elasticsearch/pull/45897 and https://github.com/elastic/elasticsearch/issues/40031
=> Add `manage_own_api_key` cluster privilege documentation

docs/en/stack/index.asciidoc
Depends on https://github.com/elastic/docs/pull/1148
This PR changes the location of the shared version attributes (so that updates are not required every time there's a new branch).
NOTE: The source_branch attribute definition should be removed from this PR after https://github.com/elastic/docs/pull/1147 is merged.
=> Updates location of version attributes for Stack Overview

docs/en/getting-started/index.asciidoc
Related to https://github.com/elastic/docs/issues/804
Depends on elastic/docs#1148 and elastic/docs#1147
This PR changes the location of the shared version attributes (so that updates are not required every time there's a new branch).
=> Updates location of version attributes for Getting started with Stack

docs/en/gke-on-prem/index.asciidoc, docs/en/glossary/index.asciidoc, docs/en/infraops/index.asciidoc, docs/en/siem/index.asciidoc
Related to elastic/docs#804
Depends on elastic/docs#1148 and elastic/docs#1147
This PR changes the location of the shared version attributes (so that updates are not required every time there's a new branch).
=> Updates location of version attribute for multiple books

docs/en/stack/security/authentication/kerberos-realm.asciidoc
Now that we added support for Kerberos in 7.3, this commit
removes the incorrect note from the docs that it is not supported.
=> Remove incorrect note for Kerberos support in Kibana

docs/en/stack/data-frames/limitations.asciidoc
This PR deletes "Cannot update data frame transform" limitation because it is no longer valid.
Related issue: https://github.com/elastic/ml-team/issues/187#issuecomment-529356690
=> [DOCS] Deletes Cannot update data frame transform limitation

docs/en/install-upgrade/index.asciidoc
This PR changes the location of the version attributes from the ES repo to a shared file in elastic/docs.
Unblocks elastic/elasticsearch#46719
Related to https://github.com/elastic/docs/issues/804
=> Use shared versions file from elastic/docs for install-upgrade guide

docs/en/stack/ml/df-analytics/index.asciidoc, docs/en/stack/security/authorization/built-in-roles.asciidoc, docs/en/stack/security/authorization/privileges.asciidoc
Related to https://github.com/elastic/stack-docs/issues/478
This PR fixes occurrences of data frame transforms in the stack-docs repo.
=> [DOCS] Updates data frame transform terminology

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR expands the limitation section with a new item about unsupported field types and documents.
Related issue: https://github.com/elastic/ml-team/issues/187#issuecomment-528351782
=> [DOCS] Adds data frame analytics field type and document limitation

docs/en/stack/ml/df-analytics/dfa-regression.asciidoc, docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc
This PR adds the conceptual overview of regression and the related evaluation type to the documentation. Also amends the index.asciidoc file to contain the new additions.
Depends on https://github.com/elastic/docs/pull/1124 because of the used attributes.
Related issue: https://github.com/elastic/ml-team/issues/203
=> [DOCS] Adds conceptual documentation of regression and the related evaluation type

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR fixes two wrongly defined section level in the limitations piece.
=> [DOCS] Fixes wrong section level in data frame analytics limitations

docs/en/install-upgrade/highlights.asciidoc
This PR removes some introductory text from the Kibana release highlights in the Installation and Upgrade Guide. Related to https://github.com/elastic/kibana/pull/42768
=> Update Kibana release highlights in Install Upgrade Guide

docs/en/stack/ml/df-analytics/index.asciidoc
This PR must be merged after https://github.com/elastic/elasticsearch/pull/46940
It updates a link to the transform APIs page, which has a new URL when that PR is merged.
=> [DOCS] Fixes link to transform APIs

docs/en/stack/ml/df-analytics/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/525
=> [7.x][DOCS] Fixes link to transform APIs (#525)

docs/en/stack/ml/df-analytics/index.asciidoc
Backports https://github.com/elastic/stack-docs/pull/525
=> [7.4][DOCS] Fixes link to transform APIs (#525)

docs/en/glossary/glossary.asciidoc
Replaces duplicated glossary definitions with tagged regions from the Elasticsearch glossary.
Dependent on elastic/elasticsearch#46782. CI failures are expected until then.
Relates to elastic/elasticsearch#46683.
=> [DOCS] Reuse glossary items from ES glossary

docs/en/stack/index.asciidoc, docs/en/stack/redirects.asciidoc
Related to elastic/stack-docs#503 and https://github.com/elastic/elasticsearch/pull/46846
This PR moves the content related to transform into closer proximity to the documentation for the data rollups feature.
=> [DOCS] Removes transform content from Stack Overview

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR applies the changes of https://github.com/elastic/stack-docs/pull/501 on the 7.3 branch (contains only the outlier detection limitation).
=> [DOCS][7.3] Adds data frame analytics field type and document limitation

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc, docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc
Related to https://github.com/elastic/stack-docs/issues/518
This PR changes the wording of the data frame analytics limitation- and the evaluate data frame analytics pieces to move away from the data frame terminology.
Other occurrences of the `data frame` or `data frames` expressions were necessary to leave in the text (limitation piece & index).
List of occurrences:
```
Istvan-MacBook-Pro:stack-docs[master]$ find docs -name '*.asciidoc' | xargs egrep 'data frame'
Istvan-MacBook-Pro:stack-docs[master]$ find docs -name '*.asciidoc' | xargs egrep 'dataframe'
docs/en/stack/redirects.asciidoc:* <<dataframe-limitations>>
docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc:For more details about creating {transforms}, see <<ecommerce-dataframes>>. …
```
=> [DOCS] Changes wording to move away from data frame terminology in Stack Docs

docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc, docs/en/stack/redirects.asciidoc
Related to https://github.com/elastic/docs/pull/1220
This PR cleans up some deleted pages now that redirects exist.
It also re-adds an anchor that was mistakenly removed in earlier PRs.
=> Removes deleted pages for transforms

docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc
Related to https://github.com/elastic/stack-docs/pull/544
This PR backports link fixes for content that moved from the Stack Overview to the Elasticsearch Guide. It does not, however, remove the deleted pages.
=> Fixes transform links

docs/en/stack/index.asciidoc, docs/en/stack/introduction.asciidoc, docs/en/stack/redirects.asciidoc
Backports https://github.com/elastic/stack-docs/pull/546/
Depends on https://github.com/elastic/kibana/pull/46871 and https://github.com/elastic/elasticsearch/pull/47255
=> [7.x] Removes Watcher from Stack Overview (#546)

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR removes the coming[7.4.0] tags from the Installation and Upgrade Guide.
=> Removes coming tags from Installation Guide

docs/en/stack/redirects.asciidoc, docs/en/stack/security/index.asciidoc
This PR is one of several staged PRs related to #46880
This PR creates deleted pages in the Stack Overview for content that was previously being pulled from
from https://github.com/elastic/elasticsearch/tree/master/x-pack/docs/en/security
=> Stages removal of security content

docs/en/siem/machine-learning.asciidoc
Dev correction for ML job description.
Removed second paragraph as it was inaccurate and did not add anything to the first one.
=> [Docs] Corrects SIEM linux_anomalous_network_service job description

docs/en/siem/machine-learning.asciidoc
Dev correction for ML job description.
Backport: #587
=> [Docs] [Backport] Corrects linux_anomalous_network_service job description

docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc, docs/en/stack/ml/anomaly-detection/examples.asciidoc, docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/job-tips.asciidoc, docs/en/stack/ml/anomaly-detection/jobs.asciidoc, docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc, docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc, docs/en/stack/ml/anomaly-detection/overview.asciidoc, docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc, docs/en/stack/redirects.asciidoc
Applies the changes of the following commit to 7.x:
[DOCS] Revamps the Anomaly Detection section #548
The doc build is failing because the Kibana 7.x contains a link redirect in [`redirects.asciidoc`](https://github.com/elastic/kibana/blob/7.x/docs/redirects.asciidoc#machine-learning-job-tips) that points to `job-tips.html` which is not available (in this form) anymore in the Stack Overview due to the changes of this PR.
I opened a PR in the Kibana repo to amend the job-tips redirect accordingly. Naturally, the docs test is failing on that, too, because the changes of this PR in the stack docs are not applied yet.
Related PR: https://github.com/elastic/kibana/pull/47569
=> [7.x] [DOCS] Revamps Anomaly Detection section

docs/en/install-upgrade/highlights.asciidoc
Credit to Gail for spotting this. It's uncommented in `master` and `7.3`, but not here.
=> [docs] Uncomment APM highlights link

docs/en/stack/ml/anomaly-detection/index.asciidoc
This PR removes an unnecessary menu link from the Anomaly Detection index section.
=> [7.x] [DOCS] Fixes TOC in the anomaly detection index

docs/en/stack/redirects.asciidoc, docs/en/stack/security/authentication/active-directory-realm.asciidoc, docs/en/stack/security/authentication/index.asciidoc, docs/en/stack/security/authentication/ldap-realm.asciidoc, docs/en/stack/security/authorization/index.asciidoc, docs/en/stack/security/get-started-security.asciidoc, docs/en/stack/security/index.asciidoc
=> [6.7] Stages removal of security content 

docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc, docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc
This PR backports the following commit to the 7.3 branch (in a slightly changed form, as regression analysis is not available in 7.3):
[DOCS] Marks DFA and the related analytics types as experimental feataures #619
=> [7.3] [DOCS] Marks DFA and the related analytics types as experimental features

docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc, docs/en/stack/ml/df-analytics/dfa-regression.asciidoc, docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
This PR reorganizes the ML Data Frame Analytics section to align with the ML feature template.
Related issue: https://github.com/elastic/stack-docs/issues/608
[ML feature template](https://raw.githubusercontent.com/elastic/stack-docs/master/docs/en/stack/ml/doc-template/ml-feature-template.asciidoc)
Preview: http://stack-docs_613.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/master/ml-dfanalytics.html
=> [DOCS] Revamps Data Fame Analytics section

docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc, docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
This PR backports the changes of the following commit: 
[DOCS] Revamps Data Fame Analytics section #613
Preview: http://stack-docs_635.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/7.3/index.html
=> [7.3] [DOCS] Revamps Data Frame Analytics section

docs/en/siem/siem-ui.asciidoc
Adds a short note about displaying connection lines on the SIEM map.
[Preview](http://stack-docs_648.docs-preview.app.elstc.co/guide/en/siem/guide/master/conf-map-ui.html)
=> [SIEM] [Docs] Adds note about map connection lines

docs/en/logs/page_header.html, docs/en/metrics/page_header.html
Due to the way the build process works, the new Logs Monitoring Guide and Metrics monitoring Guide docs are included as current docs at v7.5. 
This PR adds a banner pointing readers to the actual current doc (the V7.4 infrastructure Monitoring Guide).
This needs to be back ported to the 7.5 and 7.x branches and reverted in all these branches when 7.5 docs are released.
=> [DOCS] Adding temporary banner to mark Logs and Metrics docs as "future"

docs/en/logs/page_header.html, docs/en/metrics/page_header.html
Backports the following commits to 7.5:
- Adding temporary banner to mark current version of logs monitoring guide as "future" (#655)
=> [7.5] Adding temporary banner to mark current version of logs monitoring guide as "future" (#655)

docs/en/logs/page_header.html, docs/en/metrics/page_header.html
- Adding temporary banner to mark current version of logs monitoring guide as "future" (#655)
=> [7.x] Adding temporary banner to mark current version of logs monitoring guide as "future" (#655)

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR backports the changes in the following commit to 7.3:
[DOCS] Renames limitation items in DFA limitations #638
=> [7.3][DOCS] Renames limitation items in DFA limitations

docs/en/getting-started/docker-compose.yml, docs/en/getting-started/docker/.env, docs/en/getting-started/docker/create-certs.yml, docs/en/getting-started/docker/docker-compose.yml, docs/en/getting-started/docker/elastic-docker-tls.yml, docs/en/getting-started/docker/instances.yml, docs/en/getting-started/get-started-docker.asciidoc
Uses a compose file that launches 3 nodes + Kibana. 
Related to #455
=> [DOCS] Added instructions for 3 nodes + kibana

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
This PR adds classification conceptual documentation to the data frame analytics docs.
Related issue: https://github.com/elastic/stack-docs/issues/629
Depends on https://github.com/elastic/docs/pull/1260 (attributes)
=> [DOCS] Adds classification and classification evaluation conceptual documentation

docs/en/getting-started/get-started-stack.asciidoc, docs/en/logs/index.asciidoc, docs/en/logs/logs-overview.asciidoc, docs/en/metrics/index.asciidoc, docs/en/metrics/infra-ui-intro.asciidoc, docs/en/metrics/metrics-overview.asciidoc
- Renaming references to Infrastructure app to Metrics where appropriate. (#661)
=> [7.x] Renaming references to Infrastructure app to Metrics where appropriate. (#661)

docs/en/getting-started/get-started-stack.asciidoc, docs/en/logs/index.asciidoc, docs/en/logs/logs-overview.asciidoc, docs/en/metrics/index.asciidoc, docs/en/metrics/infra-ui-intro.asciidoc, docs/en/metrics/metrics-overview.asciidoc
Backports the following commits to 7.5:
- Renaming references to Infrastructure app to Metrics where appropriate. (#661)
=> [7.5] Renaming references to Infrastructure app to Metrics where appropriate. (#661)

docs/en/install-upgrade/breaking.asciidoc
This PR makes the Kibana 7.5 breaking changes (https://www.elastic.co/guide/en/kibana/7.5/breaking-changes-7.5.html) appear successfully in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/7.5/kibana-breaking-changes.html).
Preview: http://stack-docs_684.docs-preview.app.elstc.co/guide/en/elastic-stack/7.5/kibana-breaking-changes.html
=> [DOCS] Adds Kibana 7.5 breaking changes

docs/en/stack/license.asciidoc
Fixes https://github.com/elastic/kibana/issues/18386
by adding a Kibana section to the following page:
https://www.elastic.co/guide/en/elastic-stack-overview/master/license-expiration.html
Preview: http://stack-docs_685.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/master/license-expiration.html
=> [DOCS] Adds Kibana expiration behaviour

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Updates the placeholder links to reflect the new path to Beats breaking changes and highlights.
commented-out for now.
=> [7.x] Update Beats BC and highlights links

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR expands the data frame analytics limitation sections with the supported field types for classification.
=> [DOCS] Adds classification field type description to the DFA limitations

docs/en/stack/index.asciidoc
This PR removes references to the Kibana and Beats repos from the Stack Overview, since those dependencies are no longer required.
=> Removes unnecessary repo dependencies

docs/en/install-upgrade/page_header.html
Related to elastic/docs#1426
This PR adds a banner to the Installation and Upgrade Guide.
Preview: http://stack-docs_695.docs-preview.app.elstc.co/guide/en/elastic-stack/6.2/index.html
=> Adds EOL banner in Installation and Upgrade Guide

docs/en/stack/ml/df-analytics/examples.asciidoc, docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
This PR adds a regression example to the data frame analytics documentation section.
Related issue: https://github.com/elastic/ml-team/issues/237
=> [DOCS] Adds regression example

docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
This PR fixes some minor typographic errors in the classification example.
=> [DOCS] Fixes typos in the classification example

docs/en/logs/page_header.html, docs/en/metrics/page_header.html
DO NOT MERGE UNTIL 7.5 RELEASE DAY!
https://github.com/elastic/stack-docs/pull/655 added a "docs for a future release" banner to the new v7.5 docs, Logs Monitoring Guide and Metrics Monitoring Guide (on branches master, 7.5 and 7.x)
When v7.5 docs are published, this banner needs to be removed from all three branches. This PR removes the headers from the master branch. It also needs to be back ported to 7.5 and 7.x.
=> [DOCS] [FOR 7.5] Remove temporary "future docs" banner from 7.5 release docs

docs/en/infraops/page_header.html
DO NOT MERGE UNTIL 7.4 IS NO LONGER THE CURRENT RELEASE!
At the same time, also needs to be back ported to all earlier branches in which this doc exists (7.3 down to 6.5)
=> [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide

docs/en/logs/page_header.html, docs/en/metrics/page_header.html
- DO NOT CHECK IN BEFORE v7.5 RELEASE DAY. Removing temporary "future docs" page headers, ready for v7.5 docs. (#658)
=> [7.x] Removes temporary "future docs" page headers (#658)

docs/en/logs/page_header.html, docs/en/metrics/page_header.html
Backports the following commits to 7.5:
- DO NOT CHECK IN BEFORE v7.5 RELEASE DAY. Removing temporary "future docs" page headers, ready for v7.5 docs. (#658)
=> [7.5] Removes temporary "future docs" page headers (#658)

docs/en/infraops/page_header.html
Backports the following commits to 6.5:
=> [6.5] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)

docs/en/infraops/page_header.html
Backports the following commits to 6.6:
=> [6.6] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)

docs/en/infraops/page_header.html
Backports the following commits to 6.7:
=> [6.7] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)

docs/en/infraops/page_header.html
Backports the following commits to 6.8:
=> [6.8] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)

docs/en/infraops/page_header.html
Backports the following commits to 7.0:
=> [7.0] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)

docs/en/infraops/page_header.html
Backports the following commits to 7.1:
=> [7.1] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)

docs/en/infraops/page_header.html
Backports the following commits to 7.2:
=> [7.2] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)

docs/en/infraops/page_header.html
Backports the following commits to 7.3:
=> [7.3] [DOCS] [FOR 7.5] Add superseded banner to older versions of Infrastructure Monitoring Guide (#654)

docs/en/getting-started/page_header.html, docs/en/install-upgrade/page_header.html, docs/en/stack/page_header.html
Related to https://github.com/elastic/docs/pull/1426
This PR adds a banner to the Stack Overview, Installation and Upgrade Guide, and Getting Started Guide. 
NOTE: This PR should not be merged until after 7.5.0 is released.
Preview:
http://stack-docs_694.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/7.4/index.html
http://stack-docs_694.docs-preview.app.elstc.co/guide/en/elastic-stack-get-started/7.4/index.html
http://stack-docs_694.docs-preview.app.elstc.co/guide/en/elastic-stack/7.4/index.html
=> Adds OOM banners in stack books

docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
This PR adds a section title to the paragraph about regression models in the regression conceptual documentation. This makes it easier to link directly to the section about the used model.
Preview: http://stack-docs_723.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/master/dfa-regression.html
=> [DOCS] Puts regression model info into a separated section

docs/en/siem/siem-ui.asciidoc
Fixes incorrect ECS field name in the [Configuring map data](https://www.elastic.co/guide/en/siem/guide/7.5/conf-map-ui.html) page.
=> [SIEM] [Docs] Fixes ecs field name in map connection lines note

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR adds a new limitation item to the data frame analytics limitation section about the possible runtime of the analytics jobs.
=> [DOCS] Expands DFA limitations section with runtime paragraph

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
This PR changes the title of the section about algorithms in the classification docs to be in line with the same section of the regression docs.
Related PR: https://github.com/elastic/stack-docs/pull/723
=> [DOCS] Changes section title in classification conceptual docs

docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
This PR changes a section title in the regression conceptual doc to be in line with the classification doc structure. See https://github.com/elastic/stack-docs/pull/727
=> [DOCS] Fine-tunes regression docs section titles

docs/en/stack/index.asciidoc, docs/en/stack/redirects.asciidoc
Backports https://github.com/elastic/stack-docs/pull/464
=> [7.2][DOCS] Remove CCR docs from Stack Overview (#464)

docs/en/getting-started/page_header.html, docs/en/install-upgrade/page_header.html, docs/en/stack/page_header.html
Explicitly set page_header.html for 6.8 so that the default notice can be updated for OOM versions. 
Prerequisite for:  https://github.com/elastic/docs/pull/1528
=> [DOCS] Added older release notice.

docs/en/stack/page_header.html
Instead of explicitly setting page_header.html for every OOM version, we're updating the default notice so it doesn't have to be set manually every release. 
Relates to: https://github.com/elastic/docs/pull/1528
=> [DOCS] Remove custom page_header.html

docs/en/stack/index.asciidoc, docs/en/stack/redirects.asciidoc
Backports https://github.com/elastic/stack-docs/pull/464
=> [6.5][DOCS] Remove CCR docs from Stack Overview (#464)

docs/en/stack/index.asciidoc, docs/en/stack/redirects.asciidoc
Backports https://github.com/elastic/stack-docs/pull/464
Depends on https://github.com/elastic/elasticsearch/pull/49954
=> [6.6][DOCS] Remove CCR docs from Stack Overview (#464)

docs/en/siem/installation.asciidoc, docs/en/siem/siem-ui.asciidoc
Adds additional clarifications on index requirements in general and, specifically, for maps configuration.
[Map configuration page preview](http://stack-docs_739.docs-preview.app.elstc.co/guide/en/siem/guide/master/conf-map-ui.html)
Requested in [#52312](https://github.com/elastic/kibana/issues/52312).
=> [SIEM][Docs]Clarifies SIEM index and Kibana index pattern requirements

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR removes a link that refers to the hyperparameter optimization section of the DFA resources page. As https://github.com/elastic/elasticsearch/pull/50021 will remove this page, the PR is failing because of the link in the Limitations section.
After the above-mentioned PR is merged, the link will be replaced with the new one.
=> [DOCS] Removes link refering to hyperparameter optimization in Limitations

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR puts back a link that points to hyperparameter optimization to the Limitations section. The description of hyperparameter optimization is moved to another page in a PR listed below. To make the PR pass on the CI tests, the link must be removed. This PR puts the link back with its new URL.
ONLY MERGE AFTER https://github.com/elastic/elasticsearch/pull/50021 IS MERGED.
(CI will fail until that PR is merged.)
Related PRs: 
* https://github.com/elastic/elasticsearch/pull/50021
* https://github.com/elastic/stack-docs/pull/750
=> [DOCS] Adds link refering to hyperparameter optimization to Limitations

docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
This PR adds a link to the classification example that points to the companion Jupyter notebook on GitHub.
Related issue: https://github.com/elastic/ml-team/issues/187#issuecomment-566532097
=> [DOCS] Adds Jupyter noetbook link to the classification example

docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc
This PR adds a link to the outlier detection example that points to a Jupyter notebook on GitHub.
=> [DOCS] Adds a Jupyter notebook link to the outlier detection example

docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc, docs/en/stack/ml/anomaly-detection/model-snapshots.asciidoc
The model snapshot resources definition page (https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-snapshot-resource.html) was deleted in https://github.com/elastic/elasticsearch/pull/50157, but there is some conceptual information there that is worth saving.
This PR adds this type of content to the machine learning content in the Stack Overview instead.
Preview: http://stack-docs_755.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/master/ml-model-snapshots.html
=> Add conceptual overview of model snapshots

docs/en/stack/ml/df-analytics/examples.asciidoc
This PR adds two links pointing to Jupyter notebook to the DFA example page.
Preview: http://stack-docs_765.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/master/dfanalytics-examples.html
=> [DOCS] Adds Jupyter notebook links to the example page

docs/en/stack/index.asciidoc, docs/en/stack/redirects.asciidoc
Depends on https://github.com/elastic/docs/pull/1662
This PR creates redirects for all of the machine learning pages in the Stack Overview.
=> [DOCS] Removes ML content from Stack Overview

docs/60_upgrade_guide.html, docs/en/siem/machine-learning.asciidoc, docs/en/siem/tune-anomaly-results.asciidoc, docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc
Related to elastic/stack-docs#777
This PR updates links to machine learning content so that they point to the appropriate book (https://www.elastic.co/guide/en/machine-learning/master/index.html instead of https://www.elastic.co/guide/en/elastic-stack-overview/master/index.html).
=> [DOCS] Fixes machine learning links

docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
This PR adds a "how it works" piece to the DFA overview section that explains the four phases of a data frame analytics job. 
(approx. 500 words)
Preview available here: http://stack-docs_754.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/master/ml-dfa-phases.html
=> [DOCS] Adds how DFA jobs work section

docs/en/siem/machine-learning.asciidoc
Adds the ECS fields required to run each ML job. When a job uses a beats-specific field, I've added a note stating the job can only be run when data is shipped via beats.
@randomuserid - [here's the preview](http://stack-docs_738.docs-preview.app.elstc.co/guide/en/siem/guide/master/prebuilt-ml-jobs.html).
Resolves #724
=> Adds ecs fields for ml jobs

docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc, docs/en/stack/ml/df-analytics/ml-inference.asciidoc
This PR adds the conceptual documentation of the inference feature to the machine learning book.
Preview: http://stack-docs_758.docs-preview.app.elstc.co/guide/en/elastic-stack-overview/master/ml-inference.html
Related issue: https://github.com/elastic/stack-docs/issues/691
PR for new attributes: https://github.com/elastic/docs/pull/1616
**NOTE**
Only merge this PR after https://github.com/elastic/elasticsearch/pull/50204 is merged. This PR contains a link pointing to the processor documentation. The CI here will pass after the processor docs are merged.
=> [DOCS] Adds inference conceptual documentation

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR removes a link from the limitation page in order to get the green light for merging:
https://github.com/elastic/elasticsearch/pull/50697
=> [7.5][DOCS] Remove hyperparam optimization link from DFA limitations

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR adds a link pointing to the definition of hyperparameter optimization to one of the limitations items on the DFA limitation page.
=> [7.5][DOCS] Adds hyperparameter optimization link to limitation text

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Removes link pointing to hyperparameter optimization from one of the limitation items in order to get green CI test on https://github.com/elastic/elasticsearch/pull/50704.
=> [DOCS] Removes hyperparm link from DFA limitations

docs/en/metrics/aws-ec2-metricset.asciidoc, docs/en/metrics/aws-rds-metricset.asciidoc, docs/en/metrics/aws-s3-metricset.asciidoc, docs/en/metrics/aws-sqs-metricset.asciidoc, docs/en/metrics/docker-metricset.asciidoc, docs/en/metrics/host-metricset.asciidoc, docs/en/metrics/index.asciidoc, docs/en/metrics/infrastructure-metrics.asciidoc, docs/en/metrics/kubernetes-metricset.asciidoc
This PR re-organizes the "Infrastructure metrics" page to support linking to multiple sub pages for details about the fields we use for each of the metricsets. The original layout had everything on the same page. Breaking this up will allow us to document the ever growing lists of metricsets.
=> [Metrics UI] Update docs with AWS Metricset fields

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Adds a link pointing to the hyperparameter optimization section in PUT DFA API to the data frame analytics runtime related limitation item.
=> [DOCS] Adds hyperparameter optimization link to a DFA limitation item text

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR adds a paragraph about the inference limitation regarding nested objects to the limitation pool.
Preview: http://stack-docs_791.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html#dfa-inference-nested-limitation
=> [DOCS] Adds nested objects related inference limitation

docs/en/install-upgrade/upgrading-stack.asciidoc, docs/en/stack/ml/anomaly-detection/calendars.asciidoc, docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc, docs/en/stack/ml/anomaly-detection/getting-started-multi.asciidoc, docs/en/stack/ml/anomaly-detection/getting-started-single.asciidoc, docs/en/stack/ml/anomaly-detection/job-tips.asciidoc, docs/en/stack/ml/anomaly-detection/jobs.asciidoc, docs/en/stack/ml/anomaly-detection/limitations.asciidoc, docs/en/stack/ml/anomaly-detection/troubleshooting.asciidoc
This PR fixes links to pages that have been deleted from the Elasticsearch Reference. They currently do not generate build errors because there are entries for them in https://github.com/elastic/elasticsearch/blob/master/docs/reference/redirects.asciidoc
=> [DOCS] Fixes out-dated links

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR adds a limitation item about imbalanced class sizes to the limitation section and mentions the issue in the classification conceptual documentation.
Docs preview: http://stack-docs_806.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html
=> [DOCS] Documents imbalanced class sizes and their effect on classification

docs/en/stack/ml/anomaly-detection/limitations.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/49889
This PR documents a limitation in machine learning anomaly detection related to date_nano data types.
Preview: http://stack-docs_815.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-limitations.html#ml-limitations-nanos
=> [DOCS] Adds ML limitation for date_nanos

docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
This PR adds a one-sentence description of classification to the Overview section.
=> [DOCS] Adds one-liner description of classification to the overview page

docs/en/stack/ml/anomaly-detection/datafeeds.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/50389 and https://github.com/elastic/elasticsearch/pull/51280
This PR augments the "datafeed" conceptual topic (https://www.elastic.co/guide/en/machine-learning/master/ml-dfeeds.html) with information about queries, query delays, aggregations, and frequency intervals. 
Preview: http://stack-docs_810.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfeeds.html
=> [DOCS] Augment datafeed overview

docs/en/stack/ml/anomaly-detection/architecture.asciidoc, docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc, docs/en/stack/ml/index.asciidoc, docs/en/stack/ml/setup.asciidoc, docs/en/stack/redirects.asciidoc
This PR creates a new page in the Machine Learning book for setup instructions.
This information was previously included in the getting started tutorial (https://github.com/elastic/stack-docs/pull/225) but it seems like a good idea to separate it out. There was also a "Machine learning nodes" page nested under the Anomaly Detection concepts, but this change makes it redundant.
The subsection about security privileges can be expanded in subsequent PRs depending on the level of detail required.
Preview: http://stack-docs_818.docs-preview.app.elstc.co/guide/en/machine-learning/master/setup.html
=> [DOCS] Adds machine learning setup page

docs/en/siem/detection-engine-intro.asciidoc
Adds the UI permissions that can be displayed on the Detections page to the documentation.
[Preview](http://stack-docs_821.docs-preview.app.elstc.co/guide/en/siem/guide/master/detection-engine-overview.html#detections-permissions)
=> [Docs][SIEM]Adds Detections UI permission error messages

docs/en/stack/ml/df-analytics/examples.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc, docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
This PR adds language identification conceptual documentation to the machine learning data frame analytics chapter.
**Do not merge this PR before https://github.com/elastic/docs/pull/1706 is merged.**
Related issue: https://github.com/elastic/ml-team/issues/279
Preview: http://stack-docs_816.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-lang-ident.html
=> [DOCS] Adds language identification documentation to the ML DFA docs

docs/en/stack/ml/anomaly-detection/forecasting.asciidoc, docs/en/stack/ml/anomaly-detection/limitations.asciidoc
There is a list of forecast limitations in the anomaly detection overview (https://www.elastic.co/guide/en/machine-learning/master/ml-overview.html), which are partially duplicated in the anomaly detection limitations (e.g. https://www.elastic.co/guide/en/machine-learning/master/ml-limitations.html#_forecasts_cannot_be_created_for_population_jobs).
This PR moves the full list of forecast-related limitations into the Limitations page and links to it from the overview.
=> [DOCS] Moves forecast limitations out of overview

docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc
This PR adds a one-sentence long description of inference to the data frame analytics overview page.
Preview: http://stack-docs_829.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-overview.html
=> [DOCS] Adds one liner about inference to the DFA overview page

docs/en/stack/ml/df-analytics/ml-inference.asciidoc
This PR adds a short description of language identification with a link to the inference conceptual docs.
Preview: http://stack-docs_830.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-inference.html
=> [DOCS] Adds a paragraph about language identification to the inference conceptual docs

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Do not merge until after https://github.com/elastic/beats/pull/15663 is merged and backported.
=> [docs] Include Beats breaking changes and release highlights

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR fixes the files that are pulled into the Installation and Upgrade Guide for the Elasticsearch release highlights and breaking changes.
Preview: http://stack-docs_834.docs-preview.app.elstc.co/guide/en/elastic-stack/7.6/elasticsearch-highlights.html
=> [DOCS] Fixes Elasticsearch release highlights and breaking changes

docs/en/stack/ml/df-analytics/ml-inference.asciidoc, docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
This PR updates the introductory sentence of the language identification example (https://www.elastic.co/guide/en/machine-learning/7.6/ml-lang-ident.html).
=> [DOCS] Fixes trained model terminology

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/dfa-regression.asciidoc, docs/en/stack/ml/shared-ml-concepts.asciidoc
This PR gives a high-level explanation of what feature importance is and adds the definition to the regression and classification docs.
Preview: http://stack-docs_844.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-classification.html
and
http://stack-docs_844.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-regression.html
=> [DOCS] Adds feature importance to regression and classification docs

docs/en/stack/ml/df-analytics/ecommerce-outliers.asciidoc, docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc
This PR collapse the API snippets in the machine learning outlier detection example (https://www.elastic.co/guide/en/machine-learning/master/ecommerce-outliers.html).
It also clarifies an acronym in the regression example.
=> [DOCS] Collapses APIs in outlier example

docs/en/install-upgrade/highlights.asciidoc
Related to https://github.com/elastic/kibana/pull/57160
This PR adds the notable Kibana 7.6.0 release highlights to the Installation and Upgrade Guide.
Preview: http://stack-docs_867.docs-preview.app.elstc.co/guide/en/elastic-stack/7.6/kibana-higlights.html
=> [DOCS] Adds Kibana 7.6.0 highlights

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
**Blocked by https://github.com/elastic/apm-server/pull/3282**.
Cherrypick to `7.x` and `master`.
=> [7.6][docs] Add APM tagged regions for 7.6.0

docs/en/siem/detection-engine-intro.asciidoc, docs/en/siem/installation.asciidoc, docs/en/siem/privileges-api-overview.asciidoc
- [Docs][SIEM]Updates for Detections configuration requirements and errors (#873)
=> [7.6] [Docs][SIEM]Updates for Detections configuration requirements and errors (#873)

docs/en/stack/ml/setup.asciidoc
This PR clarifies the list of security privileges that are required to use the machine learning features.
It currently contains the information in two formats (checklist and table) to get feedback on which is easiest to follow.
Preview: http://stack-docs_824.docs-preview.app.elstc.co/guide/en/machine-learning/master/setup.html#setup-privileges
=> [DOCS] Augments list of machine learning privileges

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Adds a new item to the DFA limitation section about possible performance effects of feature importance calculation.
Related issue: https://github.com/elastic/ml-team/issues/274#issuecomment-585262454
=> [DOCS] Adds DFA limitation regarding feature importance

docs/en/siem/detection-engine-intro.asciidoc
Adds HTTPS as a Detections requirement.
[Preview](http://stack-docs_882.docs-preview.app.elstc.co/guide/en/siem/guide/master/detection-engine-overview.html#detections-permissions)
=> [Docs][SIEM] Add https requirement to detections

docs/en/siem/detection-engine-intro.asciidoc
- [Docs][SIEM] Add https requirement to detections (#882)
=> [7.x] [Docs][SIEM] Add https requirement to detections (#882)

docs/en/siem/detection-engine-intro.asciidoc
- [Docs][SIEM] Add https requirement to detections (#882)
=> [7.6] [Docs][SIEM] Add https requirement to detections (#882)

docs/en/stack/ml/shared-ml-concepts.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/52246
This PR augments the description of feature importance in the classification and regression overview pages.
It also removes unnecessary "discrete" attributes so that we get links in the top right navigation for these long overview pages.
Preview:
* http://stack-docs_881.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-classification.html#dfa-classification-feature-importance
* http://stack-docs_881.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-regression.html#dfa-regression-feature-importance
=> [DOCS] Clarify feature importance values

docs/en/stack/ml/setup.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/52259
This PR updates the list of security privileges for machine learning, in particular related to the privilege that will no longer be required by the Kibana categorization job wizard.
=> [DOCS] Remove cluster privilege requirement

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Some of the limitation items are verbose. This PR tries to mitigate it by omitting parts that are not essential.
Preview: http://stack-docs_884.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html
=> [DOCS] Makes the DFA limitations section more succinct

docs/en/stack/ml/anomaly-detection/limitations.asciidoc
This PR adds a limitation to the machine learning anomaly detection documentation with respect to frozen indices. 
Related to https://github.com/elastic/elasticsearch/issues/48056
=> [DOCS] Adds ML limitation for frozen indices

docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
Adds `class_score` and its short explanation to the API response in the example.
=> [DOCS] Adds class_score to the classification example

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc
This PR adds an explanation of `class_probability` and `class_score` to the classification docs.
Preview: http://stack-docs_885.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-classification.html
=> [DOCS] Adds section to the classification docs that helps interpret results

docs/en/glossary/glossary.asciidoc
This PR adds the terms "feature importance" and "feature influence" to the Elastic Stack Glossary (https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html)
Preview: http://stack-docs_889.docs-preview.app.elstc.co/guide/en/elastic-stack-glossary/master/terms.html
=> [DOCS] Adds feature influence and importance to Glossary

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR adds documentation of the modules with prebuilt anomaly detection jobs.
Related issue: https://github.com/elastic/stack-docs/issues/708
Preview: http://stack-docs_843.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs.html
Source: https://github.com/elastic/kibana/tree/master/x-pack/legacy/plugins/ml/server/models/data_recognizer/modules
=> [DOCS] Adds a page that lists the modules with OOTB ML jobs

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR makes the monitored activity log types in the documentation more precise.
=> [DOCS] Fine-tunes monitored activity log types in OOTB ML jobs docs

docs/en/stack/ml/anomaly-detection/examples.asciidoc
This PR adds URLs of ML related blog posts to the anomaly detection example page.
Preview: http://stack-docs_905.docs-preview.app.elstc.co/guide/en/machine-learning/master/anomaly-examples.html
=> [DOCS] Adds ML related blog posts to the anomaly detection examples page

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR reorganizes the list of the prebuilt SIEM jobs by agent type. This way it is easier to navigate among the jobs.
Preview: http://stack-docs_906.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs.html
=> [DOCS] Reorganizes the OOTB SIEM jobs by agent type

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR changes the name of the "Prebuild anomaly detection jobs" page to "Supplied anomaly detection configurations" to be in line with the ML UI text. It also collects jobs in different categories to individual pages (Apache, APM, etc).
Preview:  http://stack-docs_909.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs.html
=> [DOCS] Renames OOTB jobs page and separates the categories to individual pages

docs/en/siem/tune-rule-signals.asciidoc
- corrects tuning prebuilt rules section title (#910)
=> [7.x] corrects tuning prebuilt rules section title (#910)

docs/en/siem/tune-rule-signals.asciidoc
- corrects tuning prebuilt rules section title (#910)
=> [7.6] corrects tuning prebuilt rules section title (#910)

docs/en/getting-started/get-started-stack.asciidoc, docs/en/install-upgrade/installing-stack.asciidoc, docs/en/logs/logs-installation.asciidoc, docs/en/metrics/installation.asciidoc, docs/en/siem/installation.asciidoc, docs/en/siem/machine-learning.asciidoc, docs/en/stack/ml/setup.asciidoc
This PR switches trial sign-up links over to the standard attribute we're introducing that should provide some metrics for how effective these links are.﻿
Details for the attribute are in https://github.com/elastic/docs/pull/1737, if you want to know more. 
@lcawl @szabosteve if you could review this PR, I would be grateful. I'd also appreciate any pointers you have for getting these changes into all the right branches.
=> Switch to standard ESS trial links

docs/en/siem/machine-learning.asciidoc
Winlogbeat was incorrectly listed in the suspicious_login_activity_ecs job description.
[Preview](http://stack-docs_908.docs-preview.app.elstc.co/guide/en/siem/guide/master/prebuilt-ml-jobs.html)
=> [Docs][SIEM]Removes winlogbeat from the suspicious_login_activity_ecs ml job description

docs/en/siem/machine-learning.asciidoc
- removes winlogbeat from linux ml job (#908)
=> [7.6] removes winlogbeat from linux ml job (#908)

docs/en/siem/machine-learning.asciidoc
- removes winlogbeat from linux ml job (#908)
=> [7.x] removes winlogbeat from linux ml job (#908)

docs/en/glossary/glossary.asciidoc, docs/en/stack/ml/anomaly-detection/influencers.asciidoc
This PR adds "influencer" to the Elastic Stack glossary (https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html). It also adds an additional sentence to the influencer overview in the Machine learning documentation (https://www.elastic.co/guide/en/machine-learning/current/ml-influencers.html). 
It also wraps some existing glossary entries to align with typical line lengths.
=> [DOCS] Adds influencer to Stack glossary

docs/en/stack/ml/df-analytics/examples.asciidoc
This PR adds URLs of ML related blog posts to the data frame analytics example page.
Preview: http://stack-docs_916.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfanalytics-examples.html
=> [DOCS] Adds ML related blog posts to the DFA examples page

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Adds limitation to data frame analytics explaining training on multi-field fields and how that affects inference.
Preview: http://stack-docs_920.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html
=> [ML] adding multi-field limitation for inference + analytics

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
- [ML] adding multi-field limitation for inference + analytics (#920)
=> [7.6] [ML] adding multi-field limitation for inference + analytics (#920)

docs/en/stack/ml/df-analytics/dfa-regression.asciidoc, docs/en/stack/ml/df-analytics/examples.asciidoc
This PR adds the link of a Jupyter notebook on feature importance to the DFA examples and the regression conceptual docs under Further readings.
Related issue: https://github.com/elastic/ml-team/issues/274#issuecomment-593481061
Preview: 
* [Examples page](http://stack-docs_919.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfanalytics-examples.html)
* [Regression docs](http://stack-docs_919.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-regression.html)
=> [DOCS] Adds feature importance Jupyter notebook to the examples and further readings

docs/en/siem/rules-api-bulk-actions.asciidoc, docs/en/siem/rules-api-create.asciidoc, docs/en/siem/rules-api-update.asciidoc
Describes using PATCH and PUT for updating detection engine rules. 
[Preview](http://stack-docs_921.docs-preview.app.elstc.co/guide/en/siem/guide/master/rules-api-update.html)
=> [Docs][SIEM]Adds PATCH method to update rule api

docs/en/siem/rules-api-bulk-actions.asciidoc, docs/en/siem/rules-api-create.asciidoc, docs/en/siem/rules-api-update.asciidoc
- [Docs][SIEM]Adds PATCH method to update rule api (#921)
=> [7.x] [Docs][SIEM]Adds PATCH method to update rule api (#921)

docs/en/siem/machine-learning.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
Updates links in the ML SIEM prebuilt jobs section so it can be included in the SIEM docs without breaking links.
=> [Docs][ML]Updates prebuilt ml jobs file links

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR adds links from the list of machine learning modules (https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs.html) to the location of the JSON definitions in the Kibana repo (https://github.com/elastic/kibana/tree/master/x-pack/plugins/ml/server/models/data_recognizer/modules).
It also removes comments related to those job details.
=> [DOCS] Adds links to ML module definitions in GitHub

docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
This PR changes the `field_mappings` resource name to `field_map` in the language identification example.
Related PR: https://github.com/elastic/elasticsearch/pull/53433
=> [DOCS] Changes field_mappings to field_map in lang ident example

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc, docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
This PR appends tags to the algorithm description sections of the different data frame analytics types. These tags will make it easier to re-use the information in another context via single-sourcing.
Preview: 
* outlier detection: http://stack-docs_941.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-outlier-detection.html
* classification: http://stack-docs_941.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-classification.html
=> [DOCS] Adds tags to the sections about the used algorithms of the different DFA types

docs/en/siem/privileges-api-overview.asciidoc, docs/en/siem/rules-api-create.asciidoc, docs/en/siem/rules-api-update.asciidoc
- fixes rules privileges example and typo (#947)
=> [7.x] fixes rules privileges example and typo (#947)

docs/en/siem/privileges-api-overview.asciidoc, docs/en/siem/rules-api-create.asciidoc, docs/en/siem/rules-api-update.asciidoc
- fixes rules privileges example and typo (#947)
=> [7.6] fixes rules privileges example and typo (#947)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR adds the Elastic Uptime machine learning job to the list of supplied configurations (https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs.html).
Preview: http://stack-docs_961.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-uptime.html
=> [DOCS] Adds Elastic Uptime anomaly detection job

docs/en/siem/index-api-overview.asciidoc, docs/en/siem/installation.asciidoc, docs/en/siem/privileges-api-overview.asciidoc, docs/en/siem/rules-api-bulk-actions.asciidoc, docs/en/siem/rules-api-create.asciidoc, docs/en/siem/rules-api-delete.asciidoc, docs/en/siem/rules-api-export.asciidoc, docs/en/siem/rules-api-find.asciidoc, docs/en/siem/rules-api-get.asciidoc, docs/en/siem/rules-api-import.asciidoc, docs/en/siem/rules-api-overview.asciidoc, docs/en/siem/rules-api-prebuilt.asciidoc, docs/en/siem/rules-api-update.asciidoc, docs/en/siem/signals-api-overview.asciidoc, docs/en/siem/tags-api-overview.asciidoc
- [Docs][SIEM]General doc improvements  (#957)
=> [7.x] [Docs][SIEM]General doc improvements  (#957)

docs/en/siem/case-api-update-connector.asciidoc, docs/en/siem/cases-api-add-comment.asciidoc, docs/en/siem/cases-api-assign-connector.asciidoc, docs/en/siem/cases-api-associate-sn.asciidoc, docs/en/siem/cases-api-create.asciidoc, docs/en/siem/cases-api-delete-all-comments.asciidoc, docs/en/siem/cases-api-delete-case.asciidoc, docs/en/siem/cases-api-delete-comment.asciidoc, docs/en/siem/cases-api-find-cases.asciidoc, docs/en/siem/cases-api-find-connectors.asciidoc, docs/en/siem/cases-api-get-case-activity.asciidoc, docs/en/siem/cases-api-get-case-comments.asciidoc, docs/en/siem/cases-api-get-case.asciidoc, docs/en/siem/cases-api-get-comment.asciidoc, docs/en/siem/cases-api-get-connector.asciidoc, docs/en/siem/cases-api-get-reporters.asciidoc, docs/en/siem/cases-api-get-status.asciidoc, docs/en/siem/cases-api-get-tags.asciidoc, docs/en/siem/cases-api-update-comment.asciidoc, docs/en/siem/cases-api-update.asciidoc, docs/en/siem/cases-api.asciidoc, docs/en/siem/cases-kbn-actions-api.asciidoc, docs/en/siem/cases-overview.asciidoc, docs/en/siem/index.asciidoc
- [SIEM] [Docs] Cases API (#761)
=> [7.7] [SIEM] [Docs] Cases API (#761)

docs/en/siem/rules-ui-create.asciidoc, docs/en/siem/siem-ui.asciidoc
Adds info about importing/exporting timelines and configuring displayed reputation links on IP detail pages.
[Timeline preview](http://stack-docs_981.docs-preview.app.elstc.co/guide/en/siem/guide/master/siem-ui-overview.html#import-export-timelines)
[Reputation links preview](http://stack-docs_981.docs-preview.app.elstc.co/guide/en/siem/guide/master/siem-ui-overview.html#network-ui)
=> [Docs][SIEM] 7.7 timeline and reputation link updates

docs/en/siem/rules-api-create.asciidoc, docs/en/siem/rules-api-update.asciidoc
Updates the rules API docs for creating ml rules.
[Preview](http://stack-docs_983.docs-preview.app.elstc.co/guide/en/siem/guide/master/rules-api-create.html)
=> [Docs][SIEM]Rules API ml rule type

docs/en/install-upgrade/highlights.asciidoc
Related to https://github.com/elastic/kibana/pull/63748
This PR uncomments the Kibana 7.7.0 release highlights in the Installation and Upgrade Guide.
Preview: http://stack-docs_995.docs-preview.app.elstc.co/guide/en/elastic-stack/7.7/kibana-higlights.html
=> [DOCS] Uncomments Kibana release highlights

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR adds a new limitation item to the DFA limitations list about the backward compatibility of the inference trained models created in 7.8.0.
Merge this PR only after https://github.com/elastic/elasticsearch/pull/55260 merged.
=> [DOCS] Adds limitation item about inference trained model backward compatibility

docs/en/siem/detection-engine-intro.asciidoc
Adds the `manage` cluster privilege, required when visiting Detections for the first time.
[Preview](http://stack-docs_1003.docs-preview.app.elstc.co/guide/en/siem/guide/master/detection-engine-overview.html#_resolve_ui_error_messages)
=> [Docs][SIEM]Corrects required detections privileges

docs/en/siem/detection-engine-intro.asciidoc
- [Docs][SIEM]Corrects required detections privileges (#1003)
=> [7.7] [Docs][SIEM]Corrects required detections privileges (#1003)

docs/en/siem/detection-engine-intro.asciidoc
- [Docs][SIEM]Corrects required detections privileges (#1003)
=> [7.6] [Docs][SIEM]Corrects required detections privileges (#1003)

docs/en/siem/cases-kbn-actions-api.asciidoc, docs/en/siem/cases-overview.asciidoc, docs/en/siem/cases-ui-integrations.asciidoc, docs/en/siem/detection-engine-intro.asciidoc, docs/en/siem/installation.asciidoc, docs/en/siem/overview.asciidoc, docs/en/siem/privileges-api-overview.asciidoc, docs/en/siem/rules-api-create.asciidoc, docs/en/siem/rules-ui-create.asciidoc, docs/en/siem/tune-anomaly-results.asciidoc, docs/en/siem/tune-rule-signals.asciidoc
Fixes typos and grammatical errors in the SIEM docs
=> [Docs][SIEM]General proofing and editing

docs/en/siem/rules-api-overview.asciidoc
- adds link to postman collection example (#1034)
=> [7.7] adds link to postman collection example (#1034)

docs/en/siem/rules-api-overview.asciidoc
- adds link to postman collection example (#1034)
=> [7.6] adds link to postman collection example (#1034)

docs/en/siem/rule-details/adversary-behavior-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/credential-dumping-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/credential-dumping-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/credential-manipulation-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/credential-manipulation-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/exploit-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/exploit-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/malware-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/malware-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/permission-theft-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/permission-theft-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/process-injection-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/process-injection-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/ransomware-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/ransomware-prevented-elastic-endpoint.asciidoc
- updates prebuilt endpoint rules look back time (#1040)
=> [7.8] updates prebuilt endpoint rules look back time (#1040)

docs/en/siem/rule-details/adversary-behavior-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/credential-dumping-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/credential-dumping-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/credential-manipulation-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/credential-manipulation-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/exploit-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/exploit-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/malware-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/malware-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/permission-theft-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/permission-theft-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/process-injection-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/process-injection-prevented-elastic-endpoint.asciidoc, docs/en/siem/rule-details/ransomware-detected-elastic-endpoint.asciidoc, docs/en/siem/rule-details/ransomware-prevented-elastic-endpoint.asciidoc
- updates prebuilt endpoint rules look back time (#1040)
=> [7.7] updates prebuilt endpoint rules look back time (#1040)

docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc, docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc, docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
This PR reviews and amends the footnotes in the ML book to make them less verbose.
[Classification example](http://stack-docs_1028.docs-preview.app.elstc.co/guide/en/machine-learning/master/flightdata-classification.html)
[Regression example](http://stack-docs_1028.docs-preview.app.elstc.co/guide/en/machine-learning/master/flightdata-regression.html)
[Language identification](http://stack-docs_1028.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-lang-ident.html)
=> [DOCS] Amends the footnotes in the ML book

docs/en/install-upgrade/breaking.asciidoc
This PR updates the link to the Kibana breaking changes in the Installation and Upgrade Guide.
Depends on https://github.com/elastic/kibana/pull/65591
=> [DOCS] Fix link to Kibana breaking changes

docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
This PR amends the phase description of the DFA jobs with the analysis type-specific sub-phases of the analyzing phase.
Related PR: https://github.com/elastic/elasticsearch/pull/56107
[How a data frame analytics job works](http://stack-docs_1038.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-phases.html)
=> [DOCS] Expands the analyzing phase with the analysis specific sub-phases

docs/en/getting-started/get-started-stack.asciidoc
This PR updates a tip on the "Getting Started with Elastic Stack" page about installing Kibana on the hosted Elasticsearch Service. 
Closes: https://github.com/elastic/stack-docs/issues/286
Preview: http://stack-docs_1056.docs-preview.app.elstc.co/guide/en/elastic-stack-get-started/master/get-started-elastic-stack.html#install-kibana
=> [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service

docs/en/getting-started/get-started-stack.asciidoc
- [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)
=> [7.6] [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)

docs/en/getting-started/get-started-stack.asciidoc
- [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)
=> [7.7] [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)

docs/en/getting-started/get-started-stack.asciidoc
- [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)
=> [7.8] [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)

docs/en/getting-started/get-started-stack.asciidoc
- [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)
=> [7.x] [DOCS] Clarify enabling Kibana on hosted Elasticsearch Service (#1056)

docs/en/stack/ml/anomaly-detection/model-snapshots.asciidoc
This PR updates the "Model snapshots" page with details about how long snapshots are retained. It also includes minor improvements to other sections of that page.
Related to https://github.com/elastic/elasticsearch/issues/52150
Preview: http://stack-docs_1047.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-model-snapshots.html
=> [DOCS] Update snapshot retention details

docs/en/siem/cases-kbn-actions-api.asciidoc, docs/en/siem/siem-ui.asciidoc
- [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)
=> [7.x] [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)

docs/en/siem/cases-kbn-actions-api.asciidoc, docs/en/siem/siem-ui.asciidoc
- [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)
=> [7.8] [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)

docs/en/siem/cases-kbn-actions-api.asciidoc, docs/en/siem/siem-ui.asciidoc
- [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)
=> [7.7] [Docs][SIEM]Adds link to beats pipeline example and corrects typo (#1065)

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/dfa-outlierdetection.asciidoc, docs/en/stack/ml/df-analytics/evaluatedf-api.asciidoc, docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc, docs/en/stack/ml/df-analytics/flightdata-regression.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc, docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc, docs/en/stack/ml/df-analytics/ml-inference.asciidoc, docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
This PR removes the [discrete] attributes from the DFA documentation pages (level 3 and below). With this change, the sub-section titles of the pages will appear on the right sidebar under the "On this page" header.
* [Classification](http://stack-docs_1070.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-classification.html)
* [Outlier detection](http://stack-docs_1070.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-outlier-detection.html)
* [DFA phases](http://stack-docs_1070.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-phases.html)
* [Evaluating DFA](http://stack-docs_1070.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfanalytics-evaluate.html)
* [Feature importance](http://stack-docs_1070.docs-preview.app.elstc.co/guide/ …
=> [DOCS] Removes [discrete] attributes from DFA docs

docs/en/stack/ml/anomaly-detection/buckets.asciidoc, docs/en/stack/ml/anomaly-detection/influencers.asciidoc
This PR removes the [discrete] attributes from the anomaly detection documentation pages (level 3 and below). With this change, the sub-section titles of the pages will appear on the right sidebar under the "On this page" header.
* [Buckets](http://stack-docs_1079.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-buckets.html)
* [Influencers](http://stack-docs_1079.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-influencers.html)
=> [DOCS] Removes [discrete] attributes from anomaly detection docs

docs/en/glossary/glossary.asciidoc
This PR fixes a mismatched ifdef ... endif pair in the Glossary.
=> [DOCS] Fix endif in Glossary

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc
This PR enables mathematical formulae in the data frame analytics chapter of the ML book and adds the required markup to the formula in the classification conceptual docs to render it correctly.
AsciiMath can be enabled by adding `:stem:` to the index.asciidoc of the chapter/book.
```
= Section title
:stem:
```
Use the following notation for the formulae:
```
stem:[sum_(i=1)^n i^3=((n(n+1))/2)^2]
```
For a centered block:
```
[stem]
++++
x/x={(1,if x!=0),(text{undefined},if x=0):}
++++
``` 
[Classification](http://stack-docs_1091.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-classification.html#dfa-classification-class-score)
=> [DOCS] Enables mathematical formulate in DFA chapter and adds markup to a formula

docs/en/stack/ml/anomaly-detection/job-tips.asciidoc
This PR adds a new section to the ML job tips page which contains a recommendation about the usage of dedicated results indices. 
As on the ML UI, the *Use dedicated index* option is near to the *model memory limit* settings, it seems appropriate to add the new section after the MML section in the tip docs. 
[ML job tips](http://stack-docs_1080.docs-preview.app.elstc.co/guide/en/machine-learning/master/create-jobs.html#job-tips)
=> [DOCS] Adds dedicated indices section to job tips with recommendation

docs/en/stack/ml/anomaly-detection/api-quickref.asciidoc
This PR changes the URL of the `/anomaly_detectors/` from
`/ml-apis.html#ml-api-job-endpoint`
to
`/ml-apis.html#ml-api-anomaly-job-endpoint`.
[API quick reference](http://stack-docs_1100.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-api-quickref.html)
=> [DOCS] Changes link in Anomaly Detection API quick reference

docs/en/stack/ml/anomaly-detection/limitations.asciidoc
This PR specifies that you can generate three forecasts per job.
[Forecasts limitations](url)
=> [DOCS] Expands forecast limitations

docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
This PR removes an outdated item from the DFA limitations list: `Analytics training on multi-field values may affect inference`.
https://github.com/elastic/elasticsearch/pull/53294 made it irrelevant.
=> [DOCS] Removes outdated inference related limitation item

docs/en/stack/redirects.asciidoc
Fixes broken link in https://github.com/elastic/stack-docs/pull/1106.
=> [7.8] Fix broken link to docs about configuring beats input in Logstash

docs/en/stack/redirects.asciidoc
Required to fix build error in https://github.com/elastic/stack-docs/pull/1105.
=> [7.x] Fix broken link to docs about configuring beats input in Logstash

docs/en/stack/ml/anomaly-detection/limitations.asciidoc, docs/en/stack/ml/df-analytics/dfanalytics-limitations.asciidoc
Related to https://github.com/elastic/ml-cpp/pull/1276 and https://github.com/elastic/ml-cpp/pull/1109
This PR adds a limitation (applicable to both anomaly detection and dataframe analytics jobs) that makes it clear that the CPU scheduling improvements apply only to Linux and MacOS.
=> [DOCS] Add ML CPU scheduling limitation

docs/en/stack/ml/df-analytics/dfa-regression.asciidoc, docs/en/stack/ml/df-analytics/ml-dfa-concepts.asciidoc
This PR expands the regression conceptual documentation with a high-level explanation of loss functions. 
[Regression](http://stack-docs_1062.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-regression.html#regression-lossfunction)
=> [DOCS] Adds loss function description to regression conceptual docs

docs/en/stack/landing-all.asciidoc, docs/en/stack/landing.asciidoc
This PR drafts further changes to the landing page, in particular, the removal of the top-level "Guides" section and the addition of "Elastic" to the solution names.
It also moves the APIs, release notes, and breaking changes out from within the Reference section.
=> [DOCS] Removes top-level guides section from landing page

docs/en/stack/index-landing-all.adoc, docs/en/stack/index-landing.adoc, docs/en/stack/index-landing.asciidoc, docs/en/stack/landing-all.asciidoc, docs/en/stack/landing.asciidoc, docs/en/stack/redirects-landing.adoc
This PR drafts the inclusion of the ESS APIs (https://www.elastic.co/guide/en/cloud/current/ec-restful-api.html) in the landing page.
The following PR must be merged first: https://github.com/elastic/elasticsearch/pull/57390
=> [DOCS] Adds ESS APIs to landing page

docs/en/install-upgrade/highlights.asciidoc
Related to https://github.com/elastic/kibana/pull/68918
The Kibana release highlights have moved, so the Installation and Upgrade Guide needs to seek the tagged sections from their new location.
=> [DOCS] Updates path to Kibana highlights

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Get ingest management docs ready to publish (#1147)
=> [7.x] Get ingest management docs ready to publish (#1147)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Get ingest management docs ready to publish (#1147)
=> [7.8] Get ingest management docs ready to publish (#1147)

docs/en/ingest-management/index.asciidoc
- Temporarily comment out overview (#1157)
=> [7.x] Temporarily comment out overview (#1157)

docs/en/ingest-management/index.asciidoc
- Temporarily comment out overview (#1157)
=> [7.8] Temporarily comment out overview (#1157)

docs/en/ingest-management/index.asciidoc
- Get agent docs building (#1163)
=> [7.x] Get agent docs building (#1163)

docs/en/ingest-management/index.asciidoc
- Get agent docs building (#1163)
=> [7.8] Get agent docs building (#1163)

docs/en/stack/ml/get-started/get-started-prereqs.asciidoc
This PR modifies the 3rd step of the Prerequisites section of ML getting started to reflect recent changes on the UI.
The changes apply to 7.8, 7.x, and 8.0. Version 7.7 still uses the Kibana logo.
[Prerequisites](https://stack-docs_1179.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-getting-started.html)
=> [DOCS] Modifies instruction in ML getting started to reflect UI changes

docs/en/ingest-management/troubleshooting.asciidoc
@dedemorton FYI - let me know if you need anything more.  I'll keep reviewing.
Beats 'issues' link linked to:
https://github.com/elastic/beats/issuess
screenshot:
=> fix hyperlink typo for Beats issues

docs/en/install-upgrade/breaking.asciidoc
This PR must be merged after https://github.com/elastic/kibana/pull/68588 is backported to 7.8.
It uncomments the Kibana 7.8 breaking changes in the Installation and Upgrade Guide.
=> [DOCS] Uncomments Kibana breaking changes

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Adds APM breaking changes and release highlights to the installation and upgrade guide for `7.8`.
Blocked by https://github.com/elastic/apm-server/pull/3869.
=> [7.8] docs: add APM to release highlights and changes

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/ingest-management-limitations.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/overview.asciidoc
Summary of changes:
* Edit to conform to Elastic style guidelines.
* Modify asciidoc markup (I made structural changes that necessitated this)
* Add line breaks (makes for easier diffs in the future)
* Move limitations to a separate topic so one topic = one html page
Open question: Do we want limitations at the same level as the overview or nested under it as it is now? 
(Sorry that the diff doesn't show changes very well, but I made a lot of changes, so please read all the text.)
=> Edit ingest management overview

docs/en/ingest-management/troubleshooting.asciidoc
- fix hyperlink typo for Beats issues (#1172)
=> [7.x] fix hyperlink typo for Beats issues (#1172)

docs/en/ingest-management/troubleshooting.asciidoc
- fix hyperlink typo for Beats issues (#1172)
=> [7.8] fix hyperlink typo for Beats issues (#1172)

docs/en/getting-started/get-started-stack.asciidoc
This PR fixes an outdated links to the Stack Overview book, which is no longer used.
=> [DOCS] Fixes license management link

docs/en/ingest-management/getting-started.asciidoc
Softens the wording so users are not misled into thinking there are no additional config steps required.
=> Change misleading sentence about required config settings

docs/en/ingest-management/getting-started.asciidoc
- Change misleading sentence about required config settings (#1197)
=> [7.8] Change misleading sentence about required config settings (#1197)

docs/en/ingest-management/getting-started.asciidoc
- Change misleading sentence about required config settings (#1197)
=> [7.x] Change misleading sentence about required config settings (#1197)

docs/en/siem/detections/api/rules-api-export.asciidoc, docs/en/siem/detections/api/rules-api-prebuilt.asciidoc
Fixes the use of prebuilt vs prepackages rules where possible (excluding API calls)
=> [Docs][SIEM]Fixes prebuilt rules terminology and typo

docs/en/siem/detections/api/rules-api-export.asciidoc, docs/en/siem/detections/api/rules-api-prebuilt.asciidoc
- fixes terminology and typo (#1200)
=> [7.x] fixes terminology and typo (#1200)

docs/en/siem/detections/api/rules-api-export.asciidoc, docs/en/siem/detections/api/rules-api-prebuilt.asciidoc
- fixes terminology and typo (#1200)
=> [7.8] fixes terminology and typo (#1200)

docs/en/glossary/glossary.asciidoc, docs/en/glossary/index.asciidoc, docs/en/glossary/intro.asciidoc
Depends on https://github.com/elastic/kibana/pull/69721 and https://github.com/elastic/docs/pull/1875
This PR adds alphabetical sections and links to the Glossary (https://www.elastic.co/guide/en/elastic-stack-glossary/current/index.html). It also moves the "Introduction" page into the "Terminology" page, so that there's only one page in this book.
https://stack-docs_1214.docs-preview.app.elstc.co/guide/en/elastic-stack-glossary/master/terms.html
=> Adds alphabetical links to Glossary

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/ingest-management-limitations.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Clean up ingest management docs (#1211)
=> [7.x] Clean up ingest management docs (#1211)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/ingest-management-limitations.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Clean up ingest management docs (#1211)
=> [7.8] Clean up ingest management docs (#1211)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- [DOCS] Document encryption key setting needed by Fleet (#1224)
=> [7.8] [DOCS] Document encryption key setting needed by Fleet (#1224)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- [DOCS] Document encryption key setting needed by Fleet (#1224)
=> [7.x] [DOCS] Document encryption key setting needed by Fleet (#1224)

docs/en/observability/index.asciidoc, docs/en/observability/observability-introduction.asciidoc, docs/en/observability/observability-ui.asciidoc
This PR adds content placeholders for the forthcoming Observability docs. This directory and the files will be included in the migration of the Logs and Metrics directories to the new Observability repo. 
The following PRs need to be merged before migrating the Logs and Metrics directories:
https://github.com/elastic/stack-docs/pull/1210
https://github.com/elastic/stack-docs/pull/1203
https://github.com/elastic/docs/pull/1877
=> [DOCS] Add placeholders for Observability docs

docs/en/getting-started/get-started-docker.asciidoc
Removing `xpack.security.http.ssl.*` options because the following error occurs when running `elasticsearch-setup-passwords` with these.
```
ERROR: setting [xpack.security.http.ssl.certificate] already set, saw [certificates/es01/es01.crt] and [/usr/share/elasticsearch/config/certificates/es01/es01.crt]
```
=> remove unnecessary options for elasticsearch-setup-passwords

docs/en/getting-started/docker/elastic-docker-tls.yml
A small fix that sets the correct http certificate for es03 node in docker.
=> Use es03 cert for es03 node in docker

docs/en/glossary/glossary.asciidoc, docs/en/glossary/index.asciidoc
This PR depends on https://github.com/elastic/docs/pull/1875 and https://github.com/elastic/kibana/pull/69721, which must be merged first.
It adds Kibana terms to the overall Glossary (https://www.elastic.co/guide/en/elastic-stack-glossary/current/index.html)
Preview: https://stack-docs_1213.docs-preview.app.elstc.co/guide/en/elastic-stack-glossary/master/terms.html
=> [DOCS] Adds Kibana terms to glossary

docs/en/siem/detections/detection-engine-intro.asciidoc
Adds ml rule creation requirements to the Detections prerequisites as users are having trouble finding this info.
[Preview](https://stack-docs_1230.docs-preview.app.elstc.co/guide/en/siem/guide/master/detection-engine-overview.html#detections-permissions)
=> [Docs][SIEM]Adds ml rule prerequisites 

docs/en/siem/detections/detection-engine-intro.asciidoc
- [Docs][SIEM]Adds ml rule prerequisites  (#1230)
=> [7.x] [Docs][SIEM]Adds ml rule prerequisites  (#1230)

docs/en/siem/detections/detection-engine-intro.asciidoc
- [Docs][SIEM]Adds ml rule prerequisites  (#1230)
=> [7.8] [Docs][SIEM]Adds ml rule prerequisites  (#1230)

docs/en/getting-started/get-started-stack.asciidoc, docs/en/gke-on-prem/index.asciidoc, docs/en/siem/installation.asciidoc
Updates links to reflect changes added in elastic/beats#19302.
This change applies to 7.9 and later.
Marking as WIP because I want to wait until the observability-docs repo changes are in place before finalizing.
=> Change links to refactored Beats getting started docs

docs/en/getting-started/get-started-stack.asciidoc, docs/en/siem/installation.asciidoc
- Change links to refactored Beats getting started docs (#1234)
=> [7.x] Change links to refactored Beats getting started docs (#1234)

docs/en/glossary/glossary.asciidoc, docs/en/stack/ml/setup.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/54998 and https://github.com/elastic/elasticsearch/pull/59024
This PR changes occurrences of node.ml to node.roles.
https://stack-docs_1239.docs-preview.app.elstc.co/guide/en/machine-learning/master/setup.html
https://stack-docs_1239.docs-preview.app.elstc.co/guide/en/elastic-stack-glossary/master/terms.html#m-glos
=> [DOCS] Clarifies machine learning nodes

docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc, docs/en/stack/ml/df-analytics/index.asciidoc, docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1240 and https://github.com/elastic/stack-docs/pull/1246
This PR splits the content from the anomaly-detection/index.asciidoc and df-analytics/index.asciidoc into new files with names that match their anchors/URLs. Thus the index.asciidoc files contain only structural information.
=> [DOCS] Removes ML content from index.asciidoc files

docs/en/getting-started/get-started-docker.asciidoc, docs/en/install-upgrade/installing-stack.asciidoc
Relate: https://github.com/elastic/elasticsearch/pull/58958, https://github.com/elastic/kibana/pull/70636
This PR fixes the documentation that implies a trial licence maps to a platinum subscription. It also improves some licence-related text to align with the style guide and generally tries to avoid stating which licenses are required for specific features in the docs.
Preview:
https://stack-docs_1237.docs-preview.app.elstc.co/diff
=> [DOCS] Clarify trial subscription levels

docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc
This PR amends the docs on influencers to make it clear that they are reported only if they have a statistically significant impact on the anomalousness.
[Influencer results](https://stack-docs_1269.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-influencers.html#ml-influencer-results)
=> [DOCS] Makes it clear that only significant influencers are reported

docs/en/stack/ml/df-analytics/ml-inference.asciidoc
This PR adds a new section to the inference conceptual documentation about using inference as a pipeline aggregation.
[Inference aggregation](https://stack-docs_1268.docs-preview.app.elstc.co/diff)
=> [DOCS] Expands inference conceptual docs with aggregation section

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Related to #1270 (review)
This PR groups the machine learning jobs by module rather than sorting them alphabetically in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-apm.html
https://stack-docs_1276.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-apm.html
=> [DOCS] Sorts APM ML modules

docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
This PR adds a link of a Jupyter notebook about regression loss functions to the loss function and the further reading sections of regression conceptual documentation.
[Loss functions for regression analyses](https://stack-docs_1274.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-regression.html#dfa-regression-lossfunction)
=> [DOCS] Adds Jupyter notebook link to loss function section of regression conceptual

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc
Related to https://github.com/elastic/kibana/pull/70361
This PR updates the list of supplied ML modules for APM to replace the high_mean_response_time job with the high_mean_transaction_duration job.
https://stack-docs_1272.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-apm.html
=> [DOCS] Updates to APM ML module for service maps

docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc, docs/en/stack/ml/df-analytics/ml-dfanalytics.asciidoc, docs/en/stack/ml/setup.asciidoc
This PR changes one of the main menu items name to `Setup and security` from `Setup`. It also adds a link that points to this page to the first page of the anomaly detection and the data frame analytics sections.
[Anomaly detection](https://stack-docs_1283.docs-preview.app.elstc.co/guide/en/machine-learning/master/xpack-ml.html)
[DFA](https://stack-docs_1283.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfanalytics.html)
=> [DOCS] Changes menu item name to Setup and security in ML book

docs/en/getting-started/get-started-docker.asciidoc, docs/en/install-upgrade/upgrading-stack.asciidoc
> refer to: https://github.com/elastic/stack-docs/pull/1285
More links of apm-server-ref
=> [DOCS] Fix apm-server-ref links

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/overview.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1285 and https://github.com/elastic/stack-docs/pull/1286.
This PR fixes more occurrences of the "apm-server-ref-70" attribute.
https://stack-docs_1287.docs-preview.app.elstc.co/diff
=> [DOCS] Fix more apm-server-ref-links

docs/en/stack/ml/anomaly-detection/anomaly-examples.asciidoc, docs/en/stack/ml/anomaly-detection/create-jobs.asciidoc, docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/job-tips.asciidoc, docs/en/stack/ml/anomaly-detection/ml-api-quickref.asciidoc, docs/en/stack/ml/anomaly-detection/ml-buckets.asciidoc, docs/en/stack/ml/anomaly-detection/ml-calendars.asciidoc, docs/en/stack/ml/anomaly-detection/ml-concepts.asciidoc, docs/en/stack/ml/anomaly-detection/ml-configuration.asciidoc, docs/en/stack/ml/anomaly-detection/ml-datafeeds.asciidoc, docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc, docs/en/stack/ml/anomaly-detection/ml-jobs.asciidoc, docs/en/stack/ml/anomaly-detection/ml-limitations.asciidoc, docs/en/stack/ml/anomaly-detection/ml-model-snapshots.asciidoc, docs/en/stack/ml/anomaly-detection/ml-overview.asciidoc, docs/en/stack/ml/anomaly-detection/ml-rules.asciidoc, docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-uptime.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc, docs/en/stack/ml/anomaly-detection/stopping-ml.asciidoc, docs/en/stack/ml/anomaly-detection/xpack-ml.asciidoc, docs/en/stack/ml/get-started/ml-gs-results.asciidoc, docs/en/stack/ml/redirects.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/59911
This PR improves the consistency of machine learning anomaly detection pages such that all of the source files begin with the same section title level (=).  It also temporarily omits the files included from the elasticsearch repo, so that they can be renamed in the elasticsearch PR.
=> [DOCS] Changes level offset for anomaly detection pages

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Related to https://github.com/elastic/kibana/pull/71323
This PR adds the new jobs from the siem_cloudtrail module (https://github.com/elastic/kibana/tree/master/x-pack/plugins/ml/server/models/data_recognizer/modules/siem_cloudtrail) to the list of SIEM machine learning jobs in https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html
* https://stack-docs_1270.docs-preview.app.elstc.co/guide/en/security/master/prebuilt-ml-jobs.html
* https://stack-docs_1270.docs-preview.app.elstc.co/guide/en/siem/guide/master/prebuilt-ml-jobs.html
* https://stack-docs_1270.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html
=> [DOCS] Adds siem_cloudtrail module

docs/en/stack/ml/df-analytics/ml-dfa-overview.asciidoc, docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
Relates to https://github.com/elastic/elasticsearch/issues/59947
This PR renames the binary_soft_classification evaluation type to outlier_detection in order to avoid confusion.
* https://stack-docs_1300.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfanalytics-evaluate.html
* https://stack-docs_1300.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-overview.html
=> [DOCS] Rename binary_soft_classification evaluation

docs/en/install-upgrade/highlights.asciidoc
Changing the link in the release highlights to support a parallel change I'm making in Beats (to align with Kibana practice of providing a "What's new" topic instead of "Release highlights."
Related PR: https://github.com/elastic/beats/pull/20255
=> Change highlights path

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
This PR expands the conceptual documentation of regression and classification with a section about possible further steps after training the model and adds a link that points to the inference conceptual piece.
[Regression – Deploying the model](https://stack-docs_1273.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-regression.html#dfa-regression-deploy)
[Classification – Deploying the model](https://stack-docs_1273.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfa-classification.html#dfa-classification-deploy)
=> [DOCS] Adds Deploying the model section to regression and classification conceptual

docs/en/stack/ml/df-analytics/dfa-classification.asciidoc, docs/en/stack/ml/df-analytics/dfa-regression.asciidoc
This PR backports the changes in the following PR to the 7.8 branch but excludes the reference to the inference pipeline aggregation as it is introduced in 7.9: 
[DOCS] Adds Deploying the model section to regression and classification conceptual #1273
=> [7.8][DOCS] Adds Deploying the model section to regression and classification conceptual

docs/en/install-upgrade/highlights.asciidoc
- Activate include for Beats highlights (#1311)
=> [7.x] Activate include for Beats highlights (#1311)

docs/en/install-upgrade/highlights.asciidoc
- Activate include for Beats highlights (#1311)
=> [7.9] Activate include for Beats highlights (#1311)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
Changes SIEM ML job group names to Security, and updates the name of the app.
[Preview](https://stack-docs_1317.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-siem.html)
=> [Docs][ML]Updates ML job group names

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-siem.asciidoc
- [Docs][ML]Updates ML job group names (#1317)
=> [7.9] [Docs][ML]Updates ML job group names (#1317)

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Blocked by https://github.com/elastic/apm-server/pull/4033.
=> [7.9] Add APM release highlights / breaking changes

docs/en/stack/ml/df-analytics/dfanalytics-examples.asciidoc
This PR updates the DFA examples in blog posts section on the DFA examples page with the latest related blog posts.
[DFA examples](https://stack-docs_1322.docs-preview.app.elstc.co/guide/en/machine-learning/master/dfanalytics-examples.html)
=> [DOCS] Adds blog links to the DFA examples page

docs/en/stack/ml/df-analytics/ml-dfanalytics-apis.asciidoc
This PR adds Inference API links to the data frame analytics API quick reference page.
[DFA API quick reference](https://stack-docs_1323.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfanalytics-apis.html)
=> [DOCS] Adds inference API links to DFA API quick reference

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
Depends on https://github.com/elastic/elasticsearch/pull/60695
This PR uncomments the Elasticsearch 7.9.0 release highlights and breaking changes.
https://stack-docs_1326.docs-preview.app.elstc.co/guide/en/elastic-stack/7.9/elasticsearch-highlights.html
https://stack-docs_1326.docs-preview.app.elstc.co/guide/en/elastic-stack/7.9/elasticsearch-breaking-changes.html
=> [DOCS] Enables ES highlights and breaking changes in Install Upgrade Guide

docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
This PR adds the `inference` phase and its description to the `How a data frame analytics job works` section. Applies to 7.9 and above.
[How a DFA job works – Inference phase](https://stack-docs_1327.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-phases.html#ml-dfa-phases-inference)
=> [DOCS] Adds inference phase to how a DFA job works section

docs/en/stack/ml/df-analytics/ml-dfa-phases.asciidoc
This PR changes the verb `infer` to `validate` in the description of the inference phase to differentiate it from the inference process that happens in a pipeline, in an aggregation, or in a continuous transform. Applies to 7.9 and above.
[How a data frame analytics job works]()
=> [DOCS] Fine-tunes wording in inference phase description

docs/en/stack/ml/anomaly-detection/ml-influencers.asciidoc, docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc, docs/en/stack/ml/df-analytics/ml-lang-ident.asciidoc
This PR adds a `Further reading` section to the Influencers chapter in the AD docs and adds a link of a related blog post.
[Influencers](https://stack-docs_1339.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-influencers.html)
=> [DOCS] Adds further reading section to Influencers

docs/en/stack/ml/anomaly-detection/index.asciidoc, docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/61195
This PR publishes symptoms and work-arounds for a known problem in 7.9.0.
https://stack-docs_1337.docs-preview.app.elstc.co/guide/en/machine-learning/7.9/ml-troubleshooting.html
=> [DOCS] Adds ML troubleshooting for upgrade

docs/en/install-upgrade/breaking.asciidoc, docs/en/install-upgrade/highlights.asciidoc
This PR removes the coming[7.9.0] tags from the Installation and Upgrade Guide.
=> [DOCS] Removes coming tags from installation upgrade guide

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
- [DOCS] Fixes typo in OOTB metricbeat jobs. (#1345)
=> [7.x] [DOCS] Fixes typo in OOTB metricbeat jobs. (#1345)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc
- [DOCS] Fixes typo in OOTB metricbeat jobs. (#1345)
=> [7.9] [DOCS] Fixes typo in OOTB metricbeat jobs. (#1345)

docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apache.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-apm.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-auditbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-logs-ui.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-metricbeat.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs-nginx.asciidoc, docs/en/stack/ml/anomaly-detection/ootb-ml-jobs.asciidoc
This PR makes the following changes on the OOTB AD jobs content:
* removes the links that refer to the used function for each job
* removes the `partition_field_name` value when it is not important to provide
* makes the `partition_field_name` value the part of the sentence when it is important
* adds a `titleabbrev` to the main page.
* [Apache](https://stack-docs_1348.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-apache.html)
* [APM](https://stack-docs_1348.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-apm.html)
* [Auditbeat](https://stack-docs_1348.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-auditbeat.html)
* [Logs UI](https://stack-docs_1348.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml- …
=> [DOCS] Modifies OOTB jobs content

docs/en/glossary/glossary.asciidoc
This PR adds the following Observability terms to the Elastic Glossary:
* **Observability**
* **Agent (APM)**
* **Server (APM)**
* **Distributed tracing**
* **Instrumentation**
* **Real User Monitoring (RUM)**
* **Span**
* **Trace**
* **Transaction**
* **Ingestion**
* **Integration**
* **Module**
* **Monitor**
* **Uptime**
I didn't source these terms from the `observability-docs` repo because we don't have any short-term plans to host an Observability glossary.
Closes https://github.com/elastic/observability-docs/issues/34.
=> docs: add Observability terms to glossary

docs/en/stack/ml/anomaly-detection/ml-troubleshooting.asciidoc
The incorrect mappings problems that affected 7.9.0 are resolved
as far as possible in 7.9.1, but:
1. It is still possible that the ML config index has incorrect
mappings if these occurred due to a chain of upgrades through
various 7.x versions prior to 7.9.0
2. We need to make clear that if incorrect mappings occurred due
to upgrading to 7.9.0 then upgrading to 7.9.1 will not magically
fix these - reindexing is still required to do this
=> Adjust ML mappings known issue

docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
This PR expands the DFA evaluation conceptual docs with the description of classification AUC ROC.
[AUC ROC](https://stack-docs_1365.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfanalytics-evaluate.html#ml-dfanalytics-class-aucroc)
=> [DOCS] Adds classification AUC ROC metric description

docs/en/stack/ml/df-analytics/ml-dfanalytics-evaluate.asciidoc
- [DOCS] Adds classification AUC ROC metric description (#1365)
=> [7.x] [DOCS] Adds classification AUC ROC metric description (#1365)

docs/en/stack/ml/df-analytics/ml-feature-importance.asciidoc
The [feature importance documentation](https://www.elastic.co/guide/en/machine-learning/master/ml-feature-importance.html) says:  "The magnitude of feature importance shows how significantly the feature affects the prediction both locally (for a given data point) or generally (for the whole data set)."  However, you must take extra steps to aggregate the data to determine the importance for the whole data set, so this statement is misleading.
https://stack-docs_1369.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-feature-importance.html
=> [DOCS] Feature importance clarification

docs/en/stack/ml/df-analytics/flightdata-classification.asciidoc
The machine learning [classification example](https://www.elastic.co/guide/en/machine-learning/master/flightdata-classification.html) currently states that the "most probable class is the prediction", but it is the class with the highest score. This PR fixes the text in that section.
https://stack-docs_1368.docs-preview.app.elstc.co/guide/en/machine-learning/master/flightdata-classification.html
=> [DOCS] Fix classification score details in example

docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
This PR adds a limitation item about the number of training documents to the DFA limitations section.
[DFA Limitations](https://stack-docs_1370.docs-preview.app.elstc.co/guide/en/machine-learning/master/ml-dfa-limitations.html#dfa-training-docs)
=> [DOCS] Adds DFA limitation item about number of training documents

docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Adds DFA limitation item about number of training documents (#1370)
=> [7.9] [DOCS] Adds DFA limitation item about number of training documents (#1370)

docs/en/stack/ml/df-analytics/ml-dfa-limitations.asciidoc
- [DOCS] Adds DFA limitation item about number of training documents (#1370)
=> [7.x] [DOCS] Adds DFA limitation item about number of training documents (#1370)
